### ISSUE TITLE
Unable to add wildcard meta to oreDict entry

### ISSUE THREAD

**Issue by MikeBurk** [stanhebben/MineTweaker3#100]
This may be a user error, or may not be implemented...

I was trying:
val seat = ore:seat;
seat.addAll(<BiblioCraft:BiblioSeats:*>);

This yields "a method available but none matches the parameters (minetweaker.item.IItemStack).

The idea being to use the wildcard to get all of the items with that id and assign them to the new oreDict value. It seems like the wildcard is not actually returning me an ItemStack to work with addAll. I tried just add, but only works if I call out each meta id (or 0 by default if I do none).

Is this a user error or is something not intuitive about addAll? Thanks.

Continuation:
rebooting the server with:
val seat = <ore:seat>;
seat.add(<BiblioCraft:BiblioSeats:*>);

The "add" alone yields Error executing AoS-Core-Tweaks.zs: 32767

This is Minecraft 1.7.10 with Forge 1.7.10-10.13.1.1226.  MineTweaker3-1.7.10-3.0.9

**Comment by jaredlll08** [comment]
This is very much user error, the addAll method asks for an oreDictionary, for example
```
val seat = <ore:seat>;
seat.addAll(<ore:stick>);
```
That will add everything under `<ore:stick>` to `<ore:seat>`
I would suggest you look at the wiki for an example on loops, as you can then loop through the metadata
