### ISSUE TITLE
[Question] Specifying certain items...

### ISSUE THREAD

**Issue by SnowShock35** [stanhebben/MineTweaker3#102]
Hi Stan,

Thought this would be a better place to ask a question about minetweaker 3 than twitter so here it is.

If for instance you have thermal expansion basic hardened reinforced and resonant machines, however I believe (correct me if I am wrong) that CoFH uses NBT to differentiate between tiers of machines. So my question is, Is it possible to specify the different tiers of machine in minetweaker currently?

Let us know when you can.
-Snow

**Comment by jaredlll08** [comment]
Hey there! I'm not stan, but I think I know the problem to your issue... 

```[1, 1, 2, 2, 2, 2] as byte[] as byte[],```
you are assigning a byte[] as a byte[], so remove that second byte[] and see if it works!

Once again, sorry for not being Stan :P
