### ISSUE TITLE
GregTech meta tools

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#103]
When i make a recipe script where GregTech tool is used as a ingredient, it will only lower the durability by 100. Thats completely fine when using hammers, wrenches, etc... but when i use for example a Electrum Hoe, i expect the hoe to be consumed.

So I would like to request an option to "force" consume the item. Or is there already a way how to do this?

Thank you

**Comment by Timeslice42** [comment]
The issue here being that there needs to be a difference between crafting tools (i.e. using a hammer in a recipe with ingots to make plates) and crafting components (i.e. crafting an MFR harvester with a GT hoe instead of a vanilla hoe).

**Comment by UndeadZeratul** [comment]
Isn't there already a way to damage or consume items?  [Yeah, here](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes#Output_reuse_and_transformations), there's a transformDamage() and a transformConsume() method that you can use to damage the tool, or consume more than one item in a crafting recipe.  There's others, but those should help you do what you want.

**Comment by jaredlll08** [comment]
This can be achieved using the .noReturn() function
