### ISSUE TITLE
IllegalArgumentException when using /minetweaker blockinfo

### ISSUE THREAD

**Issue by BLAMM67** [stanhebben/MineTweaker3#107]
Had a crash after activating the "/minetweaker blockinfo" command to look into an id conflict issue I'm having. I don't think the crash is directly related to that issue, but I'll describe it for context.
I was in a SSP game when this occurred. I'm having an issue between Ancient Warfare and JABBA. The AW crafting tables and the JABBA structural upgrades seem to be having an id conflict. They appear to share an in-game object. The crafting recipe and image is that of the crafting table, but the name and behavior is that of the upgrade; it upgrades barrels. I was using MT to diagnose the issue. I was holding a "crafting table" and accidentally right-clicked to place it on the ground to look at it with the mt blockinfo tool, forgetting that it behaved like a JABBA upgrade. The crash occurred as soon as I right-clicked. Not sure why it would do that instead of just giving me the data for the grass block I clicked on but I assume it had something to do with the non-block item I was holding at the time.

Crash Report
http://pastebin.com/0xvDivd1

**Comment by jaredlll08** [comment]
This was fixed a while ago
