### ISSUE TITLE
Could not resolve?

### ISSUE THREAD

**Issue by Tsugaga** [stanhebben/MineTweaker3#108]
I used /mt names and looked up the name for BuildCraft Additions iron dust. I also used /mt hand and got the same name. It's <bcadditions:dustIron>, but when I create a variable for it, mt returns "Could not resolve <bcadditions:dustIron>". This happens with other BCA items too. Is this an issue with BCA or MT? What do I do if I get this error? And yes, I'm positive that I've made no mistakes, I've successfully made hundreds of other variables and recipes.

**Comment by Timeslice42** [comment]
Just an idea: maybe it's an issue with the modID. Look really closely, do you see any whitespace before or after the mod ID? Like, does /mt hand actually say bcadditions :dustIron instead?

**Comment by Tsugaga** [comment]
Hmm, nope, it's the same as other mods. puu.sh/efYh1/b2d6b93d5b.png

**Comment by UndeadZeratul** [comment]
You put angle brackets around the item name, right?  like \<bcadditions:dustIron\>?

If not, IIRC, bspkrs core adds a file called UniqueNames to your config folder, should help in finding the names of items.

**Comment by jaredlll08** [comment]
from the looks of it, it was a problem with the angle brackets
