### ISSUE TITLE
[Question]/[Bug] - Unhiding things from nei requires a restart of the client

### ISSUE THREAD

**Issue by SnowShock35** [stanhebben/MineTweaker3#109]
Hi @stanhebben,

So this is kinda a question but could possibly be a bug.

Forge: 1230
Minetweaker: 3.0.9c

Desc: Ok so here I have a screen shot of my NEI hiding script...
![untitled](https://cloud.githubusercontent.com/assets/8388680/5154299/4fdde0b6-724c-11e4-83df-e5bf6d3e9a33.png) When I hide  them it seems to work on when I do /mt reload in-game however if I remove them it doesn't update nei unless I restart client it also has a few other weird things where it doesn't always sync up/update when using /mt reload.

**Comment by kerts93** [comment]
We have noticed that sometimes it hides all items, but after client restart sometimes it only hides the ones with specified IDs.

**Comment by jaredlll08** [comment]
https://github.com/stanhebben/MineTweaker3/issues/205#issuecomment-137717090
