### ISSUE TITLE
Recipe issue with iChun's Portalgun mod

### ISSUE THREAD

**Issue by Ionaru** [stanhebben/MineTweaker3#110]
I am having an issue with iChun's portal mod. For some, but not all items, the recipe changes do not load on startup until I do '/mt reload' in-game. 

I do not use CraftingManager.

MineTweaker file: http://pastebin.com/yzG2LTaj
Using MineTweaker 3.0.9B for 1.6.4.

From startup:

![2014-10-24_01 51 22](https://cloud.githubusercontent.com/assets/3472373/4763328/b2adda38-5b0f-11e4-9700-027cc7821a77.png)

After '/mt reload'

![2014-10-24_01 55 21](https://cloud.githubusercontent.com/assets/3472373/4763336/1a75964c-5b10-11e4-9c89-59fd0f753f99.png)

I posted this in an earlier issue related to the Sync mod a while ago, but it did not get a reply or any recognition.

**Comment by jaredlll08** [comment]
Ichun registers his recipes too late for us to actually edit them on first go, this is a bug on HIS side.
