### ISSUE TITLE
Error Parsing

### ISSUE THREAD

**Issue by Gunner76th** [stanhebben/MineTweaker3#113]
[18:52:43] [Client thread/INFO]: [CHAT] ERROR: Error parsing opfixes.zs:1 -- ) expected

That is what I get when I try to do /mt reload. the script is:

oreDict.dyeBlue.remove(minecraft:dye);

this method works just fine for other ore dictionary removals, but for some reason it is erroring when I try to remove dye entries.

**Comment by stanhebben** [comment]
In case this is still relevant, you'd need &lt;minecraft:dye:4&gt;
