### ISSUE TITLE
Reload keeps script files open

### ISSUE THREAD

**Issue by wleader** [stanhebben/MineTweaker3#114]
When I am working on my scripts, I like to have the script open in one window and have my server running in the console. I load the server, and the console shows the scripts executing without error. Then I make a change in my editor program and save the script file. In the console I use the /mt reload command. The console shows the scripts running without error. I switch back to the script editor, make a change. When I save, my editor can not save the file because it is open by another application. I stop the server. I go back to the editor and save my changes. I can then restart the server and have the changed scripts run without error.

OS: Windows 7
MT: MineTweaker3-1.7.10-3.0.8B.jar
Server: forge-1.7.10-10.13.2.1230-universal.jar

java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

**Comment by stanhebben** [comment]
Found the culprit. Will have it fixed in the next release.

**Comment by jaredlll08** [comment]
considering 3.0.8B is an old version I'm sure that this can be closed. (also have never experienced it in later versions)
