### ISSUE TITLE
[Feature Request] Simple Execution Order Support

### ISSUE THREAD

**Issue by Mictali** [stanhebben/MineTweaker3#116]
A simple approach to providing some level of script load execution order would only take this change in the class ScriptProviderDirectory:

	@Override
	public Iterator<IScriptIterator> getScripts() {
		List<IScriptIterator> scripts = new ArrayList<IScriptIterator>();
		if (directory.exists()) {
			for (File file : directory.listFiles()) {
				if (file.isDirectory()) {
					scripts.add(new ScriptIteratorDirectory(file));
				} else if (file.getName().endsWith(".zs")) {
					scripts.add(new ScriptIteratorSingle(file));
				} else if (file.getName().endsWith(".zip")) {
					try {
						scripts.add(new ScriptIteratorZip(file));
					} catch (IOException ex) {
						MineTweakerAPI.logError("Could not load " + file.getName() + ": " + ex.getMessage());
					}
				}
			}
		}

     ///Add this part to sort the scripts
    Collections.sort(scripts, new Comparator<IScriptIterator>()
                     {
                       public int compare(IScriptIterator one, IScriptIterator two) {
                         return one.getName().compareTo(two.getName());
                       }
                     });
		return scripts.iterator();
	}

Now, with this small addition, all that is needed to define an execution order for the scripts is to name them with incrementing numbers:

   01_oredictionary.zs
   02_recipes.zs
   03_anythingelse.zs

The string comparison will order them 01, 02, 03 so they'll come out of the iterator in that order.

**Comment by Timeslice42** [comment]
This feels like a bit of a hacky solution, it being a hidden feature type of change. I prefer MT 2's solution, which was to have a "main" script which let you explicitly specify the script load order. What was the driving reason behind removing the "main" script feature from MT 3?

**Comment by Mictali** [comment]
Not sure about being hacky, this is the model Unix and Linux start up
scripts use.  They are numbered this way so their startup order can be
set.  Means you don't have to maintain a load script.  But both ways work.

**Comment by UndeadZeratul** [comment]
IIRC, Stan wants to add that import functionality back in.  It may be in 3.1.0, and not 3.0.10 or whatever else, but I've seen mentions of having scripts that end in .zsi (a ZenScript Import file, if you will), and you just write import "myImport.zsi" in your other files.

This will end up doing what you mentioned about MT2's way of doing it.

**Comment by Mictali** [comment]
It's his call how he wants to do it.  Just pointing out there's a fairly trivial way it can be done that has some history behind it.

**Comment by stanhebben** [comment]
The problem with the main script is that you couldn't just install scripts from different sources and expect them to work. But then there is indeed the issue of shared declarations, for which the include files will be handy.

The goal is to provide more functions to MineTweaker (that's also the reason why I'm doing a lot of work upgrading the scripting system to be more capable) and then being able to share scripts easily will become handy - you can just drop them in the scripts folder and expect them to work.

**Comment by UndeadZeratul** [comment]
So you'd load any and all .zs files that exist, but each .zs file can have any number of .zsi imports, so you can have your shared library/libraries as .zsi files, and each script that uses them just imports them as necessary?  That way when the game loads, it'll pick up each .zs script, which will in turn import each .zsi file as necessary?

You could still end up having a "main" script if you structured your files that way, I guess.  I am curious though, if you import a file, which in turn imports more files, would that work?  If I wanted to have my main script just import a bunch of aggregated library .zsi files, which they themselves consist of numerous .zsi imports of  separate mod library declaration files, would they get passed back up the import stack into the main file as expected?

Having that sort of tree structure could really help organize my script files.

**Comment by stanhebben** [comment]
Yes, it will work recursively, and if you have a single .zs script loading the others as includes it would indeed be the same as the old system.

**Comment by Blue64** [comment]
yeah, pretty much. It'd end up looking like this once loaded:
```
Main.zs
Import sub1.zsi
(
    sub1.zsi
    import sub2.zsi
    (
        sub2.zsi
        var bob = <minecraft:dirt>
        var steve = <minecraft:cobblestone>
    )
)
recipe.addshapeless(steve*3, bob, bob, bob)
```
result: 3 dirt into 3 cobblestone ```:P```

**Comment by Blue64** [comment]
on a related note, how would this get enforced [here](https://github.com/stanhebben/MineTweaker3/issues/297#issuecomment-165657911) (need to load only Single Player during Single Player, and only Server during Server, preferably without deleting either cluster of files)

**Comment by jaredlll08** [comment]
Scripts are now sorted, that should help with execution order shouldn't it?
