### ISSUE TITLE
Error in command /mt hand

### ISSUE THREAD

**Issue by sheynandr** [stanhebben/MineTweaker3#117]
Execute command /mt hand throws error in console. Error see in my gist https://gist.github.com/sheynandr/0535e6cf81cd8ea535c4.

Version server: Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by jaredlll08** [comment]
This has been fixed by Stan in a previous version.
