### ISSUE TITLE
Gregtech Shapes/mold get consumed in their machine

### ISSUE THREAD

**Issue by xF4m3** [stanhebben/MineTweaker3#123]
Basically it would be nice if you could make a mold/shape in an Alloy smelter/extruder to not be consumed. Just like in some gregtech recipes (4 steel + extruder shape(Gear)= 1 Steel Gear)
but the extruder shape should not be consumed so I can make multiple gears without loosing the shape.
If that is already a thing somehow, Id like to know what i need to do that the shape/mold is not lost in the process

**Comment by Timeslice42** [comment]
A note on the wiki would be nice too :)

**Comment by xF4m3** [comment]
Totally forgot abput that, The display issue seems to be gone, but I don't know why and I also don't know if that may was a mod constellation or something, it also shows a little tool tip that says: does not get consumed in the process

**Comment by stanhebben** [comment]
Could it be a gregtech upgrade doing the trick?

**Comment by xF4m3** [comment]
Not sure, but I don't remember updating in the mod between those two tests
I know its working on gregtech 5.07.07 now for sure(just for refrence if people have the same problem)

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
