### ISSUE TITLE
.addTooltip not respecting NBT data tags

### ISSUE THREAD

**Issue by Timemon** [stanhebben/MineTweaker3#127]
I was changing the way botania worked found that tooltips dont respect nbt tags. This stops me from adding a tool tip to only one type of flower and effects all types of "<Botania:specialFlower>". This bug would affect the ability to add tooltips to multiple other mods items which determine things through nbt.
<Botania:specialFlower>.withTag({type:"jadedAmaranthus"}).addTooltip(format.yellow("Can be found in Dungeon Chests"));
<Botania:specialFlower>.withTag({type:"jadedAmaranthus"}).addTooltip("Can be used to get Mystical Flowers");

![2015-01-03_11 37 46](https://cloud.githubusercontent.com/assets/8180536/5600987/fb4868ca-933c-11e4-8f25-deae6a890e95.png)

**Comment by stanhebben** [comment]
Sorry for the late reply. You need onlyWithTag for this case, just as with recipe ingredients.

**Comment by Timemon** [comment]
Yeah that works. Thanks for the help. Sorry for the derp
