### ISSUE TITLE
Wildcard on output item causes a crash

### ISSUE THREAD

**Issue by JDonut** [stanhebben/MineTweaker3#129]
I've attempted to use a wildcard on the output item as seen here:
    `recipes.addShaped(<ProjRed|Transmission:projectred.transmission.framewire:*>,
        [[<minecraft:stick>, <ProjRed|Transmission:projectred.transmission.wire>, <minecraft:stick>]]);`

Doing a `/mt reload` shows `Scripts Reloaded`, suggesting that Minetweaker doesn't see an issue with this. When I attempt to make this item in the crafting menu, the game crashes the moment I place the final item in the crafting grid. Only the client crashes. I'm running `MineTweaker3-1.7.10-3.0.9B.jar`.

I'm not certain how you would "fix" this behavior. ProjectRed has several colors of wire that all share an id and differentiate color based on subid. Framed wire follows the same pattern. I was hoping putting the wildcard on the output item would cause Minetweaker to match the input subid to the output subid, but I realized after it crashed that it would be difficult (if not impossible) to just know which subid to make the output item.

My suggestion would be to circumvent the issue altogether and throw an error when a wildcard is put on an output item.

**Comment by stanhebben** [comment]
An output item can never be a wildcard. It always has to be a specific item - how would MC/PR/MT know which item to craft? We can deduce that intuitively, but the crafting system isn't that smart.

You have to add a recipe for every color. For loops can help you with that - see the wiki for examples.

**Comment by JDonut** [comment]
I realize MT wouldn't know what to craft. The fact remains that MT successfully reloads scripts when a wildcard is applied to an output item, and then subsequently crashes the moment someone attempts to craft the item. MT should throw a warning about a wildcard on the output item or something.

Thanks for the pointer on for loops. I didn't know MT could do for loops. That makes my life a lot easier.

**Comment by stanhebben** [comment]
Flagged as a bug since it should give an error rather than crashing.

**Comment by jaredlll08** [comment]
after looking around and thinking about it... there isn't really a good place to post the error, minetweaker can't detect if something is an output, it is seen as an IItemstack.

**Comment by jaredlll08** [comment]
Yea, there is no good way to do this, as we can't tell if an item is an output, I say just use common sense and don't have a wildcard in an output...
