### ISSUE TITLE
[Mod Suggestion]: Please update Buildcraft Support or Documentation to BC 6.2.6 or higher

### ISSUE THREAD

**Issue by Lanse505** [stanhebben/MineTweaker3#130]
Hello!, I'm a mod pack author who's working on a HEAVILY Minetweaker/Modtweaker based Map and i've noticed your Buildcraft API and Documentation is outdated and doesnt work with BC 6.2 and up which is kinda sad :(.

Is this something that could be updated without too big of hassel?, would love to get BC tweaks into my maps progression path :)

//Sincerely 
Lanse

**Comment by stanhebben** [comment]
I have been informed by asie that BuildcraftCompat now includes MT support. Mind checking that out?

**Comment by Lanse505** [comment]
Sure, brb

**Comment by Lanse505** [comment]
Hmm, so BC Compat has MT support, however we cant update to BC 6.3 due to LogisticPipes, welp guess thats another thing i have to wait for :P. Anyway Thanks Hebben-senpai!
