### ISSUE TITLE
[Suggestion] Command for block Texture Name

### ISSUE THREAD

**Issue by BlakeDarwinXE** [stanhebben/MineTweaker3#134]
It would be nice to have a command to get a block/item's Texture name.

**Comment by jaredlll08** [comment]
I don't really see the point of this... but do you want like
/mt texture
and that will output something like
<minecraft:stick>, "stick"
?

**Comment by BlakeDarwinXE** [comment]
One of the mods i'm using in my modpacks is DenseOres and you need a BlockTexture name.

```
    block_0 {
        S:baseBlock=minecraft:iron_ore
        I:baseBlockMeta=0
        S:baseBlockTexture=iron_ore
        D:denseOreProbability=1.0
        I:renderType=0
        I:retroGenId=0
        S:underlyingBlock=stone
    }
```

**Comment by jaredlll08** [comment]
This is not something that we can do, since not all mods use the vanilla system, some use their own icons.
It would be easier for you to open the mod jar and find the texture for it
