### ISSUE TITLE
Problem with recipes (with tag)

### ISSUE THREAD

**Issue by unpure** [stanhebben/MineTweaker3#135]
Hey there.
I'm currently trying to create some recipes to craft all the different mana beans from thaumcraft.
All the different mana beans are the same item with different tags.

So i'm trying to add a recipe for ignis + perditio
<Thaumcraft:ItemManaBean>.withTag({Aspects: [{amount: 1, key:"ignis"}]})
<Thaumcraft:ItemManaBean>.withTag({Aspects: [{amount: 1, key:"perditio"}]})

to get gelum when crafted together
<Thaumcraft:ItemManaBean>.withTag({Aspects: [{amount: 1, key:"gelum"}]})

I checked the wiki more then one time so i dont make any mistakes.
If you create the script for that its working fine, but it also works with every other mana bean
I could use something like ignis + lux to get gelum or even gelum + gelum to get gelum.
Its showing the correct recipe in NEI btw.
No usage for every bean except ignis and perditio and no recipe for any bean except gelum.
Is there any way to get that working? Or is there anything i'm doing wrong?

I'm currently using Forge 10.13.2.1277
All other mods can be checked here: http://upclan.de/modpack/info/
Sorry for my bad english, i hope its not to hard to understand.

**Comment by unpure** [comment]
So i checked everything again and changed everything again and again.
When i'm using withTag on input and output its showing the correct recipe but gives gelum with any mana beans. When i'm using onlyWithTag for the input items its showing the recipe for gelum with the normal mana bean item without any tags. Like it would be ok to use any bean instead of only ignis and perditio. But it only creates gelum with ignis and perditio.

Long story short:
With "withTag" on input and output NEI shows the correct recipe but the recipes are broken.
With "onlyWithTag" on input NEI shows random stuff but the reipes are working.


btw. i just checked it again and with "withTag" it shows the recipe ignis + perditio = gelum for every other beans too. So showing the recipe for lux is working even without any recipe because its showing the recipe from gelum.

Again sorry for my bad english!

**Comment by stanhebben** [comment]
That's right. For an ingredient, use .onlyWithTag, but it doesn't display correctly in NEI. For an output,  use .withTag .

The incorrect display of .onlyWithTag in NEI is an issue that will be fixed in the next version. Meanwhile, you can combine .withTag and .onlyWithTag to fix the display bug.

**Comment by unpure** [comment]
How would i combine these? Can you show me an example about this?
Is it something like
bean.withTag().onlyWithTag
Or how should it look like?
And will there be some problems with the combined recipes after the next update?

**Comment by UndeadZeratul** [comment]
well, one is for output variables, one is for input...  so you can't use both on the same variable.

for instance, a simple crafting recipe example:

var output = <minecraft:diamond>;
var input = <minecraft:dirt>;
recipes.addShapeless(output.withTag({Display:{name:"Dirty Diamond"}}), [input.onlyWithTag({hasDiamond:true})]);

now, that won't work in practice, obviously, but you get the idea.

You can't do input.withTag({something_here}).onlyWithTag({something_else_here}); because one method is for inputs, or ingredients, the other is strictly for output items.

**Comment by stanhebben** [comment]
That's not correct, Undead Z. You can combine both with item.withTag(tag).onlyWithTag(tag) .

**Comment by UndeadZeratul** [comment]
oh? I did not know that, Is it just that one will be used when being an input, the other when it's being used as an output?

**Comment by unpure** [comment]
Ok so for now even when it seems to be a realy dirty workarround it seems like its working when i combine both. It shows the correct input and output in NEI and the recipes are working.
When i try to show the recipes in NEI it shows every single recipe for every mana bean.
So there are 21 pages as recipes for gelum (but only one is correct) when i have all recipes added.
Is there any workarround for that too? Its not a big deal but it looks ugly. :D

**Comment by UndeadZeratul** [comment]
if you think 21 pages is ugly, don't install GregTech, like, ever. :)

**Comment by jaredlll08** [comment]
This was resolved, nothnig we can do on our side about nei being nei
