### ISSUE TITLE
Possible to load scipts when the world is loaded

### ISSUE THREAD

**Issue by xF4m3** [stanhebben/MineTweaker3#136]
I think it would be nice if the scripts would be loaded/reloaded everytime you join a SP world or a MP world is startet up.
Nothing world-changing, but I think that this would ne a neat feature to add :)

**Comment by stanhebben** [comment]
It's already supposed to do that.

**Comment by xF4m3** [comment]
Is it? in MP thats not possible other than that (cause loading a world there means restarting the server^^ didnt think that through) but I think I need to reload the scripts when Im in the TItle menu and change a script, then join the world (gonna check on that later) might just be my imagination^^ gonna think/look things through more next time when Im asking :)
