### ISSUE TITLE
Scripts not seen by Players who join the server

### ISSUE THREAD

**Issue by xF4m3** [stanhebben/MineTweaker3#137]
I recently noticed a strange issue, since a few days we have the issue that player cant see the recipe the server has, the recipes are not send to the Server (you can craft it, just looking it up with NEI does not work).
It is possible that there was a NEI update inbetween, not sure (so many updates and changes, hard to remember everything you do^^)
Is this done over a specific port maybe? or just over the port the server is running on?

Edit:I might have changed a few recipes, but that shouldn't effect that right? because the recipes are there, its just not shown

**Comment by UndeadZeratul** [comment]
We had this issue in our private pack, and ended up just [downgrading](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/commit/467fde6c0e9146aea7a9058161d01b0025bce196) NEI to a previous version.  None of our recipes were being altered at all in either SSP or SMP.  The crafting recipes wouldn't even work, so it's not like you could just manually craft them by memory.

**Comment by xF4m3** [comment]
Pretty sure 1.0.3.77 is working, we upgrades to the same version as you so I would bet its NEI causing this, or the api need to be updated in minetweaker (I dont have much knowledge when it come to coding itself, this is just my stomach telling me so, and a bit of common sense)

**Comment by xF4m3** [comment]
Okay downgrading didnt work, and some recipes are displayed and some are not (I can't find an issue though) , they work fine on SP but not on MP
Also the recipes on MP are not only not displayed, but also not loaded

**Comment by xF4m3** [comment]
Okay thats not an issue on your part, someone edited one of my scripts and removed those items in there (they were only removed in one script, but in the other script I wrote they were removed and then added) 
I dont understand why it was working in sp but not on the server (maybe the server loads scripts diffrently? not sure) It is fixed for now atleast
