### ISSUE TITLE
Suspected bug with IguanaTweaksTinkersConstruct!

### ISSUE THREAD

**Issue by Zaphinine** [stanhebben/MineTweaker3#138]
<strong>Description</strong>
When installing IguanaTweaksTinkersConstruct with MineTweaker, the /help or /? page that contains a command from one of them will cause the game to crash when requested.

<strong>The mods that are installed are:</strong>
Mantle 0.3.2
Tinkers' Construct 1.2.8a
IguanaTweaksTinkersConstruct 2.0.7
MineTweaker 3.0.9C

<strong>How to reproduce:</strong>
1) Install the previously listed mods on Forge 10.13.2.1230
2) Load into a world
3) Do the /help or /? command. Cycle through the pages until you reach the page the commands for one of the two mods should be on. The game will crash.

<strong>Crash Log:</strong>
<hr />
<strong>Pastebin:</strong> http://pastebin.com/FmEpmPvw

<strong>Code:</strong>
B#234]  java.lang.NullPointerException
[B#234]  	at java.util.regex.Matcher.getTextLength(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at java.util.regex.Matcher.reset(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at java.util.regex.Matcher.<init>(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at java.util.regex.Pattern.matcher(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150269_b(SourceFile:61) ~[fr.class:?]
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150270_g(SourceFile:48) ~[fr.class:?]
[B#234]  	at net.minecraft.util.ChatComponentTranslation.iterator(SourceFile:147) ~[fr.class:?]
[B#234]  	at com.google.common.collect.Lists.newArrayList(Lists.java:129) ~[guava-16.0.jar:?]
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146237_a(GuiNewChat.java:168) ~[bcc.class:?]
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146234_a(GuiNewChat.java:148) ~[bcc.class:?]
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146227_a(GuiNewChat.java:143) ~[bcc.class:?]
[B#234]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:695) ~[bjb.class:?]
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:38) ~[gj.class:?]
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9) ~[gj.class:?]
[B#234]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[B#234]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
[B#234]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591) ~[bao.class:?]
[B#234]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
[B#234]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#234]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
[B#234]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#234]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#234]  [03:28:39] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#234]  // Oops.
[B#234]  
[B#234]  Time: 1/19/15 3:28 AM
[B#234]  Description: Unexpected error
[B#234]  
[B#234]  java.lang.NullPointerException: Unexpected error
[B#234]  	at java.util.regex.Matcher.getTextLength(Unknown Source)
[B#234]  	at java.util.regex.Matcher.reset(Unknown Source)
[B#234]  	at java.util.regex.Matcher.<init>(Unknown Source)
[B#234]  	at java.util.regex.Pattern.matcher(Unknown Source)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150269_b(SourceFile:61)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150270_g(SourceFile:48)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.iterator(SourceFile:147)
[B#234]  	at com.google.common.collect.Lists.newArrayList(Lists.java:129)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146237_a(GuiNewChat.java:168)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146234_a(GuiNewChat.java:148)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146227_a(GuiNewChat.java:143)
[B#234]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:695)
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:38)
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9)
[B#234]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[B#234]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[B#234]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
[B#234]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
[B#234]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[B#234]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#234]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#234]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#234]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#234]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#234]  
[B#234]  
[B#234]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#234]  ---------------------------------------------------------------------------------------
[B#234]  
[B#234]  -- Head --
[B#234]  Stacktrace:
[B#234]  	at java.util.regex.Matcher.getTextLength(Unknown Source)
[B#234]  	at java.util.regex.Matcher.reset(Unknown Source)
[B#234]  	at java.util.regex.Matcher.<init>(Unknown Source)
[B#234]  	at java.util.regex.Pattern.matcher(Unknown Source)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150269_b(SourceFile:61)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.func_150270_g(SourceFile:48)
[B#234]  	at net.minecraft.util.ChatComponentTranslation.iterator(SourceFile:147)
[B#234]  	at com.google.common.collect.Lists.newArrayList(Lists.java:129)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146237_a(GuiNewChat.java:168)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146234_a(GuiNewChat.java:148)
[B#234]  	at net.minecraft.client.gui.GuiNewChat.func_146227_a(GuiNewChat.java:143)
[B#234]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:695)
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:38)
[B#234]  	at net.minecraft.network.play.server.S02PacketChat.func_148833_a(SourceFile:9)
[B#234]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[B#234]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[B#234]  
[B#234]  -- Affected level --
[B#234]  Details:
[B#234]  	Level name: MpServer
[B#234]  	All players: 1 total; [EntityClientPlayerMP['Zaphinine'/2, l='MpServer', x=-1108.50, y=5.62, z=-1104.50]]
[B#234]  	Chunk stats: MultiplayerChunkCache: 599, 599
[B#234]  	Level seed: 0
[B#234]  	Level generator: ID 01 - flat, ver 0. Features enabled: false
[B#234]  	Level generator options: 
[B#234]  	Level spawn location: World: (-1117,4,-1101), Chunk: (at 3,0,3 in -70,-69; contains blocks -1120,0,-1104 to -1105,255,-1089), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
[B#234]  	Level time: 648 game time, 648 day time
[B#234]  	Level dimension: 0
[B#234]  	Level storage version: 0x00000 - Unknown?
[B#234]  	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[B#234]  	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
[B#234]  	Forced entities: 62 total; [EntitySheep['Sheep'/68769, l='MpServer', x=-1187.50, y=4.00, z=-1106.50], EntityCow['Cow'/68771, l='MpServer', x=-1053.50, y=4.00, z=-1132.50], EntityCow['Cow'/68773, l='MpServer', x=-1057.94, y=4.00, z=-1130.06], EntityCow['Cow'/68772, l='MpServer', x=-1056.50, y=4.00, z=-1131.50], EntityChicken['Chicken'/68775, l='MpServer', x=-1059.41, y=4.00, z=-1134.56], EntityCow['Cow'/68774, l='MpServer', x=-1055.50, y=4.00, z=-1127.50], EntityChicken['Chicken'/68777, l='MpServer', x=-1055.50, y=4.00, z=-1139.50], EntityChicken['Chicken'/68776, l='MpServer', x=-1057.47, y=4.00, z=-1143.47], EntityPig['Pig'/68779, l='MpServer', x=-1046.16, y=4.00, z=-1137.28], EntityChicken['Chicken'/68778, l='MpServer', x=-1068.38, y=4.00, z=-1144.47], EntityPig['Pig'/68781, l='MpServer', x=-1055.59, y=4.00, z=-1136.03], EntityPig['Pig'/68780, l='MpServer', x=-1057.25, y=4.00, z=-1134.75], EntitySheep['Sheep'/68783, l='MpServer', x=-1032.03, y=4.00, z=-1076.13], EntityPig['Pig'/68782, l='MpServer', x=-1059.50, y=4.00, z=-1138.50], EntitySheep['Sheep'/68785, l='MpServer', x=-1033.94, y=4.00, z=-1081.06], EntitySheep['Sheep'/68784, l='MpServer', x=-1032.66, y=4.00, z=-1077.84], EntityChicken['Chicken'/68787, l='MpServer', x=-1034.66, y=4.00, z=-1075.66], EntityChicken['Chicken'/68789, l='MpServer', x=-1031.50, y=4.00, z=-1073.50], EntityChicken['Chicken'/68788, l='MpServer', x=-1033.50, y=4.00, z=-1071.50], EntityHorse['Horse'/68663, l='MpServer', x=-1089.50, y=4.00, z=-1052.50], EntityHorse['Horse'/68665, l='MpServer', x=-1089.50, y=4.00, z=-1050.50], EntityChicken['Chicken'/68667, l='MpServer', x=-1092.50, y=4.00, z=-1051.50], EntityHorse['Horse'/68666, l='MpServer', x=-1085.50, y=4.00, z=-1046.50], EntityHorse['Horse'/68794, l='MpServer', x=-1033.38, y=4.00, z=-1074.38], EntityChicken['Chicken'/68669, l='MpServer', x=-1090.50, y=4.00, z=-1048.50], EntityChicken['Chicken'/68668, l='MpServer', x=-1092.50, y=4.00, z=-1050.50], EntityChicken['Chicken'/68671, l='MpServer', x=-1092.50, y=4.00, z=-1049.50], EntityChicken['Chicken'/68670, l='MpServer', x=-1093.50, y=4.00, z=-1050.50], EntityChicken['Chicken'/68673, l='MpServer', x=-1100.31, y=4.00, z=-1056.31], EntityChicken['Chicken'/68672, l='MpServer', x=-1100.91, y=4.00, z=-1056.88], EntityChicken['Chicken'/68674, l='MpServer', x=-1095.53, y=4.00, z=-1037.56], EntityPig['Pig'/68687, l='MpServer', x=-1163.91, y=4.00, z=-1072.50], EntityPig['Pig'/68689, l='MpServer', x=-1163.50, y=4.00, z=-1075.22], EntityPig['Pig'/68688, l='MpServer', x=-1165.66, y=4.00, z=-1071.06], EntityHorse['Horse'/68691, l='MpServer', x=-1172.93, y=4.00, z=-1070.88], EntityPig['Pig'/68690, l='MpServer', x=-1168.50, y=4.00, z=-1078.50], EntityPig['Pig'/68695, l='MpServer', x=-1164.22, y=4.00, z=-1076.47], EntityHorse['Horse'/68694, l='MpServer', x=-1162.50, y=4.00, z=-1072.50], EntityPig['Pig'/68696, l='MpServer', x=-1164.34, y=4.00, z=-1073.78], EntityPig['Pig'/68698, l='MpServer', x=-1170.84, y=4.00, z=-1064.88], EntityHorse['Horse'/68701, l='MpServer', x=-1030.50, y=4.00, z=-1063.50], EntityHorse['Horse'/68700, l='MpServer', x=-1033.50, y=4.00, z=-1065.50], EntityChicken['Chicken'/68707, l='MpServer', x=-1030.50, y=4.00, z=-1067.50], EntityChicken['Chicken'/68709, l='MpServer', x=-1030.50, y=4.00, z=-1068.50], EntityChicken['Chicken'/68708, l='MpServer', x=-1040.44, y=4.00, z=-1067.53], EntityChicken['Chicken'/68711, l='MpServer', x=-1151.50, y=4.00, z=-1120.50], EntityChicken['Chicken'/68713, l='MpServer', x=-1155.41, y=4.00, z=-1114.41], EntityClientPlayerMP['Zaphinine'/2, l='MpServer', x=-1108.50, y=5.62, z=-1104.50], EntityChicken['Chicken'/68712, l='MpServer', x=-1153.31, y=4.00, z=-1119.56], EntitySheep['Sheep'/68715, l='MpServer', x=-1150.06, y=4.00, z=-1114.06], EntityChicken['Chicken'/68714, l='MpServer', x=-1152.31, y=4.00, z=-1118.69], EntitySheep['Sheep'/68717, l='MpServer', x=-1152.50, y=4.00, z=-1126.22], EntitySheep['Sheep'/68716, l='MpServer', x=-1153.22, y=4.00, z=-1122.50], EntitySheep['Sheep'/68719, l='MpServer', x=-1156.34, y=4.00, z=-1115.28], EntitySheep['Sheep'/68718, l='MpServer', x=-1152.50, y=4.00, z=-1127.78], EntitySheep['Sheep'/68721, l='MpServer', x=-1157.78, y=4.00, z=-1121.22], EntitySheep['Sheep'/68720, l='MpServer', x=-1154.56, y=4.00, z=-1122.66], EntityPig['Pig'/68723, l='MpServer', x=-1186.50, y=4.00, z=-1135.50], EntitySheep['Sheep'/68722, l='MpServer', x=-1160.50, y=4.00, z=-1122.50], EntityPig['Pig'/68725, l='MpServer', x=-1186.50, y=4.00, z=-1133.50], EntityPig['Pig'/68724, l='MpServer', x=-1184.50, y=4.00, z=-1136.50], EntityPig['Pig'/68726, l='MpServer', x=-1183.50, y=4.00, z=-1132.50]]
[B#234]  	Retry entities: 0 total; []
[B#234]  	Server brand: fml,forge
[B#234]  	Server type: Integrated singleplayer server
[B#234]  Stacktrace:
[B#234]  	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
[B#234]  	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
[B#234]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
[B#234]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#234]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#234]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#234]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#234]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#234]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#234]  
[B#234]  -- System Details --
[B#234]  Details:
[B#234]  	Minecraft Version: 1.7.10
[B#234]  	Operating System: Windows 8.1 (amd64) version 6.3
[B#234]  	Java Version: 1.8.0_25, Oracle Corporation
[B#234]  	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[B#234]  	Memory: 788331488 bytes (751 MB) / 963641344 bytes (919 MB) up to 3817865216 bytes (3641 MB)
[B#234]  	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m
[B#234]  	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[B#234]  	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[B#234]  	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 7 mods loaded, 7 mods active
[B#234]  	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	FML{7.10.85.1230} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	Forge{10.13.2.1230} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle_0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker_3.0.9c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct_1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	IguanaTweaksTConstruct{1.7.10-2.0.7} [Iguana Tinker Tweaks] (IguanaTiCTweaks_2.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[B#234]  	Mantle Environment: Environment healthy.
[B#234]  	TConstruct Environment: Environment healthy.
[B#234]  	Launched Version: 1.7.10-Forge10.13.2.1230
[B#234]  	LWJGL: 2.9.1
[B#234]  	OpenGL: AMD Radeon HD 7800 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
[B#234]  	GL Caps: Using GL 1.3 multitexturing.
[B#234]  Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
[B#234]  Anisotropic filtering is supported and maximum anisotropy is 16.
[B#234]  Shaders are available because OpenGL 2.1 is supported.

**Comment by vanceza** [comment]
If you remove MineTweaker do you still have the problem?

**Comment by vanceza** [comment]
I hope you already checked, just to confirm: When you uninstall minetweaker, do you still see this problem?

**Comment by jaredlll08** [comment]
This is a TiC / ITTC issue, I just tested latest versions of it WITHOUT MT and it crashed.
