### ISSUE TITLE
vanilla.loot.removeChestLoot crash on chunk gen

### ISSUE THREAD

**Issue by joesephkatana** [stanhebben/MineTweaker3#139]
I removed all chest loot items then added a few more for each chest type. Like this, for every item given by /mt loot:
    
    vanilla.loot.removeChestLoot("dungeonChest", <minecraft:name_tag>);

I made sure to change the first argument to match the the respective category given by /mt loot.
 It crashes on world generation. So I removed all entries except those in strongholds, then used enderpearls to find the stronghold. It crashes everytime before I reach the stronghold. So I conclude that its crashing anytime it generates a chunk containing a chest that's been emptied (too much? or maybe its certain items that cause crashes when removed?) the script doesn't crash anything if I reload it with these changes and don't move around to cause new chunks to generate.

**Comment by Kalbintion** [comment]
I have ran into this issue myself, but the culprit was due to Tinkers' Construct arrows being added to the dispenser loot list, which isn't a typical item that can be generated since it has a lot of information stored in NBT tags that weren't being supplied. Removing this offending (complex) item from the list fixed the crash in my particular issue.

**Comment by jaredlll08** [comment]
this is weird can I please have the full script

**Comment by joesephkatana** [comment]
Sorry, that was far too long ago for me to still have the scripts.

**Comment by jaredlll08** [comment]
Ah ok :/

**Comment by jaredlll08** [comment]
This issue has no information (partially my fault for not getting to it sooner), and it hasn't been reported again, so I can only assume it is an edge case, or not our mod causing the crash

**Comment by Kalbintion** [comment]
I actually forgot about this issue completely until I just saw the email sent to me today about this ticket being responded to and closed. I'm fairly sure I still have my script if you're still interested in looking into this on my end even though removing the one offending item, as previously mentioned, caused it to work without having discovered other issues. Would you prefer to see the script with the broken item included in it? I keep extensive version history of the modpack so it shouldnt be a problem to find a version i had pushed it out with the issue involved.
