### ISSUE TITLE
Planter

### ISSUE THREAD

**Issue by skaviouz** [stanhebben/MineTweaker3#140]
#### Status
~~PR #145 Completed~~
waiting next version
test
close issue

#### I'm trying to add some seeds to the planter
```java
var SeedA = <minecraft:gold_ingot:0> as IIngredient;
var BlockAIS = <minecraft:gold_block> as IItemStack;
var BlockA = BlockAIS.asBlock() as IBlock;
Planter.addPlantable(SeedA, BlockA);
```

#### However I am running into the errors
BlockA
![http://i.imgur.com/vXgB6t9.png](http://i.imgur.com/vXgB6t9.png)
Planter.addPlantable
![http://i.imgur.com/Q30FOi5.png](http://i.imgur.com/Q30FOi5.png)

#### I see the two methods 
```java
addPlantable(IItemStack seed, @Optional IBlockPattern canPlantOn)
addPlantable(IIngredient seed, IBlock block, @Optional IBlockPattern canPlantOn)
```

#### And this is the link for IItemStack
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/api/item/IItemStack.java
which lists asBlock as a valid function for IItemStack?

#### What I want to do
I want to exec addPlantable(IIngredient seed, IBlock block) leaving the optional empty, so what am I doing wrong?

#### Constants
Forge 1.7.10-1277
MFR 1.7.10-2.8.0RC6-6
MT3 1.7.10-3.0.9C

**Comment by stanhebben** [comment]
The asBlock shouldn't be needed. It's registered as a special function that automatically converts the value to the IBlock type. If you want to make the conversion explicitly, you can add "as minetweaker.block.IBlock".

**Comment by skaviouz** [comment]
#### Example 1
var BlockAIS = minecraft:gold_block as IItemStack;
var BlockA = BlockAA as minetweaker.block.IBlock;

#### Example 2
var BlockA = <minecraft:gold_block> as minetweaker.block.IBlock;

Neither of the above examples work. Same error.
http://i.imgur.com/QD9dtaS.png

**Comment by UndeadZeratul** [comment]
You shouldn't need to cast to an IBlock to begin with.  I've used just \<minecraft:gold_block\> or similar without having to cast it and it works just fine.

**Comment by skaviouz** [comment]
Shouldn't need, yet I have not been able to get this to work.
```
import mods.mfr.Planter;
addPlantable(<minecraft:gold_ingot:0>, <minecraft:gold_block:0>);
```

**Comment by UndeadZeratul** [comment]
I think you forgot to add the "Planter" at the beginning of the method:

```
import mods.mfr.Planter;
Planter.addPlantable(<minecraft:gold_ingot>, <minecraft:gold_block>);
```

Should work.

Does the addPlantable method take ore dictionary entries?

```
import mods.mfr.Planter;
Planter.addPlantable(<ore:ingotGold>, <ore:blockGold>);
```

might be better if other mods add their own versions of these for whatever reason.

**Comment by skaviouz** [comment]
Typo, I have planter, and the three snipets you made didn't work.

I'm assuming the latter, I'm gona download forge and see if editing https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Mod-MFR/src/main/java/minetweaker/mods/mfr/machines/Planter.java line 57 does anything different if I change it to
```java
public static void addPlantable(IItemStack seed, IItemStack blockI, @Optional IBlockPattern canPlantOn) {
	IBlock block = blockI.asBlock();
		if (block == null) {
			MineTweakerAPI.logError("The given seed has no block equivalant");
		}
	addPlantable(seed, block, canPlantOn);
}
@ZenMethod
public static void addPlantable(IIngredient seed, IBlock block, @Optional IBlockPattern canPlantOn) {
```

let's see how successful I can be (I am new to my OS) and make a pull request

**Comment by UndeadZeratul** [comment]
Yeah, if the methods I gave didn't work, then I have to assume it's because they're looking for a block explicitly, which the parameters you define are going to be itemStacks.  If you get it to accept two itemStacks, maybe do a PR for the fix? :)

**Comment by jaredlll08** [comment]
PR was merged.
