### ISSUE TITLE
[Mod Question] MFR Support?

### ISSUE THREAD

**Issue by Lanse505** [stanhebben/MineTweaker3#142]
Hello!

I've Noticed that under MFR support that it says abunch of "Unfinished" and has been for a while I think(?).

Is it done and the thread is not update? or is it just something that has been placed on the back burner?

**Comment by Yulife** [comment]
@stanhebben if the code is done, I could document it.

**Comment by jaredlll08** [comment]
Code is done and documented, http://minetweaker3.powerofbytes.com/wiki/Mods:MFR_Support
