### ISSUE TITLE
Crash server with MineTweaker3-Dev-Full-1.7.10-3.0.9C

### ISSUE THREAD

**Issue by Tsyklop** [stanhebben/MineTweaker3#143]
Logs: http://pastebin.com/TR23KMfq

**Comment by jaredlll08** [comment]
A few things... don't use dev unless you are actually making an addon. 
What forge version?
Please update your forge version to the latest.
also I know this has been fixed, considering I have used Minetweaker on a server

**Comment by Tsyklop** [comment]
@jaredlll08 help here https://github.com/stanhebben/MineTweaker3/issues/214

**Comment by jaredlll08** [comment]
A please would be nice... also I am currently dealing with vanilla Minetweaker issues, once I have cleared those out, I will look into mod issues :)

**Comment by jaredlll08** [comment]
Please give me some time.

**Comment by Tsyklop** [comment]
@jaredlll08 Okay)
