### ISSUE TITLE
Crash with Buildcraft's Advanced Crafting Table

### ISSUE THREAD

**Issue by ultrasn0w** [stanhebben/MineTweaker3#144]
Whenever I lay a Recipe made with Minetweaker into an Advanced Crafting Table, my game crashes and the log spits out this:

http://pastebin.com/B0WCC7zk

I'm not sure if this is a crash related to Minetweaker or BC, so I opened the Issue on both Gits.
(BC Issue: https://github.com/BuildCraft/BuildCraft/issues/2429)

Greetings
ultrasn0w

Edit: Auto Workbenches are working fine.

**Comment by jaredlll08** [comment]
This is now fixed locally (will upload to git a bit later)
