### ISSUE TITLE
MineTweaker preventing ComputerCraft Computers from booting

### ISSUE THREAD

**Issue by Xukkorz** [stanhebben/MineTweaker3#148]
Upon updating to ComputerCraft Beta computers no longer start.

Mods Used:
Forge 10.13.2.1300
MineTweaker 3.0.9c
ComputerCraft 1.66pr3

DESCRIPTION:
Upon updating to Computercraft Beta computers no longer start.
EXPECTED RESULT:
Computers should boot when right clicking
REPRODUCTION STEPS:
Place the computer and right click, no errors occur. Included is http://paste.ee/p/EpW0w of Minecraft log.
NOTES: 
I am not sure if this is MineTweaker3 or if it is ComputerCraft. I am reporting on both sides. Note this appears to be a problem between these specific versions of the mods as if I remove MineTweaker ComputerCraft works and if I install the previous version of ComputerCraft. I tend to believe this is because ComputerCraft is now able to send Minecraft Commands directly rather then interfacing with a Command Block.

**Comment by stanhebben** [comment]
Can you provide a link to the corresponding posting on ComputerCraft? I have no clue what could be causing it, and too busy to spend much time on it, but I can keep an eye on the issue.

**Comment by Xukkorz** [comment]
Sure, heres the posing on the CC forums.  Honestly with the other mod being a beta it may be on that side but noticing it and it being weird I figured I should point it out.

http://www.computercraft.info/forums2/index.php?/topic/16882-computercraft-16-beta-bug-reports/page__pid__205183__st__40#entry205183

**Comment by dan200** [comment]
Hiya. I've managed to work around this error in my latest computercraft update, but this bug report shows the root cause: https://github.com/stanhebben/MineTweaker3/issues/154

**Comment by jaredlll08** [comment]
So can this be closed then?

**Comment by Xukkorz** [comment]
Thats fine
