### ISSUE TITLE
mt advanced options in gregtech support

### ISSUE THREAD

**Issue by Usernm0** [stanhebben/MineTweaker3#149]
I disable recipe through gregtech config and try to use this one:

val moldPlate = <gregtech:gt.metaitem.01:32301>;
val ingotRedAlloy = <gregtech:gt.metaitem.01:11308>;
val plateRedAlloy = <gregtech:gt.metaitem.01:17308>;
AlloySmelter.addRecipe(plateRedAlloy * 2, ingotRedAlloy * 3, moldPlate, 1200, 2);

It works but consume mold, i try use .reuse method, but it not works inside machine recipe:
AlloySmelter.addRecipe(plateRedAlloy * 2, ingotRedAlloy * 3, moldPlate.reuse(), 1200, 2);

Any chance to fix it? Reuse can be added globally or just like flag to one of the input parameter.

**Comment by Dream-Master** [comment]
Set it to 0 and it work.

AlloySmelter.addRecipe(plateRedAlloy * 2, ingotRedAlloy * 3, moldPlate * 0, 1200, 2);

**Comment by Dream-Master** [comment]
Reload the Game then it will displayed : "item not consumed in this Process" or something like that.

**Comment by Usernm0** [comment]
Works well, thank you.
