### ISSUE TITLE
Problems with NEI api

### ISSUE THREAD

**Issue by Usernm0** [stanhebben/MineTweaker3#152]
import mods.nei.NEI;
NEI.hide(<IC2:blockMachine:13>); // Induction smelter
NEI.hide(<IC2:blockMachine:14>); // Mass fabricator
NEI.hide(<IC2:blockMachine2:3>); // Thermal centrifuge
NEI.hide(<IC2:blockMachine2:4>); // Metal former
NEI.hide(<IC2:blockMachine2:5>); // Ore washing machine
NEI.hide(<IC2:blockMachine3:1>); // Blast furnace
NEI.hide(<IC2:blockMachine3:2>); // Block cutting machine

This code works fine when loaded first time. If i use /mt reload ingame, this code hide all blocks inside <IC2:blockMachine2> not only specific. 

I same script i use this code:
NEI.overrideName(<IC2:itemIngot:3>, "Steel ingot");

It works, but every time i use /mt reload ingame script stuck more and more times.

**Comment by Voidi** [comment]
see https://github.com/stanhebben/MineTweaker3/issues/121

**Comment by jaredlll08** [comment]
https://github.com/stanhebben/MineTweaker3/issues/205#issuecomment-137717090
