### ISSUE TITLE
[Bug] Can't remove recipe with ' in their name

### ISSUE THREAD

**Issue by Katrix-** [stanhebben/MineTweaker3#153]
Can't remove a recipe with a ' in their name. An item called "Sorcerer's Sutra Scroll" will not work for example.

**Comment by RAnders00** [comment]
Have you tried to escape the `'` with a `\'`? I am really not into MineTweaker but it's the usual way to escape such characters.

**Comment by Katrix-** [comment]
Tried it. \ Is not a valid character.

**Comment by jaredlll08** [comment]
can we get the script please?

**Comment by jaredlll08** [comment]
Let me just say, whoever put a ' in their item unlocalized name, should not be modding...
anyway, all items now get stripped of '
