### ISSUE TITLE
Multiple references to net.minecraft.server.dedicated.DedicatedServer in classes not marked @SideOnly(Side.SERVER), causes crashes

### ISSUE THREAD

**Issue by dan200** [stanhebben/MineTweaker3#154]
In ComputerCraft, I attempt to iterate over all the registered Minecraft commands to check if they can be executed by a Command Computer. When I attempt to call canCommandSenderUseCommand() on the commands added by MineTweaker, this causes a crash on a singleplayer client, as java attempts to load the command class, which in turn tries to load DedicatedServer, which does not exist on the client. If this class must reference DedicatedServer, use reflection to do so, and safely handle it's non-existance.

**Comment by jaredlll08** [comment]
Fixed this in Crafttweaker dev
