### ISSUE TITLE
Crash with latest Buildcraft version 6.4.1

### ISSUE THREAD

**Issue by Staegrin** [stanhebben/MineTweaker3#157]
So I wanted to update my minetweaker version to MineTweaker3-1.7.10-3.0.9 from version MineTweaker3-1.7.10-3.0.8B

When I try to run minecraft the resulting crash happens.

Crash log:
http://pastebin.com/9qqn9kRx

With Minetweaker being named along with Caused by: java.lang.NoClassDefFoundError: buildcraft/api/fuels/IronEngineCoolant$Coolant

Everything runs fine with the older version of Minetweaker.

**Comment by Staegrin** [comment]
Still a problem with the new release 6.4.2 of buildcraft

**Comment by Kenshij** [comment]
stanhebben.zenscript.type.ZenTypeNative.complete cause it i think buildcraft has update it api

**Comment by Kenshij** [comment]
with MineTweaker3-1.7.10-3.0.9C.jar no errors
with MineTweaker3-1.7.10-3.0.9.jar error

**Comment by RAnders00** [comment]
Why did you remove the crash log?

**Comment by RAnders00** [comment]
This is closed, get the latest 3.0.9C from the website.

**Comment by Staegrin** [comment]
Indeed version 3.0.9C fixes the issue.
