### ISSUE TITLE
[Suggestion] .getNBT function // .modifyTag function

### ISSUE THREAD

**Issue by Gemaltrix** [stanhebben/MineTweaker3#158]
Hello Developer,

I think it would be nice to have a function to get the NBT of a crafting input and store it in a variable which is defined earlier.
Because I have the problem when I change Thermal Expansion 4 recipes, I can only put a default tag on the output. This erases all NBT from the input and all stored things in them.

For example:

var something = [ ] as IData;

recipes.addShaped(example.withTag(something),
 [[null, null, null],
  [null, example.getNBT(something), null],
  [null, null, null]]);

And the second suggestion that goes hand in hand with the first one is a function to modify a NBT-tag.
Same as before TE4 stores its tier system in a level-tag.

For example:

var something = [ ] as IData;

recipes.addShaped(example.withTag(something).modifyTag(target tag, repace tag),
 [[null, null, null],
  [null, example.getNBT(something), null],
  [null, null, null]]);

Regards,
Gemaltrix

**Comment by UndeadZeratul** [comment]
I don't know if that will solve the problem you're looking for.  I'm currently running into this issue as well, and I'm going to look into [using functions for crafting recipe results](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes#Function_recipes) to grab the input machine's augments and whatnot and put them onto the output machine.

**Comment by Gemaltrix** [comment]
Oh thanks, I think I skipped this part.
But I think  nonetheless we have to wait because it looks like it's not in jet.

Well atm I configured it so that there is no upgrading recipe.
