### ISSUE TITLE
 '/minetweaker recipes' bug on Material Energy^4

### ISSUE THREAD

**Issue by miscillo** [stanhebben/MineTweaker3#160]
Hi. I tried to execute '/minetweaker recipes' on Material Energy^4 but it didn't work. 

The error message was:
Couldn't process command: 'minetweaker recipes'

I also made a pastebin with the FTB log in which there was the error. It's here: http://pastebin.com/63v3Wgsm

Also '/minetweaker recipes hand' didn't work, with the same error but reading the log it seems to be a different problem.
Again, here there is the pastebin with the log: http://pastebin.com/V3CCPcpA

**Comment by jaredlll08** [comment]
This has been fixed
