### ISSUE TITLE
Empty Oredict Recipe

### ISSUE THREAD

**Issue by Kalbintion** [stanhebben/MineTweaker3#161]
As I was attempting to add a custom recipe for OpenBlocks Tasty Clay, I accidentally typoed an ore dict name. When the script was reloaded, the script didn't fail but the recipe failed to show up at all. After spending some time on it is when I discovered the issue with the ore dictionary name. I know that the dictionary will return an empty set if it doesn't exist, but didn't expect it to "silently fail" to add the recipe due to an empty ore dict value. Is this intended behaviour that a recipe can be added with an empty ore dict? If so, can an option be provided to declare that empty ore dicts being referenced for recipes, or other purposes (outside of declaration) be mentioned in chat/console to aid in fixing user errors.

**Comment by jaredlll08** [comment]
We can't really do this(imo, please correct me if I am wrong) :/ since what happens if you do something like this

-add recipe that uses '<ore:irons>' that is currently empty, but then, the next line, you add something to '<ore:irons>' or in another script you add it, since there is no load order for scripts, it will sometimes work, and sometimes not

**Comment by Kalbintion** [comment]
How about a compromise on this then, since I do not disagree with you in that being a potential thing that may happen. A developer setting of sorts that will give more verbose information in errors, potential issues, etc, intended for modpack authors to use to aid them in problem solving. Similar to HQM's edit mode being intended to only be on for the pack author to create and modify quests. The setting could be set via the command-line on game startup since there is no config file available that would give this type of additional warnings that normally would not be seen. I could expand more into what additional information could be provided through this setting if so desired.
