### ISSUE TITLE
Can't recognise buildcraft quarry!

### ISSUE THREAD

**Issue by dylanpiera** [stanhebben/MineTweaker3#162]
When using /mt hand i get this code for a bc quary:
BuildCraft:Factory:machineBlock

But this ain't working:
val quary = <<BuildCraft:Factory:machineBlock>>;

Could not resolve BuildCraft : Factory : machineBlock

**Comment by Voidi** [comment]
The ':' between BuildCraft and Factory is in Fact the Minecraft font-specific representation of '|'
The correct internal Name is `<BuildCraft|Factory:machineBlock>`
 For Future issues : use the minetweaker names command and let the names print to minetweaker.log.

**Comment by dylanpiera** [comment]
Thanks
