### ISSUE TITLE
Minetweaker cannot resolve Logistics Pipe blocks

### ISSUE THREAD

**Issue by simlhawk** [stanhebben/MineTweaker3#164]
Unfortunately, I can't seem to get MineTweaker to resolve a logistics pipes block.

LogisticsPipes:logisticsSolidBlock:1

I've even done an NEI dump, copied and pasted to ensure I had the right variable.

This is my script.

http://pastebin.com/iJ41bBcv

**Comment by Dream-Master** [comment]
Yes i have the same problem i think. It renames the items there are space before and after the ":".

**Comment by simlhawk** [comment]
No I haven't yet. But if that is what it does, I don't mind just adding the spaces. The weird thing is, that's not what shows up when I do an NEI dump. You think it would show up.

**Comment by jaredlll08** [comment]
when we print the actual item, we put spaces between the ":" it makes it easier to read, also reading through the issue on the LP tracker, they seem to have worked it out.
