### ISSUE TITLE
Trouble specifying what soil a sapling can be planted in using MFR support

### ISSUE THREAD

**Issue by BBoldt** [stanhebben/MineTweaker3#165]
So, I have a sapling that can only be planted in a specific soil, which pops off if planted on regular dirt.

```
import mods.mfr.Planter;
Planter.addPlantable(<aether:goldenOakSapling>, <aether:aetherDirt:1>);
```

From what I understand, that should be working, but when I reload the script, it results in this:
```
ERROR: Aether.zs:2 > 2 methods available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IItemStack)
```

I can't tell if I'm trying to add it incorrectly or if it's an actual bug in minetweaker due to there not being documentation on the subject.

From what I can understand by looking at this, it should be working correctly:
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Mod-MFR/src/main/java/minetweaker/mods/mfr/machines/Planter.java#L48

**Comment by jaredlll08** [comment]
This is user error, I suggest trying
<aether:goldenOakSapling>, <block:aether:aetherDirt:1>
