### ISSUE TITLE
Adding furnace recipe doesn't work

### ISSUE THREAD

**Issue by Timeslice42** [stanhebben/MineTweaker3#167]
Adding the following furnace recipe doesn't work; removing recipes works fine.

```
# Remove grout -> seared brick
furnace.remove(<TConstruct:materials:2>);
# Add grout -> nether seared brick
furnace.addRecipe(<TConstruct:CraftedSoil:1>, <TConstruct:materials:37>);
```

**Comment by Yulife** [comment]
Like I said, the error log is needed.

**Comment by Timeslice42** [comment]
And like I said, there was no error.
Here is the log file: https://www.dropbox.com/s/wc2jyf1wvx81x5w/fml-client-latest.zip?dl=0

**Comment by Voidi** [comment]
We need the minetweaker.log

**Comment by Timeslice42** [comment]
It looks just like you'd think it should: http://paste.ee/p/TdlQL

**Comment by Timeslice42** [comment]
Has anyone looked at this yet?

**Comment by jaredlll08** [comment]
I remember testing this. I think it is a weird Tcon bug, since I am actually using furnace recipes to test right now and they are working fine
