### ISSUE TITLE
Can't unhide from NEI

### ISSUE THREAD

**Issue by PitchBright** [stanhebben/MineTweaker3#168]
When using NEI.hide to hide a block/item… it seems the mod makes a change to the NEI.data file in the client "saves/NEI" folder. When the NEI.hide script is removed (to allow the block/item to be shown in NEI again)… the client's NEI.data file doesn't get modified to allow the block/item to be seen again.

**Comment by stanhebben** [comment]
Thanks for reporting, that might explain some of the weird behavior when using NEI integration.

**Comment by PitchBright** [comment]
Hey Stan, do you know which file the "hide" information gets written to, on the server? In my initial report, I was able to unhide items by having the client blow away their NEI folder, in their saves folder. But the solution only seems to work once. The first time they connect to the server after deleting that folder… they can see the items again. When they relog, the item is no longer visible. That means there has to be a file on the server somewhere, that is feeding the client a list of what items should be hidden.

**Comment by jaredlll08** [comment]
NEI support is broken and cannot be fixed, this issue is resolved in 1.8.x using JEI
