### ISSUE TITLE
NEI.hide ignores metadata

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#170]
When I try to hide an item it hides all items with the same name tag.

For example if I try to hide Jabba bSpace barrel upgrade i type:
`NEI.hide(<JABBA:upgradeCore:1>)`
When I enter game, the bSpace barrel upgrade is hidden. But when I either rejoin the game, or reload the script it will remove all items with `<JABBA:upgradeCore>` no matter what meta number  the item has.

**Comment by PitchBright** [comment]
I'm experiencing this issue as well. It kinda renders NEI.hide useless because it's an all-or-nothin' thing.

**Comment by vanceza** [comment]
What version of minecraft are you on? Read the note at the bottom of this page: http://minetweaker3.powerofbytes.com/wiki/Mods:NEI_Support

**Comment by JasonMcRay** [comment]
I am 1.7.10

**Comment by PitchBright** [comment]
I'm also in 1.7.10

**Comment by jaredlll08** [comment]
NEI has issues with reload, nothing that we can do about it.
