### ISSUE TITLE
AE2 Flour doesn't exist as an item...

### ISSUE THREAD

**Issue by GamingMortal** [stanhebben/MineTweaker3#171]
I was trying to edit a recipe so that it would accept AE2 flour, however after using the "/minetweaker names" command to print the names of all items in the modpack I found that AE2 flour doesn't exist as an item. It's enabled in the game and can be created in survival so I have no idea why it not showing up? Here is the dump that was created I searched high and low for AE2 flour but to no avale: http://pastebin.com/3L3MxKQM . I create an issue with the AE2 guys but they directed me here (https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1247#issuecomment-91328709)

**Comment by Yulife** [comment]
Item dumps are kind of inefficient. Just use /mt hand when holding the flour in your hand to get its information.

**Comment by GamingMortal** [comment]
Thanks a bunch...

**Comment by Yulife** [comment]
You can close the issue.
