### ISSUE TITLE
Latest 3.0.9C missing on minecraft.curseforge.com

### ISSUE THREAD

**Issue by RAnders00** [stanhebben/MineTweaker3#172]
You only have that version on your website, would you mind uploading it to CurseForge as well? It's a pain to keep your mods updated if someone puts a download location up and then does not maintain it. I struggled with the BuildCraft crash for a while now and had to disable MineTweaker because of that, it would be nice to prevent outdated versions in the future by simply keeping everything up to date.

**Comment by jaredlll08** [comment]
It is on curse now.
