### ISSUE TITLE
Cannot use minetweaker commands while OP

### ISSUE THREAD

**Issue by Yascob99** [stanhebben/MineTweaker3#175]
Hello I'm running a Feed the Beast Infinity sever(1.3.4) and for some reason I can't use any minetweaker(version 3.0.9C) commands as an OP. My best guess as to why would be because we have Forge Essentials installed and permissions set up. If you have any idea or feedback on why it would be happening please do tell me.

**Comment by Yascob99** [comment]
Wait solved it it was caused by changing username. Please close the thread. Man I feel stupid for not trying that earlier.

**Comment by jaredlll08** [comment]
Just a heads up, you can close the issue yourself.
