### ISSUE TITLE
getting problems with MagicalCrops and Bloodmagic

### ISSUE THREAD

**Issue by DaBrainZ** [stanhebben/MineTweaker3#176]
i want to make the minicio seeds require an infusion of normal seeds
so for the .zs file i have:

//removed Recipies
recepies.remove(<magicalcrops:magicalcrops_SeedsMinicio>);
//Blood Magic
//Altar
mods.bloodmagic.Altar.addRecipe(<magicalcrops:magicalcrops_SeedsMinicio>, <minecraft:wheat_seeds>, 2, 200, 20, 20);

but when i try to reload the files i get:

ERROR: ?:2 > could not find recipies
ERROR: Error executing Minetweaker.zs:minetweaker/api/item/ItemStackAny

Thanks in advance

**Comment by jaredlll08** [comment]
well you mispelt recipes... that could be the problem
