### ISSUE TITLE
ModTweaker Thermal Expansion Pulverizer changes not working

### ISSUE THREAD

**Issue by chrisk123999** [stanhebben/MineTweaker3#177]
Using the latest versions of Thermal Expansion, Minetweaker, and ModTweaker; Making changes to pulverizers is silently failing.

Edit: Rolling it back one version fixes it.  ModTweaker 2-0.8.1.jar doesn't work, while ModTweaker 2-0.8.0.jar does.

**Comment by Yulife** [comment]
Why are you posting that in the Minetweaker repo?? Close this please and report it with details in the Modtweaker repo ~ - ~

**Comment by chrisk123999** [comment]
Couldn't find a mod tweaker github that's been updated in the past year.  I assumed they had the same dev's so I just put it here.
