### ISSUE TITLE
[Feature Request] Item Mirroring

### ISSUE THREAD

**Issue by SixOnTheBeach** [stanhebben/MineTweaker3#178]
I see that minetweaker has the ability to mirror recipes, and mirror ore dictionaries, but if an item is not in an ore dictionary, I see no way of mirroring it to another item. Would it be possible to change this? My pack has fish leather in it, and I see no easy way to make it interchangeable with leather.

**Comment by RisingDemon** [comment]
```
// Get an ore dictionary entry for leather
val leather = <ore:leather>;
// Ensure that regular leather is in the ore dictionary
leather.add(<minecraft:leather>);
// Add fish leather
leather.add(<yourMod:fishLeatherName>);
// Now add recipes using oredict leather
// You can add them while playing and use "/mt reload"
```

**Comment by SixOnTheBeach** [comment]
But you see, this doesn't work, RisingDemon. I did it, one would *think* it would work. However, this merely makes any future recipes I do work. All existing recipes do NOT use ore:leather, they call for regular ol MC leather, so it has no effect. Now, I *could* go through every single recipe and change it, but I'd really rather not...

**Comment by RisingDemon** [comment]
Yeah, the existing recipes are a problem...

**Comment by jaredlll08** [comment]
This won't be possible due to how mods add recipes, the best solution is the oredictionary and hope that the mod supports oredictionary recipes

**Comment by Blue64** [comment]
and lots of boring coding! lol
