### ISSUE TITLE
Minetweaker/Modtweaker crash with Thaumcraft

### ISSUE THREAD

**Issue by whitestarx0312** [stanhebben/MineTweaker3#179]
Upon entering a world, I get a fatal error. After looking at the logs something about Modtweaker/Minetweaker and Thaumcraft comes up.

Minetweaker: MineTweaker3-1.7.10-3.0.9C
Modtweaker: ModTweaker 2-0.8.0
Forge: forge-10.13.3.1387
Thaumcraft: Thaumcraft-1.7.10-4.2.3.5
Agrarian Skies 2: 1.0.39

Log: http://pastebin.com/VLiEHVpX
*The full log is too large for pastebin, let me know if you need it.
*I am using Optifine and Fastcraft.

EDIT: I can log in after restarting my client. It still crashes after I attempt to use the Guide API book, if this is their issue I will report it to them.

**Comment by stanhebben** [comment]
This is a modtweaker bug; better post it there instead.

**Comment by whitestarx0312** [comment]
Alright will do!
