### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by vanceza** [stanhebben/MineTweaker3#187]
You said to contact you if I want to contribute; here I am.

I don't think I'm interested in doing anything not already in your changelog, which is pretty damn ambitious; I'd just like to help progress down that. (Mob and block drops, fishing, etc--basically the standard vanilla parts not covered, are especially exciting)

I haven't much experience with minecraft modding, but I've written programming languages before.

**Comment by jaredlll08** [comment]
I don't think this is relevant anymore, if @stanhebben still wants help, then he can re open :)

**Comment by vanceza** [comment]
Sigh.

**Comment by Yulife** [comment]
Looking at the [Planned Features](http://minetweaker3.powerofbytes.com/wiki/Planned_Versions), there's still a ton of things left to do :)
