### ISSUE TITLE
Server Crash On World Creation

### ISSUE THREAD

**Issue by Pkr1345** [stanhebben/MineTweaker3#192]
http://pastebin.com/iamifpgw

Im usually good at figuring out mod/minetweaker errors but this new error report layout, I have no clue. Im using cauldron with forge 1448. let me know if you need a mod list.

**Comment by stanhebben** [comment]
This looks like an issue in another mod. There must be a coremod modifying the respective class and causing a failure doing so.

**Comment by Pkr1345** [comment]
After mod testing, it was Mobius Core that was doing the it. Everything works fine now.

**Comment by jburrows82** [comment]
Actually, it's kCauldron (3rd party Cauldron continuation) and it's incompatibility with MobiusCore that's causing it. kCauldron has a modified version of MobiusCore available for download that resolves the incompatibility.

**Comment by jaredlll08** [comment]
kCouldron issue.
