### ISSUE TITLE
ThaumCraft slash commands not found

### ISSUE THREAD

**Issue by CheshireKatt** [stanhebben/MineTweaker3#193]
It's possible the documentation is out of date on this, but I've found that the ThaumCraft slash commands don't seem to be available for me.  I'm using MineTweaker3 3.0.9C and ModTweaker2 0.8.0, and running Forge 10.13.3.1401 / MC 1.7.10.  My problem specifically is that:

/minetweaker aspects
/minetweaker research

both result in "No such minetweaker command available".

I'm able to manipulate ThaumCraft research via config:

mods.thaumcraft.Research.removeTab("AOBD");

does what's expected and removes the Another One Bites the Dust Thaumonomicon tab (though I do get a "WARNING: 1 modifications were stuck" message, which I'm imagining is probably because I haven't taken that research off of the tab yet, but I can at least verify that the tab *is* removed from the Thaumonomicon.

Any suggestions on what I could try, or more information you'd like on this?

**Comment by jaredlll08** [comment]
Did you use /mt reload? or did the modifications error appear first run?
Also the thaumcraft command missing was an issue with Modtweaker, iirc it has been resolved

**Comment by jaredlll08** [comment]
This is a modtweaker issue and has been fixed
