### ISSUE TITLE
Cant remove Inguana Saws and Project Red Saws with Minetweaker

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#194]
I try to remove the Saws because i want to change the Recipes and get the following Error.
Why it have a Space between the Double Point ?

````````````````````````````````````````````````````````````````````
ERROR: Iguana-Tweaks.zs:13: Could not resolve <IguanaTweaksTConstruct : sawArdite>
INFO: Removing 1 recipes
ERROR: Error executing Iguana-Tweaks.zs: null
java.lang.NullPointerException
	at minetweaker.mc1710.recipes.MCRecipeManager.remove(MCRecipeManager.java:94)
	at Iguana-Tweaks.__script__(Iguana-Tweaks.zs:13)
	at __ZenMain__.run(Iguana-Tweaks.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````````````````````````````````````````````````````````````````

https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/149

**Comment by jaredlll08** [comment]
Can I have the line of code that was used?

**Comment by jaredlll08** [comment]
This is because iguana tweaks does not adds saws... therefore there is no item, therefore it can not add a recipe...

**Comment by Voidi** [comment]
What do you mean with 'does not add saws'?

**Comment by jaredlll08** [comment]
I loaded up ITTC, I searched for "saw" I didn't get any results, I searched for "ardite" and I did not see anything that resembled or was name "saw"

**Comment by jaredlll08** [comment]
Also the very first line
'ERROR: Iguana-Tweaks.zs:13: Could not resolve <IguanaTweaksTConstruct : sawArdite>'
that means that it can't find the item.

**Comment by Dream-Master** [comment]
You need Iguana Tweaks, Tinkers construct and Project Red or/and Forge Micro Blocks than you will see the shows.
I think it is a dependency thing but it would be nice if we can find the error.

**Comment by jaredlll08** [comment]
I explained the error, I installed all the mods, Iguana Tweaks, TiC, Project Red and Forge Micro Blocks, the error is still the same, Iguana Tweaks does NOT add any saw.

**Comment by Voidi** [comment]
But we HAVE saw ingame, and they are also regonized via /mt hand and /mt names

**Comment by Dream-Master** [comment]
But which mod implement the saws then?

**Comment by Dream-Master** [comment]
I check it when i be back home. We have a mod to display the unlocalized name this will help.

**Comment by Dream-Master** [comment]
I find this 
``````````````````
net.minecraft.item.Item iguanaman.iguanatweakstconstruct.modcompat.fmp.IguanaFMPCompat.arditeSaw
``````````````

**Comment by jaredlll08** [comment]
Ok sorry, that was my mistake, I don't have a mod to check unlocalized names in my environement, I will investigate a bit more then.

**Comment by Voidi** [comment]
Here the saw item gets registered https://github.com/Chicken-Bones/ForgeMultipart/blob/82174e96fbf9504c6bc14b6db596542f4ae2835e/src/codechicken/microblock/handler/proxies.scala#L54

**Comment by jaredlll08** [comment]
ok ignore project red, since the problem is which the ardite saw, although this may suffer the same problem, so they register the items late, in ITT's case, they register in post init, in Project Red's case, it gets registered in init, I am looking to see if this can cause some issues

**Comment by jaredlll08** [comment]
Yep, we keep a different list than the minecraft one, and then we fix
issues such as spaces, thr problem was that we got that list at post init,
but the items were only geting added then, so I moved that to server
starting

**Comment by Dream-Master** [comment]
Is this fixed in Version 3.0.10?

**Comment by Dream-Master** [comment]
Ok Inguana Saws working in Minetweaker 3.0.10 Project red Saws dont work.

ERROR: Project_Red.zs:76: Could not resolve <ProjRed | Exploration : projectred . exploration . sawgruby>

recipes.remove(<ProjRed|Exploration:projectred.exploration.sawgruby>);

**Comment by jaredlll08** [comment]
Post full log and script please

**Comment by Dream-Master** [comment]
There is no log that is the problem.
Only this

````````````````
ERROR: Project_Red.zs:76: Could not resolve <ProjRed | Exploration : projectred . exploration . sawgruby>
ERROR: Project_Red.zs:439: Could not resolve <ProjRed | Exploration : projectred . exploration . sawgruby>`
``````````````

Line 76 =
```````````
// --- Ruby Saw
recipes.remove(<ProjRed|Exploration:projectred.exploration.sawgruby>);
`````````````````````

Line 439
````````
recipes.addShaped(<ProjRed|Exploration:projectred.exploration.sawgruby>, [
[<ore:stickWood>, <ore:rodSteel>, <ore:rodSteel>],
[<ore:stickWood>, <dreamcraft:item.SawBladeRuby>, <ore:rodSteel>],
[null, null, null]]);
````````````````
<dreamcraft:item.SawBladeRuby> = a item i add by my self in my core mod.

**Comment by jaredlll08** [comment]
Uh sawgRuby? Check the spelling.

**Comment by Dream-Master** [comment]
``````
<ProjRed|Exploration:projectred.exploration.sawruby>`
````
spelling is right

**Comment by Dream-Master** [comment]
wait i check

**Comment by jaredlll08** [comment]
Nope. Check again.

**Comment by Dream-Master** [comment]
Ok sory my fault woks fine now.
Thanks

Btw you said something from a version you need to test (Server sync thing with reloading)
