### ISSUE TITLE
Mekanism flamethrower blocking problem

### ISSUE THREAD

**Issue by DJIronic** [stanhebben/MineTweaker3#196]
I found an problem with Mekanism flamethrower, I can´t remove recipe for this. 
When i have script: "recipes.removeShaped(<Mekanism:Flamethrower>);" it´s ignored by the game. 
But i can add a new crafting for this. 
Can You help me ? I am running latest 1.7.10 version.

Thanks, Simon.

**Comment by Yulife** [comment]
Try adding a ":*" after Mekanism:Flamethrower. Like this "Mekanism:Flamethrower:*" Of course don't forget the < and >

**Comment by DJIronic** [comment]
I have tried this: recipes.removeShaped(<Mekanism:Flamethrower:*>); And it´s doesn´t work. It´s still same.

**Comment by DJIronic** [comment]
OK, recipes.remove(<Mekanism:Flamethrower:*>); is wokring. Thanks.

**Comment by Yulife** [comment]
Awesome :) With any tool with durability, if you want to remove the recipe of it, if it doesn't work at the first try, add a ":*" like I showed you because of all the meta datas :)

**Comment by DJIronic** [comment]
Thanks ;)

**Comment by Yulife** [comment]
*points to "Close Issue" button* :)

**Comment by DJIronic** [comment]
Sorry :(

**Comment by Yulife** [comment]
Haha, everything good!
