### ISSUE TITLE
IE Crusher does not work. Api not found

### ISSUE THREAD

**Issue by JAWSAWN** [stanhebben/MineTweaker3#198]
http://paste.ubuntu.com/11776713/

Somehow this does not work. Nor the samples on the wiki:
mods.immersiveengineering.Crusher.removeRecipe(<minecraft:blaze_powder>);
mods.immersiveengineering.Crusher.addRecipe(<ImmersiveEngineering:metal> * 8, <ImmersiveEngineering:storage:8>, 8000, <minecraft:iron_ingot>, 50);

It keeps giving me this error: http://gyazo.com/342037eca8ee2da58033462da9f6b5c5

**Comment by jaredlll08** [comment]
This isn't our fault, we don't add the support, please speak to them,https://github.com/BluSunrize/ImmersiveEngineering/issues
