### ISSUE TITLE
reload recipes conflicts with Thermal recipe refresh

### ISSUE THREAD

**Issue by krakel** [stanhebben/MineTweaker3#202]
On my own test for our mod pack, I got problems on relog at the nether. The game was not complete unloaded or I got a exception from cofh.thermalexpansion.util.crafting.SmelterManager.refreshRecipes.
So I can not use scripts for Thermal Expansion.
Is there a plan to change this behavior or a agreement with this mod?

**Comment by Yulife** [comment]
That's Modtweaker, not Minetweaker. I think it was fixed by @Zixxl recently.

**Comment by krakel** [comment]
Yes, with the newest version we got from @Zixxl the problem was gone.
