### ISSUE TITLE
NEI hide metadata 0 issue

### ISSUE THREAD

**Issue by Wolf68k** [stanhebben/MineTweaker3#203]
Using NEI.hide an item whose metadata is 0 doesn't work
I try to do: NEI.hide(<ThermalExpansion:Cell:0>); which is the creative cell, doesn't do anything.
And of course if I do NEI.hide(<ThermalExpansion:Cell>); then it hides all of the Energy Cells

**Comment by jaredlll08** [comment]
NEI support is currently broken, this has been fixed in 1.8.x by JEI
