### ISSUE TITLE
Thaumcraft aspectList command doesn't work

### ISSUE THREAD

**Issue by Killarflame** [stanhebben/MineTweaker3#204]
Attempting to use this command throws this in the console: 
http://pastebin.com/zwmEyHMN

MineTweaker3-1.7.10-3.0.9C
ModTweaker 2-0.8.1

**Comment by Yulife** [comment]
This is Modtweaker's fault. You posted it on both repos and they're both not valid. Post it here https://github.com/jaredlll08/ModTweaker2
