### ISSUE TITLE
NEI addEntry and other things bugging in NEI

### ISSUE THREAD

**Issue by gabor6505** [stanhebben/MineTweaker3#205]
If I write something that adds an entry to NEI, like if I only want to have 1 of each type of microblock, then, if I reload the scripts, it adds what I wanted, then if I reload it again, it hides all the added entries in NEI and I can only fix that with restarting the game. If I actually don't do any changes to scripts, just log into a world, type "/mt reload" once, it still hides all the custom added entries, and I have to restart the client again in order to see those added entries. So this is actually a minor issue, but I can't see the NEI changes real-time (when I write the scripts).

An Example Script for addEntry (AgriCraft):
NEI.addEntry(<AgriCraft:waterTank>.withTag({matMeta: 0, material: "minecraft:planks"}));

Some Screenshots:
AgriCraft and BiblioCraft custom registered Oak Wood Planks (and Sacred Oak too for the BiblioCraft) versions:
![2015-07-15_19 28 26](https://cloud.githubusercontent.com/assets/12859334/8705125/e3b6bc10-2b27-11e5-8ee4-f4ff2039025f.png)

And they are gone:
![2015-07-15_19 28 57](https://cloud.githubusercontent.com/assets/12859334/8705140/01b1ae0a-2b28-11e5-8655-fe59303437c8.png)

MineTweaker version: 3.0.9C

MineTweaker related mods used:
ModTweaker 0.8.3
MineTweaker RecipeMaker 1.1.0.11

And I use a bunch of other mods, if you need a modlist, or other infos, tell me.
I do use OptiFine, but I don't think that's the case.

**Comment by stanhebben** [comment]
The sad reality, as of today, is that reload doesn't work well with NEI. I haven't been able to fix these issues so far and not sure if this one can actually be properly fixed. In the end, I am merely trying to use the NEI API functions to emulate reloadability, but it doesn't work well.

**Comment by jaredlll08** [comment]
NEI scripts cannot be reloaded

**Comment by gabor6505** [comment]
They can be reloaded, the reload just vanishes all items that are controlled via MineTweaker. That would be the best thing/solution in order to fix this if they cannot be reloaded. So it would only load NEI scripts/lines once every startup. That would be better than they just disappear from NEI.
I might have to use InPureCore for the NEI handleing, if this is not going to be fixed, but it's okay :smile:
