### ISSUE TITLE
[Enhancement] Add a method to convert ore dictionary entry to an itemstack

### ISSUE THREAD

**Issue by hron84** [stanhebben/MineTweaker3#206]
In 1.6.4 we had a .any property on ore dictionary entries that can be used on any place where normal ore dictionary entries aren't. 

For example, Forestry Carpenter cannot accept an ore dictionary entry as an ingredient, but i found no way to convert `<ore:plankWood>` to something like `<minecraft:planks:*>`.

**Comment by Voidi** [comment]
Not as easy to use as any, but you can loop over oreDict entrys:
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Ore_Dictionary#Iterating_over_the_values_in_an_oredict_entry

And the Carpenter should support OreDict in the next Modtweaker update.

**Comment by hron84** [comment]
@Voidi I saw this, but this will generate a very-very lot of recipe to carpenter that will slow down carpenter recipe lookups. Also this will require to ingredients be same item, so you cannot make a impregnated casing mixing `<minecraft:logWood>` and `<minecraft:logWood:2>`

I would be very-very happy if Carpenter get OreDict support soon.

**Comment by stanhebben** [comment]
.any could only be used in removal patterns, not for adding. I have been considering to automatically expand ore dictionary items as fallback, but I would have to add support for each supported machine individually, which is a lot of work. I didn't get into it as there were other priorities. The loops are a solution if there are not a lot of inputs - you could support nested loops if a recipe has multiple oredict inputs - but that would result in a lot of code (and added recipes) pretty quickly.

**Comment by hron84** [comment]
@stanhebben my basic problem is every single loop causes new recipe. In the plankWood/logWood case it can be very extensive, especially if you have a little more mod that adds enormous amount of trees like Forestry or Plant Mega Pack does. It can slow down NEI, spams the machine recipes and so on. I already got how can I implement it anyway with loops - just I think it's not the way it _should_ be implemented. 

Btw, actually carpenter currently **has** an oredict support only ModTweaker recipe handler does not support that.

**Comment by Voidi** [comment]
By now https://github.com/jaredlll08/ModTweaker2/commit/c0df1733daa8fce69e5db11c6e95bcdca7d69fbf oredict support

**Comment by hron84** [comment]
@Voidi I :heart: this, when do you plan to do a release with this fix?

**Comment by jaredlll08** [comment]
unfortunately, there isn't really a fix on our side for that, the mod has to edit the way their nei handler works. also that modtweaker version got released a while ago.

**Comment by hron84** [comment]
@mezz could you help us?

**Comment by jaredlll08** [comment]
Well actually, could you explain this a bit better please? Just to make
sure I am talking about the right thing

**Comment by Yulife** [comment]
Perhaps you look at the 1.6.4 method @hron84 is talking about :)

**Comment by mezz** [comment]
I do not really know anything about MineTweaker so it would be helpful for me to have an issue that is just in terms of Forestry.
Does the Carpenter's recipe need to change to allow oredict strings in addition to items?
Please create an issue here and I'll see what I can do: https://github.com/ForestryMC/ForestryMC/issues

**Comment by Voidi** [comment]
@mezz This was some type of mismention. Everything is fine. No problems with forestry.

**Comment by hron84** [comment]
@Voidi so it means MT does not support oredict strings in carpenter recipes or MT supports it, but the Carpenter's recipe handler does not understand it? The original issue was I cannot use `<ore:plankWood>` and `<ore:logWood>` in Carpenter recipes (to be specific: in MineTweaker Carpenter recipes), even if the Carpenter internally could handle this problem with its own logs and planks Now I confused what is happening around me. @jaredlll08 mentioned this: "the mod has to edit the way their nei handler works" and I meant "the mod" is means the Forestry, so some change is needed at Forestry side. I kindly ask you to clarify the current situation, maybe my English is not too strong and I misunderstand things. I would be very-very thankful for your help.

**Comment by Voidi** [comment]
The Carpenter handler in *Modtweaker* now supports OreDict but we forgot to update the wiki and there will be some updates in the function signature, so please wait for the next update and then check the wiki again.

**Comment by hron84** [comment]
Cool, thanks for clarification.
