### ISSUE TITLE
[Enhancement] Add ability to change liquid dictionary

### ISSUE THREAD

**Issue by nanakisan** [stanhebben/MineTweaker3#210]
Never thought I would ask about this. But awhile back I noticed that MT has support for altering fluid containers. However what would the possibility of changing a liquid dictionary? This would be more on a case by case situation. Not everyone will need to alter a fluid block itself. But for the sake of certain mod interactions it could prove useful.  
  
Mostly with mods that add in-world ways of grabbing fluids that are registered as certain types.

**Comment by Blue64** [comment]
For example: ```<PneumaticCraft:oil>``` becomes a BuildCraft Oil as soon as you scoop it up or pour it out if you've got both mods installed (also PneumaticCraft Oil Bucket isn't registered to ```<fluid:oil>``` in my version, this may have been patched in an update, I've not checked)

**Comment by jaredlll08** [comment]
This is harder than you think, mods have to subscribe to an event to make buckets pick up fluids, there is no registry that we can edit to allow this

**Comment by Blue64** [comment]
harder, but possible :)
