### ISSUE TITLE
Ambiguous recipe IC2.

### ISSUE THREAD

**Issue by Tsyklop** [stanhebben/MineTweaker3#214]
add IC2 recipe:
mods.ic2.ThermalCentrifuge.addRecipe([<IC2:itemPartIndustrialDiamond>, <IC2:itemDust2:1>], <minecraft:diamond>, 2500); 

and:

![2015-08-02_19 20 42](https://cloud.githubusercontent.com/assets/6783568/9026973/bfcca45e-394b-11e5-860c-55c941c63c81.png)

why?

**Comment by stanhebben** [comment]
Does this error occur after reloading? I believe IC2 cannot roll back recipe changes, so a reload might add the recipe twice, resulting in an error like this one, complaining it already has a recipe with diamond as input.

**Comment by Dream-Master** [comment]
Yes with Gregtech the same.

**Comment by Tsyklop** [comment]
@stanhebben This occurs even when you first start and when you first log into the world.

**Comment by Tsyklop** [comment]
please fix this!

**Comment by xelrix** [comment]
Maybe it's your systax? I think you forgot to <> the ID names. Try;
mods.ic2.ThermalCentrifuge.addRecipe([<IC2:itemPartIndustrialDiamond>, <IC2:itemDust2:1>], <minecraft:diamond>, 2500);

**Comment by Tsyklop** [comment]
@xelrix I solved this problem by changing the recipe in the configuration of the IC2. And if it is through the MT problem likely mod.
