### ISSUE TITLE
Block not being able to be defined and stanhebben.zenscript.value.IAny.as(Ljava/lang/object;Ljava/lang/class; Error

### ISSUE THREAD

**Issue by MineTreker** [stanhebben/MineTweaker3#215]
I am trying to run this code
val gearCopper = (<thermalexpansion:machineCopper:128>);
val BasicFrame = (<thermalexpansion:machineFrame:0>);
val RRCoil = (<ThermalExpansion:material:1>);
val BasePulverizer = (<ThermalExpansion:Machine:1>);
val BasicPulverizer = BasePulverizer.withTag({Level:"0"});
val HardenedPulverizer = BasePulverizer.withTag({Level:"1"});
val ReinforcedPulverizer = BasePulverizer.withTag({Level:"2"});
val ResonantPulverizer = BasePulverizer.withTag({Level:"3"});
recipes.remove(<ThermalExpansion:Machine:1>);
recipes.addShaped(BasicPulverizer,
[[null, <appliedenergistics2:tile.BlockGrinder>, null],
 [<minecraft:flint>, BasicFrame, <minecraft:flint>],
 [gearCopper, RRCoil, gearCopper]]);

It defines a ton of values, some of them using metadata and a few using NBT Tags. It removes the recipe for all pulverizers, and adds the Basic Pulverizer recipe back, using the AE2 Grinder. It returns these errors
ERROR: Pulverizer.zs:2: Could not resolve <thermalexpansion : machineFrame>
ERROR: Pulverizer.zs:5 > No such static member in minetweaker.item.IItemStack: BasicPulverizer
ERROR: Error executing Pulverizer.zs: stanhebben.zenscript.value.IAny.as(Ljava/lang/Object;)Ljava/lang/Class;

As far as I can tell, nothing is wrong with the script, please correct me if im wrong

**Comment by stanhebben** [comment]
Do you mind to pastebin the script? Github has a habit of eating the angled brackets.

**Comment by MineTreker** [comment]
sure thing 
http://pastebin.com/0wthpDCq

**Comment by MineTreker** [comment]
And the vars are actually vals, not that it really matters

**Comment by MineTreker** [comment]
NVM i figured it out, but god is is difficult to alter the recipes of Thermal expansion machines so that you can use all of the types of each machine. They have like 20 NBT tags
