### ISSUE TITLE
Still unable to create int[] in tag

### ISSUE THREAD

**Issue by TechnicianLP** [stanhebben/MineTweaker3#217]
https://github.com/stanhebben/MineTweaker/issues/35

as said i chaged my code to:
NEI.addEntry(appliedenergistics2:item.ItemFacade:0.withTag({ custom:1, itemname:"log", modid:"minecraft", x:[17,0] as int[]}));

now minetweaker sends me the error: "cannot cast int[] to minetweaker.data.idata"

**Comment by TechnicianLP** [comment]
Integer[] doesnt work either

**Comment by LakMoore** [comment]
Have you tried just removing the " as int[]" from the data string?  I had a similar problem with an array of bytes.

**Comment by jaredlll08** [comment]
Closed in the Java8 branch of CraftTweaker
