### ISSUE TITLE
Problem with int[] NBT tag in the Applied Energistics 2 Cable Facades

### ISSUE THREAD

**Issue by gabor6505** [stanhebben/MineTweaker3#219]
I want to remove all Cable Facades from NEI except one (the Oak Wooden Planks), and I successfully did it with Forge Microblocks, BuildCraft Facades and Extra Utilities Microblocks, but it does not seem to work with Applied Energistics 2. Here is the Error:

ERROR: NEI Tweaks.zs:453 > cannot cast int[] to minetweaker.data.IData

I use this script to do this (I copied the Item with the Tooltips command + Ctrl, so it has to be right):
`NEI.addEntry(<appliedenergistics2:item.ItemFacade>.withTag({itemname: "planks", x: [5, 0] as int[], modid: "minecraft"}));`

I think it might be because I am not importing something, but I don't know what to import and the page about NEI does not tell me if I need to import anything more than `import mods.nei.NEI;`, because this is already in my script.
If you need more info, tell me.

EDIT: I tested with importing this (besides the NEI thing mentioned above): 
`import minetweaker.data.IData;`
And it didn't work.

**Comment by TechnicianLP** [comment]
same problem .... https://github.com/stanhebben/MineTweaker3/issues/217

**Comment by jaredlll08** [comment]
Closed in the Java8 branch of CraftTweaker
