### ISSUE TITLE
Not working Buildcraft IntegrationTable.

### ISSUE THREAD

**Issue by Tsyklop** [stanhebben/MineTweaker3#221]
import mods.buildcraft.IntegrationTable;

IntegrationTable.addRecipe(<minecraft:lever>, 1000, <minecraft:cobblestone>, <minecraft:stick>);

No Such static member in mods.buildcraft.IntegrationTable: addRecipe

**Comment by Voidi** [comment]
Buildcraft support was moved the The Buildcraft-Compat mod so ask there.
