### ISSUE TITLE
Nullpointerexception when registering class

### ISSUE THREAD

**Issue by Lilylicious** [stanhebben/MineTweaker3#222]
G'day.

Trying to do some mod integration with MineTweaker and I'm failing miserably. 

Error: http://pastebin.com/QJK1mSGx
Jar: MineTweaker3-Dev-1.7.10-3.0.9C.jar
Added as an external library in IDEA.

Class that's failing to be added: [Class](https://github.com/Lilylicious/ProjectE/blob/MineTweaker/src/main/java/moze_intel/projecte/integration/MineTweaker/HiddenShapeless.java)

---
EDIT: The issue has been found by my lovely team member @MaPePeR

Turns out that using ItemStack instead of IItemStack causes a NPE. Issue is solved, but there really could be better error reporting. A NPE for a type error seems silly.

**Comment by MaPePeR** [comment]
A simple descriptive Exception [here](https://github.com/stanhebben/MineTweaker3/blob/47f59a78a13d0b8346223a6f6bf9f5a1b1826adb/ZenScript/src/main/java/stanhebben/zenscript/compiler/TypeRegistry.java#L105-L108) would have been great.

**Comment by jaredlll08** [comment]
The referenced file is not found, also I would suggest you look at [ModTweaker](https://github.com/jaredlll08/ModTweaker2) to see how to add support.

**Comment by MaPePeR** [comment]
@jaredlll08 Using `ItemStack` instead of `IItemStack` in `@ZenMethod` caused that NPE: 
[Reference File](https://github.com/Lilylicious/ProjectE/blob/8716277a3b9e4cbfd0a8b2b5d9f6ce2cb88324cd/src/main/java/moze_intel/projecte/integration/MineTweaker/HiddenShapeless.java#L37)

**Comment by jaredlll08** [comment]
Yea, if you want, I guess I could ad a ClassCastException, since it is
technically that...

**Comment by Lilylicious** [comment]
The mod support is complete on our end, after figuring out that itemstack classcastexception it wasn't very difficult to complete. An accurate error would be great though, thanks! NPE doesn't scream CCE to me.

**Comment by jaredlll08** [comment]
Well we return null, the npe is caught somewhere else. We return null
because, ItemStack cannot be cast to IType or anything that we use, so I
would call that a CCE, but please correct me if I am wrong

**Comment by Lilylicious** [comment]
It is a CCE, but it wasn't very obvious to someone not familiar with your code that the issue was a CCE when the log talked about a NPE, that's what I was saying. Thank you for the awesome work!

**Comment by MaPePeR** [comment]
From that stacktrace it still looks like the cause is `cls.getPackage()` or `cls.getPackage().getName()` returning `null`. For me this indicates a problem with accessing the package and not casting the class.

**Comment by jaredlll08** [comment]
Well all the work is Stan, I litterally started here this morning :3 also,
the null is on cls iirc the cls is null becuase we return null, since
ItemStack is not an IType

**Comment by MaPePeR** [comment]
If `cls` would be `null` I would expect [this line](https://github.com/stanhebben/MineTweaker3/blob/master/ZenScript/src/main/java/stanhebben/zenscript/type/ZenTypeNative.java#L106)  to npe earlier. 

I don't know, but anything is probably better than that npe.

**Comment by jaredlll08** [comment]
hhm that is interesting. @stanhebben can you provide some input please?

**Comment by MaPePeR** [comment]
(Be aware, that I drawed this conclusion only  from looking at the code and guessing. I did not test it or use a debugger. I might be totally wrong... But from looking at the code that is what I think is happening)

**Comment by jaredlll08** [comment]
Yea I understand, and honestly I am doing the same right now, I only started looking at it yesterday, but I have a feeling that the method that returns null is the cause of the problem, since ItemStack is not an instance of IType
