### ISSUE TITLE
IC2 Overwite Recpie Support

### ISSUE THREAD

**Issue by gnif** [stanhebben/MineTweaker3#224]
Upon investigation of the IC2 api it seems there is an additional boolean paramater that can be passed to addRecepie which when true allows overwriting of existing recepies.

```
public class BasicMachineRecipeManager
  implements IMachineRecipeManagerExt
{
  public void addRecipe(IRecipeInput input, NBTTagCompound metadata, ItemStack... outputs)
  {
    if (!addRecipe(input, metadata, false, outputs)) {
      displayError("ambiguous recipe: [" + input.getInputs() + " -> " + Arrays.asList(outputs) + "]");
    }
  }
  
  public boolean addRecipe(IRecipeInput input, NBTTagCompound metadata, boolean overwrite, ItemStack... outputs)
  {
    return addRecipe(input, new RecipeOutput(metadata, outputs), overwrite);
  }
```
This is exposed by the class `IMachineRecipeManagerExt` which extends `IMachineRecipeManager`

```
public abstract interface IMachineRecipeManagerExt
  extends IMachineRecipeManager
{
  public abstract boolean addRecipe(IRecipeInput paramIRecipeInput, NBTTagCompound paramNBTTagCompound, boolean paramBoolean, ItemStack... paramVarArgs);
}
```

Would be great to get this added.

**Comment by Dream-Master** [comment]
Why you not make a pull request?

**Comment by gnif** [comment]
Because I do not have a build environment at current.

**Comment by stanhebben** [comment]
The API exposes everything as IMachineRecipeManager. Next version will check try to use IMachineRecipeManagerExt, if possible.

**Comment by gnif** [comment]
I have tested this in a custom mod I have thrown together, it works fine. It only exposes it as IMachineRecipeManager for legacy support with older mods, you are expected to typecast it to IMachineRecipeManagerEx to be able to call the new prototype.
