### ISSUE TITLE
Releasing a new minetweaker version ?

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#228]
@jaredlll08 
I see you take care the things round about minetweaker 3. Are you planning a new release with all this changes and new features.

**Comment by jaredlll08** [comment]
What is happening is, I will go through the issues, do everything I can do, add some features, then when I feel that it is worthy of a release, tell Stan, and he will release it. So there WILL be a new version in the near(?) future.

**Comment by Dream-Master** [comment]
Ok thanks for this info.
