### ISSUE TITLE
The minetweaker commands don't work

### ISSUE THREAD

**Issue by Tsyklop** [stanhebben/MineTweaker3#235]
I enter commands and writes to me that these commands do not exist

MineTweaker3-1.7.10-3.0.10

**Comment by stanhebben** [comment]
Which commands are you trying to use? Does it happen in single or multiplayer?

**Comment by Tsyklop** [comment]
@stanhebben I play in a single game. 

/ mt hand, / mt reload ... 

Just leaf through all the pages of "help" and commands MT have not seen

**Comment by stanhebben** [comment]
That's odd, I always test with those commands (and they still work as I've tested again now).

Can pastebin me the fml log?

**Comment by Tsyklop** [comment]
WTF! It's magic!I start now and everything works! I am surprised.... 

Excuse me...

**Comment by Tsyklop** [comment]
Command work but now I have another problem.

I add a recipe for Metal Former of IC2.

mods.ic2.MetalFormer.addExtrudingRecipe (<IC2: itemPartIndustrialDiamond>, <minecraft: diamond>);

MT reboot and shows me two messages:

WARNING: No furnace recipes for <IC2: itemPartIndustrialDiamond> - it shows in the chat at startup world as well as when reboots MT.

And:

![2015-09-06_13 41 05](https://cloud.githubusercontent.com/assets/6783568/9703976/52081fbc-549d-11e5-8e48-49b3e137ac6c.png)

**Comment by jaredlll08** [comment]
That is a minetweaker thing, it is saying that there is no recipe for that item.

**Comment by Tsyklop** [comment]
so I did not add IndustrialDiamond recipe in the furnace.

**Comment by Tsyklop** [comment]
Same: https://github.com/stanhebben/MineTweaker3/issues/214

**Comment by Tsyklop** [comment]
heeelp

**Comment by Yulife** [comment]
Spamming does not fix it. Try to use 3.0.9C.

**Comment by Tsyklop** [comment]
@Yulife On the furnace, I decided to question.
I noticed that the game can boot MT scripts will work but the commands does not have. This is not always the case.

But the problem remained and IC2 3.0.9c

**Comment by dualinfinities** [comment]
My scripts randomly stopped being read, and I don't have working commands. The weird thing is, this just randomly happened after it working perfectly for a few minutes after updating. Reloading or restarting doesn't help the issue.

**Comment by Tsyklop** [comment]
@dualinfinities I have downloaded and run the scripts but the commands could not function.

**Comment by Dream-Master** [comment]
login again and it works or close in sp the game and start again.
Not sure if this works for Server too.

**Comment by jaredlll08** [comment]
What has this issue turned to?! first it was commands, then it wasn't commands, then it was IC2( which was a DUPLICATE ISSUE MADE BY THE SAME PERSON! >:( ) then it was reload not working, then something about servers.
Decide what the issue is about, then make another issue for the other problems.

**Comment by Tsyklop** [comment]
@jaredlll08 With the IC2 I decided the issue already. He has to change the recipe files - now I change the recipe files. But the problem with the commands still there.
Sometimes the game is loaded but the commands MT do not work and you have to reboot.

**Comment by Dream-Master** [comment]
@jaredlll08 
https://github.com/stanhebben/MineTweaker3/issues/237#issuecomment-140938054

**Comment by jaredlll08** [comment]
I know! I am fixing it! Just wait! (For commands and reloading)

**Comment by Dream-Master** [comment]
Thanks
