### ISSUE TITLE
[Request Feature] TinkerConstruct support: a way to disable a modifier

### ISSUE THREAD

**Issue by ExDomino** [stanhebben/MineTweaker3#238]
I requested TinkerConstruct's author to add an option to remove a modifier, for example the flux capacitor modifier, but I think he doesn't want to add this option. I'm wondering if there is a way with MineTweaker, or MineModTweaker, to do so? Thanks you in advance!

**Comment by Yulife** [comment]
It's Modtweaker, hehe :) Please close this issue here as it belongs to the Modtweaker repo.

**Comment by jaredlll08** [comment]
This would be for modtweaker.
