### ISSUE TITLE
Blood Magic Removing Reinforced Slate Not Always Working

### ISSUE THREAD

**Issue by RoloEdits** [stanhebben/MineTweaker3#240]
MineTweaker3-1.7.10-3.0.10

mods.bloodmagic.Altar.removeRecipe(<AWWayofTime:reinforcedSlate>);

This script does work, but after making changes to anything in the file that has nothing to do with this ,and reloading the changes using the mt reload command, it shows back up like if it was not removed.
To work around this it seems if you move this line of script from a different line than the one it was on, and reload it, it sometimes works.For example moving it from line 1 to 10 would work.

**Comment by jaredlll08** [comment]
Mt reload should never be used for mods. end of story.
also we don't add support for blood magic.

**Comment by RoloEdits** [comment]
Sorry,

Thank you for your time.
