### ISSUE TITLE
Can't add seeds into planter.

### ISSUE THREAD

**Issue by xelrix** [stanhebben/MineTweaker3#241]
`import mods.mfr.Harvester;`
`Planter.addPlantable(<magicalcrops:magicalcrops_AirSeeds>);`
`Planter.addPlantable(<nevermine:EyeBulbSeeds:0>);`
`Planter.addPlantable(<AgriCraft:seedPotato:0>, <magicalcrops:magicalcrops_AirCrop:0>);`

Neither of these works. There is no error in log. The script loaded fine. But the planter doesnt register the added seeds.
Using [MineFactoryReloaded-[1.7.10]2.8.1B1-131] and the latest recommended forge for 1.7.10

UNRELATED EDIT: Thanks Yulife for the formatting tip!

**Comment by Yulife** [comment]
You need to use ```. For example, if you surround a piece of text with that, this happens:
```<minecraft:dirt>```

**Comment by Yulife** [comment]
For example:
``` <minecraft:dirt> ```

**Comment by xelrix** [comment]
I've found out with this line;
`Planter.addPlantable(<AgriCraft:seedPotato>, <AgriCraft:cropPotato>);`
the seed do get planted, but on plain dirt.
There was a crop spawned on the dirt, but it wouldnt grow because it is not on a minecraft:farmland.
Though the planter would plant a regular seed (which is a default), after it till the dirt. This behavior is not observed with seeds added by minetweaker.
I don't know if this a problem with what minetweaker tell the planter, or problem with the planter itself.
I notice from the Planter.java, 
`private static final IBlockPattern GRASS_OR_DIRT;`
`static {`
`IBlock blockDirt = MineTweakerMC.getBlockAnyMeta((Block) Block.blockRegistry.getObject("minecraft:dirt"));`
`IBlock blockGrass = MineTweakerMC.getBlockAnyMeta((Block) Block.blockRegistry.getObject("minecraft:grass"));`
`GRASS_OR_DIRT = blockDirt.or(blockGrass);`

maybe change it to <minecraft:farmland> ?

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
