### ISSUE TITLE
ERROR: system: Crop is already defined in that package

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#244]
Is this an minetweaker or a Modtweaker error.?
I find this in the first line of my minetweaker log.

**Comment by jaredlll08** [comment]
Need script

**Comment by Dream-Master** [comment]
I not using any script with crops.

**Comment by jaredlll08** [comment]
Still give me the script.

**Comment by Dream-Master** [comment]
wich one i have a bunch of scripts?
I link you to my gihub source of scripts.

https://github.com/GTNewHorizons/NewHorizons/tree/master/scripts-testserver

**Comment by Dream-Master** [comment]
Is crop from ic2?

**Comment by jaredlll08** [comment]
I honestly don't know on this one.

**Comment by Dream-Master** [comment]
No problem is not gives me any error in the game only this in the log.
It seems there are some double entries in the code maybe.
Before i have this problem too in my GT Tweak addon for minetweaker as i add Recipes handlers with the same name minetweaker did. Now minetweaker exclude gt support an the erro is gone.
So we let this open untill we find the error?

**Comment by jaredlll08** [comment]
Found and fixed the error

**Comment by Dream-Master** [comment]
Ok thanks
