### ISSUE TITLE
Untextured ingredients with NBT-based textures.

### ISSUE THREAD

**Issue by ZeroLevels** [stanhebben/MineTweaker3#245]
**Mod:** This is in regards to the VarietyChests mod.  This is not a crafting issue.  It's a display issue with NEI recipes added by MineTweaker.  I am not sure if it's caused by something within VarietyChests, or if it is something overlooked with the built in NEI support for MineTweaker.

**Issue:** VarietyChest's textures are applied based on the NBT of each chest.  When adding recipes based on said chests, all that are specified as output (withTag) are textured fine within NEI.  However, when specifying the chests as input (onlyWithTag), they show up in NEI as untextured.  The recipes themselves work as expected.

I imagine this might be what the VarietyChests' NEI fix in its config was meant to fix, but said fix makes the recipes *appear* unaffected by NEI.

**Comment by UndeadZeratul** [comment]
You can set both withTag() and onlyWithTag() on the same variable.  In fact, I'd set a variable with the item and the withTag() set, then reference it along with the onlyWithTag() called as well.  That way, both the input and output will have the NBT tag, and the input will only accept the one with that NBT tag.

If all that makes sense, that is.  If not, let me know and I'll write up some short example code.

**Comment by ZeroLevels** [comment]
Oh.  You're right.  I tried this before, but I must have done it incorrectly the first time.  Worked fine this time.  Thank you kindly. :)

**Comment by UndeadZeratul** [comment]
Oh cool, glad to hear that worked.
