### ISSUE TITLE
Recipe problems

### ISSUE THREAD

**Issue by NanoSymmetry** [stanhebben/MineTweaker3#248]
So im making a private mod pack and i cant figure out why this is broken it sometimes says it loads the script successfully but dosen't change the recipie.

I was told on the modtweaker issue page and they said it was a minetweaker problem.

recipes.remove(ThermalExpansion:Frame);
recipes.addShaped(ThermalExpansion:Frame,
[[ore:ingotSteel, ore:blockGlass, ore:ingotSteel],
[ore:blockGlass, ore:gearTin, ore:blockGlass],
[ore:ingotSteel, ore:blockGlass, ore:ingotSteel]]);

Mods---\/
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
CodeChickenCore (by chicken_bones)
CoFH Core (by TeamCoFH)
JourneyMap (by techbrew)
Inventory Tweaks (by Kobata)
Thermal Foundation (by TeamCoFH)
Jabba (by ProfMobius)
Waila Harvestability (by squeek502)
NEI Addons (by bdew)
NEI Integration (by tonius111)
Applied Energistics 2 (by AlgorithmX2)
TiC Tooltips (by squeek502)
Thermal Dynamics (by TeamCoFH)
AromaBackup (by Aroma1997)
Blood Magic (by WayofTime)
CoFHLib (by TeamCoFH)
Simply Jetpacks (by tonius111)
Iguanas Tinker Tweaks (by bonusboni)
NetherOres (by skyboy026)
Carpenter's Blocks (by Syntaxial)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
ExtraTiC (by JeanGlassmaker)
Ender IO (by CrazyPants_MC)
ChickenChunks (by chicken_bones)
Solar Flux (by Nauktis)
Dense Ores (by RWTema)
Ender Storage (by chicken_bones)
RFTools (by McJty)
Morpheus (by quetzi)
Translocators (by chicken_bones)
ExtraCells2 (by DrummerMC)
iChunUtil (by iChun)
Morph (by iChun)
FastLeafDecay (by Olafskii)
ArmorStatusHUD (by bspkrs)
HelpFixer (by matthewprenger)
QmunityLib (by quetzi)
MobiusCore (by ProfMobius)
Blue Power (by quetzi)
MmmMmmMmmMmm (by bonusboni)
Warp Book (by panicnot42)
FoxLib (by KitsuneKihira)
Tails (by KitsuneKihira)
Extra Utilities (by RWTema)
Minefactory Reloaded (by skyboy026)
Chisel 2 (by TheCricket26)
WR-CBE-Universal (by chicken_bones)
MineTweaker3 (by StanH)
ModTweaker (by jaredlll08)
Guide-API (by TehNut)
Baubles (by azanor)
CompactStorage (by tattyseal)
Biomes Tweaker (by Zehir_)
Aroma1997Core (by Aroma1997)
Buildcraft (by CovertJaguar)
Waila (by ProfMobius)
Logistics Pipes (by RS485)
McJtyLib (by McJty)
Ex Nihilo (by Erasmus_Crowley)
Storage Drawers (by jaquadro)
NotEnoughItems (by chicken_bones)
Thermal Expansion (by TeamCoFH)

**Comment by Yulife** [comment]
Which Minetweaker version are you using?

**Comment by NanoSymmetry** [comment]
minetweaker 3.0.10

**Comment by Yulife** [comment]
Please try [this](https://github.com/stanhebben/MineTweaker3/issues/237#issuecomment-140938057) version.

**Comment by NanoSymmetry** [comment]
With that version every recipe is broken.

**Comment by Yulife** [comment]
Oh man! :open_mouth: People had some issues with 3.0.10, try 3.0.9C please :)

**Comment by NanoSymmetry** [comment]
tryed that version it keeps saying ERROR: Error parsing MineTweaker.zs:27 -- : Expected

**Comment by Yulife** [comment]
Just tested, cannot reproduce in the latest version. Please disable all your scripts except this one and test.

**Comment by NanoSymmetry** [comment]
not the same error but with -- ) expected

**Comment by Yulife** [comment]
Do you use brackets?

**Comment by NanoSymmetry** [comment]
yes i did all brackets are balenced

**Comment by Yulife** [comment]
Can't help you then, mate. It's on your end.

**Comment by NanoSymmetry** [comment]
its ok thanks for trying :)

**Comment by Yulife** [comment]
:grin:

**Comment by jaredlll08** [comment]
The errors you are getting shows that it is a script / user error, I would suggest reading through your scripts properly and making sure they are all correct.
