### ISSUE TITLE
Mods wildcards

### ISSUE THREAD

**Issue by Neodark7** [stanhebben/MineTweaker3#251]
Hi ! is that possible to do something like that ? : 
recipes.remove(<rftools:*>);

if not, can you add it ? :)

**Comment by Dominance** [comment]
You can make your own wild cards with Item stacks.

**Comment by Blue64** [comment]
How exactly would we do that? I assume you're not simply referring to the OreDict.

**Comment by jaredlll08** [comment]
To explain in more detail how this would work it would be,
Create an IItemStack[],
Fill the array with all rftools items (Manually)
Loop through array
Done.

**Comment by Blue64** [comment]
Ohh, thank you. I don't think I saw that anywhere in the wiki.

**Comment by PrincessRTFM** [comment]
IItemStack[] arrays were mentioned briefly in one of the advanced sections, but it was more example than explanation. The wiki is still a work in progress.

**Comment by Blue64** [comment]
To say that is a minor understatement lol

**Comment by Blue64** [comment]
#292 is where I've posted an issue tracker for the wiki, because I honestly have zero clue how to work the wiki lol been way to busy to figure it out. I still chuckle at the ```<minecraft:tnt>``` listed as an Output Fluid ```:P```

**Comment by jaredlll08** [comment]
I'm closing this, you can use an IItemStack array
