### ISSUE TITLE
Issue when using NEI name overriding

### ISSUE THREAD

**Issue by Neodark7** [stanhebben/MineTweaker3#252]
When i use the example for overrinding names in NEI ( http://minetweaker3.powerofbytes.com/wiki/Mods:NEI_Support ) i get this

WARNING: 1 modifications were stuck
Scripts reloaded

WARNING: 2 modifications were stuck
Scripts reloaded

etc...
The scripts and the overrinding itself works but this message can be pretty anoying now i'm at "WARNING: 138 modifications were stuck" :D

**Comment by PitchBright** [comment]
Check the minetweaker.log file to see if it shows you were the error is occurring.

**Comment by Neodark7** [comment]
The log ? are you serious ? 4 month after ? D:

**Comment by PitchBright** [comment]
Yeah, I only ran into the "Warning: x modifications are stuck" issue just now myself. Found some other posts elsewhere that suggest to look at the minetweaker.log. That helped me find where the problem is. In my case GardenStuff Compost Bin.

Also, there was a post somewhere that suggested the stuck modification might be modtweaker related. I'm just working through my issue now.

**Comment by Neodark7** [comment]
sorry i tought you was a dev or something, yeah but man 4 month if you think i keep the logs all that time :D those mods are broken dude... D:

**Comment by PitchBright** [comment]
Oh, I didn't realize you gave up on it, and ditched the mod. I though maybe you were still experiencing the issue.

**Comment by Neodark7** [comment]
yeah but i can try to reproduce it again, that's why i use git for my modpack configs :)

**Comment by PitchBright** [comment]
Cool! Lemme know how you make out with it, and if you figure out the cause (and solution), please and thanks!

**Comment by Neodark7** [comment]
WARNING: 12 modifications were stuck
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronFrame to Steel Frame
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronTubing to Steel Tubing
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronWiring to Redstone-Steel Wiring
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronFrame to Steel Frame
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronTubing to Steel Tubing
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronWiring to Redstone-Steel Wiring
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronFrame to Steel Frame
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronTubing to Steel Tubing
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronWiring to Redstone-Steel Wiring
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronFrame to Steel Frame
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronTubing to Steel Tubing
INFO: Stuck: Overriding NEI item name of item.advgenerators.IronWiring to Redstone-Steel Wiring

This is caused by overriding the name of items, in my case, advanced generators items

**Comment by PitchBright** [comment]
Are you using ModTweaker?

**Comment by Neodark7** [comment]
in the pack yes, with that precisely no it's basic nei stuff

**Comment by PitchBright** [comment]
Okay interesting. Our problems aren't similar then I don't think. I've never dabbled with NEI renaming so I can't offer much more help there, sorry. :(

**Comment by Neodark7** [comment]
do you have a repo with your scripts i can help if you need and if i can ofc

**Comment by PitchBright** [comment]
Unfortunately I don't. But I've isolated the issue, and troubleshooted it pretty good. I've just now filed a issue with the mod's author about it. We've hit a few hiccups with this block and MT in the past, so he may have the answer quickly. Thanks though!

**Comment by Blue64** [comment]
Do you have the link to the post you made @PitchBright in case anyone else is looking up all of this information as well

**Comment by PitchBright** [comment]
Sure thing!
https://github.com/jaquadro/GardenCollection/issues/45

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
