### ISSUE TITLE
Wildcard in output on recipe removal causes removal of all recipes using a custom recipe handler

### ISSUE THREAD

**Issue by Yvonne015** [stanhebben/MineTweaker3#253]
This is a bug with `MineTweaker3-MC1710-Main/src/main/java/minetweaker/mc1710/recipes/MCRecipeManager.java`

When you try to remove a recipe using a wildcard output `<*>`, the provided ingredients array is not null, and the recipe handler is not an instance of `ShapedRecipes` or `ShapedOreRecipe` or their shapeless counterparts, the recipe will always be removed.

This will for instance break all microblock recipes involving the saw.
### To reproduce:

Include the following line in a script:
`recipes.removeShapeless(<*>, [<minecraft:stone>]);`  
### Expected result:

All shapeless recipes that include stone in their ingredients will be removed.
### Actual result:

In addition to the expected result, all recipes using custom recipe handlers will be removed (like recipes involving tools with durability, such as the microblock saw).
You will also see a line similar to the following in minetweaker.log:
`INFO: Removing 25514 recipes`
### Fix:

``` java
if (ingredients != null) {
  if (recipe instanceof ShapedRecipes) {
    /*...*/
  } else if (recipe instanceof ShapedOreRecipe) {
    /*...*/
  }
  // Given a recipe that's not an instance of ShapedRecipes or ShapedOreRecipe,
  // the code will fall through to adding the recipe to the 'toRemove' list.
  // To fix, the code should include this else condition:
  // [[[
  else {
    continue;
  }
  // ]]]
} else {
  /*...*/
}
```

The same bug occurs in both `public int removeShaped(IIngredient output, IIngredient[][] ingredients)` and `public int removeShapeless(IIngredient output, IIngredient[] ingredients, boolean wildcard)`.

**Comment by stanhebben** [comment]
Thanks for your detailed report, I will fix this shortly using your suggestion :)

**Comment by omglolbah** [comment]
Was a fix for this ever added to the codebase?
I did a little poking into the commits and could not see anything, but I'm sleep deprived ;)

Ran into the issue using 3.0.10B in Infinty Expert where we added PRojectE. Attempting to remove the smelting recipes with a removeshapeless using wildcards hosed the recipe registry.

If there is anything I can do to help on this let me know!
