### ISSUE TITLE
some recipes don't work after being added

### ISSUE THREAD

**Issue by kotoroshinoto** [stanhebben/MineTweaker3#256]
Trying to add recipe for ArchimedesShipsPlus:floater and the scripts complete without complaining, but I cannot get a crafting table to show the  recipe for the floater with the correct items.

**Comment by jaredlll08** [comment]
More information is needed, what does the crafting table show? What is your script? can we see your minetweaker.log file please.

**Comment by kotoroshinoto** [comment]
relevant lines from the script:

val woodLog = <ore:woodLog>;
val rubber = <ore:itemRubber>;
val wool = <ore:blockWool>;
val floater = <ArchimedesShipsPlus:floater>;
recipes.remove(floater);
recipes.addShapeless(<ArchimedesShipsPlus:floater> * 1 , [woodLog, rubber, wool]);

it removes the old recipe properly, but the replacement recipe doesn't show up

when I put the items in the crafting grid, it doesn't show any output.

I noted these lines in the minetweaker.log file: 
INFO: Adding recipe for Floater
INFO: Adding recipe for Floater

the only line that isn't an INFO line is at the very top: ERROR: system: AutoSpawner is already defined in that package, and I am pretty sure that isn't related to this recipe modification

**Comment by kotoroshinoto** [comment]
I am also modifying the recipes for archimedes's colored balloon blocks,but those edits are working with no problems. I'm not sure why this particular one isn't working.

**Comment by jaredlll08** [comment]
See if the recipe shows after a /mt reload

**Comment by kotoroshinoto** [comment]
it didn't. That was why I came here.

**Comment by Voidi** [comment]
https://github.com/jaredlll08/ModTweaker2/blob/master/contributing.md

**Comment by kotoroshinoto** [comment]
The thing is I don't HAVE any indication of failure in the logs, the only indication of failure is the lack of a functioning recipe. The logs claim that the recipe has been added, and then it doesn't work for some reason. I will try to find time to test it in isolation, but the recipes that I am trying to use involve the items from the other mods. (all the other woods, rubbers etc). I can't imagine that any mod would be messing with archimedes ships crafting recipe on the vanilla crafting bench ONLY after I touch it with minetweaker. (by default it uses all-vanilla items), and other mods don't really pay attention to its presence as it isn't one that interfaces or provides an API for tech mods to work with.

I do have a custom modpack, which my friends and I have been maintaining on a private git server. If you would like to access it to aid in bugtesting, thats ok by me.

**Comment by kotoroshinoto** [comment]
http://www.curse.com/mc-mods/minecraft/228029-archimedes-ships-plus-flying-houses-flying-houses

as there have been different authors with different editions of archimedes, here is the one I am using.

**Comment by Voidi** [comment]
Please simply follow the instructions. We need all logs(Minetweaker- client and server log).
and your ZenScript.

This could be some type of duplicate declarartion `ERROR: system: AutoSpawner` in your ZenScript.
So please your complete ZenScript.

**Comment by kotoroshinoto** [comment]
https://gist.github.com/kotoroshinoto/1489f85473ff8250c25c

**Comment by kotoroshinoto** [comment]
working on obtaining the logs

**Comment by Voidi** [comment]
the OreDictionary Name for Wood is logWood not woodLog.
Please check this.

Maybe we should think about logging if a OreDict name could not resolved @jaredlll08 ?

Btw @kotoroshinoto what program/editor do you use to write the scripts?

**Comment by kotoroshinoto** [comment]
notepad++ windows side and gedit linux side

silly error that. went right under my nose

**Comment by kotoroshinoto** [comment]
perhaps a function to explicitly request an oredict that you expect to exist already vs one that creates a new one (so as to separate a case deserving a warning from one where you are deliberately creating an oredict?)

**Comment by Voidi** [comment]
I think simply logging if an empty oredict is used would do.
And i thought it would good if we add support for IDE/Editors for that(I#m currently working on a sublimetext plugin for that).

**Comment by kotoroshinoto** [comment]
that would probably work, I imagine the forge dicts are the only case where the ZS files automatically plug in the requested entry if it doesn't already exist, it was in that vein of thinking that I was suggesting to make the difference in behavior more obvious. (if <ore:something> has unique behavior, perhaps putting it in a function or changing it to use double anglebrackets like <<ore:something>>, or somehow making it separate so you can grant it that unique behavior in a completely obvious way. If you did it via functions, you could always provide an alternative optional input or different named function that should speak up about a missing entry and indicate an error.

**Comment by jaredlll08** [comment]
We can't really produce an error because in theory, you could add a recipe that uses the oredict "xyzxyz", then,  lines down, you could add items to "xyzxyz", and it will work with those items that you added, so we can't tell if an oredict is empty

**Comment by stanhebben** [comment]
Actually you could. If we keep a record of which oredict entries were requested and after execution has finished, throw up a warning for the ones that stayed empty.

**Comment by kotoroshinoto** [comment]
I was thinking there could be a modification to the oredict request somehow that indicates you are expecting to be given one that already exists, or as stan mentioned, it could queue it for non-empty checking at the end.

**Comment by kotoroshinoto** [comment]
If it is just a warning, then you could do it for any created / requested entries, it could be useful for discovering silly errors or even bugs in mods ;p.
