### ISSUE TITLE
3 way oredict mirror?

### ISSUE THREAD

**Issue by kotoroshinoto** [stanhebben/MineTweaker3#257]
2 of my mods add bauxite and register them as ore:aluminum
galacticraft adds its own aluminum and registers it under 3 oredict names

how would I go about making sure all of these items are reflected in oredict as same across all 3 of these oredict entries (can I use addAll and mirror to do this?

I am running into a situation where after reloads mt reload begins failing and clients eventually can't join.

**Comment by kotoroshinoto** [comment]
there was a typo in my zs script ,but the connection issue was something that did happen a few times, might be worth looking into.

on a related note, is it possible to erase an oredict entry?

**Comment by Blue64** [comment]
Yes, in the case of iron ingot in ingotGold it would read:
```
<ore:ingotGold>.remove(<minecraft:iron_ingot>)
``` 
This information is referenced, but not mentioned on the [Ore Dictionary Tutorial Page](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Ore_Dictionary) in the [wiki](http://minetweaker3.powerofbytes.com).

**Comment by kotoroshinoto** [comment]
I meant, if you removed all entries for <ore:ingotGold> would it stop existing in the registry or simply become empty?

**Comment by Blue64** [comment]
I would need to test that actually. It also depends on how you check the oreDict, as there's a few different ways across various mods. I'm personally using Ender IO, but I heard Flaxbeard's Steam Power uses a different method.

**Comment by jaredlll08** [comment]
It should become empty
