### ISSUE TITLE
seems minetweaker 3 can only be loaded once on the same system (a second instance will crash mt3 for that instance alone)

### ISSUE THREAD

**Issue by trollworkout** [stanhebben/MineTweaker3#262]
unlike regular mods, mt3 cannot be loaded a second time on a new instance of minecraft. so far this mod is the only mod with this behaviour.

what i did was i opened minecraft normally . started a new game. open LAN
then i modify my displayedName from profile json file to something bogus. turn off internet. do open -n /Applications/Minecraft.app open a new instance (i am on a MAC).  play offline. join my other instance's game. works fine and i can move around on both instances. but minetweaker 3 will crash on the second loaded instance but will work fine on first (serving) instance.

any reason this  is happening? is this intended behaviour. i'd assume it should work same on all instances. all other mods do this.  i have never encountered this problem with any other mods and again so far this is the only mod with this behaviour.

the crashes are VERY strange. seems mt3 on second instance of minecraft cannot see any game items and simply says ERROR that item doesn't exist. but the items do exist is just any subsequent loating mt3 on any subsequent instances of minecraft cannot see any game items.

**Comment by jaredlll08** [comment]
LAN is broken with mods.

This is also destined to fail because of the minetweaker.log file, that will constantly be rewriting itself, same goes for the forge log. 

Just don't use LAN.
