### ISSUE TITLE
Dont work Refinery from Buildcraft

### ISSUE THREAD

**Issue by Tsyklop** [stanhebben/MineTweaker3#264]
mods.buildcraft.Refinery.removeRecipe(<liquid:fuel>);

Error in chat: 
`[Client thread/INFO]: [CHAT] ERROR: Recipes - Thermal Expansion - Fluid Transoser.zs:17 > No such static member in mods.buildcraft.Refinery: removeRecipe

[Client thread/INFO]: [CHAT] ERROR: Error executing Recipes - Thermal Expansion - Fluid Transoser.zs: minetweaker/api/liquid/ILiquidStackAny`

MiteTweaker log: http://pastebin.com/iFXJjFtX

**Comment by Yulife** [comment]
BC support is no longer in MT itself but in Buildcraft Compat. The method isn't called removeRecipe yet so please just use "remove".

**Comment by Tsyklop** [comment]
@Yulife Dont work...AddRecipe working, removeRecipe and remove dont working

**Comment by Yulife** [comment]
Well then wait for a fix.
