### ISSUE TITLE
Minetweaker 3 Crashes during start

### ISSUE THREAD

**Issue by Antonwinther99** [stanhebben/MineTweaker3#266]
This is the mods i use & also the cause of the crash: [14:09:40] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[14:09:40] [Server thread/ERROR] [FML/]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (Stranded.jar) 
	UC	Forge{10.13.4.1517} [Minecraft Forge] (Stranded.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UC	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126-nosplode.jar) 
	UC	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
	UC	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UC	BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.4].jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UC	Botania{r1.7-223} [Botania] (Botania r1.7-223.jar) 
	UC	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UC	BuildCraft|Core{7.1.9} [BuildCraft] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Builders{7.1.9} [BC Builders] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Transport{7.1.9} [BC Transport] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Energy{7.1.9} [BC Energy] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Silicon{7.1.9} [BC Silicon] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Robotics{7.1.9} [BC Robotics] (buildcraft-7.1.9.jar) 
	UC	BuildCraft|Factory{7.1.9} [BC Factory] (buildcraft-7.1.9.jar) 
	UC	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UC	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UC	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UC	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UC	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
	UC	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UC	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UC	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) 
	UC	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UC	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UC	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
	UC	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
	UC	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) 
	UC	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
	UC	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
	UC	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
	UC	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
	UC	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UC	headcrumbs{1.6.2} [Headcrumbs] (Headcrumbs-1.6.2.jar) 
	UC	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UC	HardcoreQuesting{The Journey (4.3.0)} [Hardcore Questing Mode] (HQM-The Journey (4.3.0).jar) 
	UC	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (inventorytweaks-1.58-147.jar) 
	UC	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UC	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3-RFNerf.jar) 
	UC	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UC	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) 
	UE	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-Dev-Full-1.7.10-3.0.10B.jar) 
	UE	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UC	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UC	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) 
	UC	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) 
	UC	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UC	RefinedRelocation{1.1.4} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.4.jar) 
	UC	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UC	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
	UC	Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) 
	UC	Schematica{1.7.5.git} [Schematica] (Schematica-1.7.10-1.7.5-GenHack3.jar) 
	UC	Shatter{4.0.0} [Shatter] (Shatter-4.0.0.jar) 
	UC	SpecialMobs{3.2.0} [Special Mobs] (SpecialMobs-1.7.10-3.2.0.jar) 
	UC	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UC	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UC	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UC	StorageDrawers{1.7.10-1.5.3} [Storage Drawers] (StorageDrawers-1.7.10-1.5.3.jar) 
	UC	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
	UC	playerzombiemod{v1} [Tainted Players] (TaintedPlayers-v1-1.7.10.jar) 
	UC	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UC	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UC	TML{3.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) 
	UC	TooMuchRain{%VERSION%} [TooMuchRain] (TooMuchRain-1.7.2-1.0.0-b5-universal.jar) 
	UC	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-test41.jar) 
	UC	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UC	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UC	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UC	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UC	IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.DEV.0edeedd.jar) 
[14:09:40] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[14:09:40] [Server thread/ERROR] [FML/]: Caught exception from MineTweaker3
java.lang.NoSuchMethodError: net.minecraft.item.crafting.CraftingManager.getInstance()Lnet/minecraft/item/crafting/CraftingManager;
	at minetweaker.mc1710.recipes.MCRecipeManager.<init>(MCRecipeManager.java:41) ~[MCRecipeManager.class:?]
	at minetweaker.mc1710.MineTweakerMod.<init>(MineTweakerMod.java:96) ~[MineTweakerMod.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_60]
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173) ~[ILanguageAdapter$JavaAdapter.class:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Antonwinther99** [comment]
Update: only crashes when started up with the MineTweaker3-Dev-Full-1.7.10-3.0.10B version, mod loads successfully when using latest recommended build.

**Comment by jaredlll08** [comment]
Yes... The dev version is only for developers, never meant to be used in a
proper environment.

**Comment by Antonwinther99** [comment]
A'ight.

**Comment by Antonwinther99** [comment]
Crashes without mods too though.

**Comment by jaredlll08** [comment]
It. Does. Not. Matter. Don't. Use. Dev. Versions. Unless. In. A.
Development. Environment.

**Comment by Antonwinther99** [comment]
Is modtweaker able to tweak iguanas tinker tweaks?

**Comment by jaredlll08** [comment]
Ok lets start...
This isn't the ModTweaker Repo, this is the MineTweaker repo.
This issue has nothing to do with ModTweaker OR Iguanas Tinker Tweaks/
You could have looked at the source code in the ModTweaker repo and just by looking at the folder names, you could see if it was supported.
You could have looked at the Minetweaker wiki where we host all of our documentation and gotten your answer.

No.

**Comment by Antonwinther99** [comment]
Lol, why so rude?

**Comment by Antonwinther99** [comment]
Shouldn't matter whether this is the right or wrong place to ask questions at, it was a simple yes or no question and you get all pissed off? calm down dude.

**Comment by Yulife** [comment]
I'm not sure if it overrides the tweaks from ITT. :) The best way to see if it works is to test it @Antonwinther99.

**Comment by Antonwinther99** [comment]
The problem is that i don't know how to test it, but thank you for your reply :P

**Comment by Antonwinther99** [comment]
Is there any way to close this issue?

**Comment by jaredlll08** [comment]
@Yulife that isn't what he asked, he was asking if we supported the mod, like actual support, not if our stuff is compatible,

@Antonwinther99 Just giving some information, would save us both time, also no need to spam this repo for modtweaker questions.

**Comment by Antonwinther99** [comment]
Couldn't find the modtweaker page though until now, sorry, didn't mean to be a pain.

**Comment by jaredlll08** [comment]
I should apologize, Just having one of those days where I have no patience for anything, sorry.

**Comment by Antonwinther99** [comment]
It's alright, and once again i am sorry :P

**Comment by Antonwinther99** [comment]
Have a nice day, hehe.
