### ISSUE TITLE
Addition and Removal of Starting Items

### ISSUE THREAD

**Issue by Yulife** [stanhebben/MineTweaker3#267]
This would be a neat addition to the current Minetweaker. An example is that you start a world or join a server for the first time and you get certain types of items (mostly books, sometimes food). It'd great for a modpack maker to configure those to let you start with items that would be sensible for the modpack, for example.

Thanks in advance ~

**Comment by jaredlll08** [comment]
Not possible, it uses events to set the items, there is nothing that we can change about that.

**Comment by stanhebben** [comment]
With a bit of creativity, maybe...? We could register ourselves on those events with a low priority, remove blocked items, add new items?

At least adding new items should be easy.

**Comment by jaredlll08** [comment]
Don't think so, let me show you how they do it

**Comment by jaredlll08** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/armor/player/TPlayerHandler.java#L79-L82
