### ISSUE TITLE
[SUGGESTION] Execute script only if mod is loaded

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#268]
As title says. It would be nice to be able to make a script that will run only if particular mod is loaded. It would help modpack makers with adding optional mods and tweaking their recipes without needing players to manually enable the script (by renaming or putting it into the scripts folder by themselves). Because right now if the script is present but the entries in the script doesnt match any real items/blocks ingame, it will error and it will be shown in chat, making the script looking broken

So if I will have an optional mod A and script A.zs I will add a statement on the beginning of the script IF mod A is loaded then continue.

If mod A is not loaded, it will just read the first line and then skip the rest of the file

If (mod A loaded) Then
    (Script)
 Else
    (nothing/skip)

**Comment by jaredlll08** [comment]
There is already an issue for this, please search for it.
