### ISSUE TITLE
Adding/hiding items in NEI causes all versions of that Item ID to hide on reload.

### ISSUE THREAD

**Issue by fishmealx** [stanhebben/MineTweaker3#271]
The following causes the original rftools:syringeItem to disappear from NEI, replaced by this one with NBT data:
NEI.addEntry(rftools:syringeItem.withTag({level:10, mobName:"Enderdragon"}));

I tried adding:
NEI.addEntry(rftools:syringeItem);
after it, but that just returned he original, overwriting the NBT one.

**Comment by fishmealx** [comment]
I think it's just this:
https://github.com/stanhebben/MineTweaker3/issues/205
My bad.

**Comment by fishmealx** [comment]
Sorry, I'm confused.
So it turns out it reloads all the time on its own, like whenever I join the server. Could reloading of NEI scripts just be stopped altogether?
As it is, if I add, for example, ingredient:7 then join the server causing a reload, ingredient:1, ingredient:7, and all the other damage values for that item will have completely vanished from NEI. This makes the NBT functions of the NEI API not only pointless, but counterproductive.
Is it possible to just leave the NEI API alone until the server restarts or something?

**Comment by cosmicdan** [comment]
I only just discovered this myself. Still a bug. I guess 1.7.10 work is ended, so we're stuffed.

**Comment by jaredlll08** [comment]
"so we're stuffed" not if you update to 1.10.2

**Comment by cosmicdan** [comment]
Am I allowed to fork and bash my keyboard until it works? And redistribute the fixed version in the modpack we're working on (putting a big unofficial stamp all over the place)?

I know NEI itself is a mess of a mod, but our pack still relies on mods that are not updating past 1.7.10 anytime soon.

**Comment by jaredlll08** [comment]
Look, the license says you can, just make sure the mod name is different, but I would prefer you didn't, it just gives a person more reason to stay on an older version when they can update, I understand that your pack may rely on 1.7.10 mods, but when people are creating a new pack, they go with versions that are getting mod updates, so I would prefer the only release versions be 1.10 or 1.11.

But like I said, nothing against it in the license, and I won't hate you forever if you do it, I will only hate you for like a day or two :P

**Comment by cosmicdan** [comment]
Lol fair enough. Well i had a quick look and your code seems fine to mee, looks like it's a bug in NEI if anything (I'm blaming it anyway). I don't think I could be bothered trying to fix that.

Thanks anyway!

**Comment by jaredlll08** [comment]
Yip, that is why it was never fixed in the first place, our code is fine,
but somewhere in the NEI code (which is the blackest of magic) it messes
up.
