### ISSUE TITLE
Items can not be correctly removed from OreDictionary

### ISSUE THREAD

**Issue by oldjunyi** [stanhebben/MineTweaker3#272]
I use these following scripts to remove vanilla dyes from OreDictionary
```javascript
<ore:dye>.remove(<minecraft:dye:*>);
<ore:dyeBlue>.remove(<minecraft:dye:4>); // this is lapis
<ore:dyeGreen>.remove(<minecraft:dye:2>);
<ore:dyeBrown>.remove(<minecraft:dye:3>);
<ore:dyeBlack>.remove(<minecraft:dye:0>);
<ore:dyeWhite>.remove(<minecraft:dye:15>);
```
By using the command "/mt hand" with a lapis gem in hand. The result shows:
```javascript
<minecraft:dye:4>
Is in <ore:gamLapis>
```
The "ore:dye" and "ore:dyeBlue" entries are successfully remove from lapis, everything seems right?

Then I wrote another piece of Java code in a simple Forge mod to check the correctness of this removal:
```java
public static void checkItem(ItemStack stack) { // It is excuted when player right click on a custom block
	if (stack == null) return;
	System.out.println("checking for ItemStack " + stack.getUnlocalizedName() + ":" + stack.getItemDamage());
	int[] ids = OreDictionary.getOreIDs(stack);
	for (int id: ids) {
		String str = OreDictionary.getOreName(id);
		System.out.println("  In OreDict " + str);
	}
}
```
The output in fml-latest.log is:
```
[01:26:08] [Client thread/INFO] [STDOUT/]: [mmintegration.Debugger:checkItem:31]: checking for ItemStack item.dyePowder.blue:4
[01:26:08] [Client thread/INFO] [STDOUT/]: [mmintegration.Debugger:checkItem:35]:   In OreDict gemLapis
[01:26:08] [Client thread/INFO] [STDOUT/]: [mmintegration.Debugger:checkItem:35]:   In OreDict dyeBlue
[01:26:08] [Client thread/INFO] [STDOUT/]: [mmintegration.Debugger:checkItem:35]:   In OreDict dye
```
Sadly, the "ore:dye" and "ore:dyeBlue" are still exist :(

**Comment by Voidi** [comment]
Minetweaker Scripts normally run after when the player join a world, when do you run your java code?
And how are you initialy aware that lapis seems still have this OreDict entrys?

**Comment by oldjunyi** [comment]
Of course I run my code after Minetweaker load all scripts. Since the test code will be triggered when a player interact with a block.

Currently I am working on an addon mod to Flaxbeard's Steam Power. I found the lapis can always dyes the FSP's armor in Engineer Table. After checking the source code, I found the FSP use some code similar to the checkItem() method to check the OreDictionary.

That's why I found this problem.

**Comment by Blue64** [comment]
It could be assumed, but has not yet been asked. Did you test this after trying ```/mt reload``` to verify that it indeed isn't on your end one bit?

**Comment by jaredlll08** [comment]
@oldjunyi can we get an update for what blue suggested please?

**Comment by oldjunyi** [comment]
Sorry for late reply, I will pick it up again and do some tests to find out more clues.
-- 
姜凯 (Kai Jiang)

**Comment by Haggle1996** [comment]
I can confirm that trying to remove items from the ore dictionary does not function. Verified with latest version. Executing a /mt reload does not affect the entries. Example:
```
<ore:oreIronHard>.remove(<HarderOres:ore_iron:15>);
```
However, HarderOres:ore_iron:15 is still in <ore:oreIronHard>

**Comment by jaredlll08** [comment]
I'll take a look at it later

**Comment by jaredlll08** [comment]
I just checked, this works fine, removed the item, in my case iron, using 

```
val iron = <ore:ingotIron>;
iron.remove(<minecraft:iron_ingot>);
```
