### ISSUE TITLE
Class Not Found Exception on startup

### ISSUE THREAD

**Issue by PitchBright** [stanhebben/MineTweaker3#277]
I'm not sure if this is a problem or not, but I thought it'd be worth asking about:

[STDERR/MineTweaker3]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: java.lang.ClassNotFoundException: stanhebben.zenscript.ZenModule

http://pastebin.com/UwTXEhmE

**Comment by Blue64** [comment]
Are you by chance importing in that script? If so, see if those errors are relevant to the import. Mine doesn't have that error at all.

**Comment by PitchBright** [comment]
No imports in that script.

**Comment by Blue64** [comment]
How odd indeed. I have zero ideas then. Perhaps it might be relevant to a parser issue? We'd need to see the script to see if anything isn't recognized by the parser though `(which I might add, is way over my head lol)'

**Comment by PitchBright** [comment]
The error occurs on whichever script loads first, so it's not always the same script. And, the script does take effect fine, and if I didn't notice the server console output, I never would've know there might be an issue. Another modder said he thinks it might be related to his modification loader, and that it has to do with something called "Hibernate", a library or module or something. Not sure. He mentioned it after I posted this issue.

**Comment by Blue64** [comment]
Ah, that could be another part, servers tend to behave differently than single player.

**Comment by jaredlll08** [comment]
Could I please get your scripts

**Comment by jaredlll08** [comment]
It also seems that you have a mod that is editing asm, which could also cause this issue.

https://github.com/TheWeatherPony/Partial-Modification-Loader---Agent
is what I am seeing in the log

**Comment by jaredlll08** [comment]
Considering that we havn't gotten any other issues, I assume it is the ASM added by the mod I linked above

**Comment by PitchBright** [comment]
Yeah sorry for the lack of response… the mod in question that's doing the ASM is being constantly updated, and I haven't had a chance to get the author to sit down and determine if the cause is something he's doing. I've kept this issue at the top of my inbox though, so I definitely haven't forgotten about it.

**Comment by jaredlll08** [comment]
Try remove the mod? And see if it still happens

**Comment by PitchBright** [comment]
PML isn't really a mod. I'm not technically knowledgeable enough to explain it very well... But it sits above forge and wraps asm, I think. I brought it to the author's attention back then, and he thought it probably was something on his side, but never dove into it. I'll remind him, and if he can't figure it out, I'll come look for you on irc or something to see if you have any further thoughts. Sorry to have left the issue open for so long.

**Comment by jaredlll08** [comment]
Heh sorry for not replying, if it messed with ASM a lot, then it can't be
our issue, when classes are changed heavily, it because a mission to
support, and causes crashes
