### ISSUE TITLE
Add feauture for removing items and blocks

### ISSUE THREAD

**Issue by wb9688** [stanhebben/MineTweaker3#281]
It could be handy to remove some broken items and blocks in your modpack...

**Comment by jaredlll08** [comment]
You can't remove items or blocks, it will cause issues with the ID registry.

**Comment by wb9688** [comment]
Why should it cause issues???

**Comment by jaredlll08** [comment]
Because mod A expects there to be block A, but you have removed it from the
game.
Last I checked, the ID registry is in numerical order, if you removed if 8,
when looping, it will still try and do things for block ID 8, causing a
crash and world corruption.
