### ISSUE TITLE
Minetweaker and Forestry crash.

### ISSUE THREAD

**Issue by jsaggers** [stanhebben/MineTweaker3#288]
I receive a crash with minetweaker and the latest version of Forestry which looks like they have changed a few things again.
To do with "forestry/factory/recipes/ISqueezerRecipe" [paste bin here](http://pastebin.com/VxDVfXeU)

[Also here is the latest fml log](http://www.jasonsaggers.id.au/downloads/fml-client-lates-minetweakert.zip)
Forestry version 's 1.7.10-4.2.1.48, 1.7.10-4.2.0.47, 1.7.10-4.1.1.46, 1.7.10-4.1.0.45 all crash with minetweaker.

Version forestry_1.7.10-4.0.11.40 or below works just fine.

**Comment by Voidi** [comment]
1. Wrong Project: Minetweaker Support for Forestry is done by modtweaker
2. there isn't a stable release of Modtweaker for Forestry 4 yet, use dev builds
https://github.com/jaredlll08/ModTweaker2/issues/279

**Comment by jaredlll08** [comment]
Wrong project
