### ISSUE TITLE
[GregTech Support] - Boxing recipes

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#29]
Is there a way on how to add a recipe for Boxing machine, to let it NOT consume the second item?

There are quite few recipes which are using for example "Schematic 3x3" item, which should not be consumed. But when I add a recipe for let's say Compressed Cobblestone (from Extra Utilities) with the Schematic, it is consuming it together with cobblestone.

Boxing.addBoxingRecipe(cobbleCompressed, cobblestone * 9, schematic3x3, 1, 1);

Also I run into little issue with Compressor recipes. Since Gregtech is taking the recipes for the IC2 compressor and using them in its own compressor, its not working when I put more items in the compressor. Again example with Compressed Cobblestone:

Compressor.addRecipe(cobbleCompressed, cobblestone * 9);

I need to put exactly 9 cobblestone to let the machine compress it. If I put there 10 or more at once, it will not process.

**Comment by jaredlll08** [comment]
We no longer add gregtech support, however I suggest you get in contact with @dream-master who creates an addon that adds GT support

**Comment by Dream-Master** [comment]
if you using  "item * 0" the item will not consumed.
