### ISSUE TITLE
Recipes not adding

### ISSUE THREAD

**Issue by LouieK22** [stanhebben/MineTweaker3#290]
I have added some recipes to a modpack, and they don't seem to be registering in game. I am getting no errors.

**Comment by jaredlll08** [comment]
Give us your minetweaker.log please

**Comment by LouieK22** [comment]
https://app.box.com/s/mmhyag38bz3ca1sfidhv33vxy2augg8b
Contains log and scripts.

**Comment by LouieK22** [comment]
Alright, reread through script, new.zs, and found some errors which much break all other lines in that script. You can close now.
