### ISSUE TITLE
Wiki page errors

### ISSUE THREAD

**Issue by Blue64** [stanhebben/MineTweaker3#292]
The [Mariculture page](http://minetweaker3.powerofbytes.com/wiki/Mariculture) either is unclear or has a typo which reads the following:
```
//Casting
//InputStack, OutputFluid
mods.mariculture.Casting.addNuggetRecipe(<liquid:gunpowder> * 16, <minecraft:gunpowder>);
mods.mariculture.Casting.addIngotRecipe(<liquid:gunpowder> * 144, <Mariculture:droplet:6>);
mods.mariculture.Casting.addBlockRecipe(<liquid:gunpowder> * 1296, <minecraft:tnt>);
```
I may not be all that amazing when it comes to the internal structure of how this works, but since when was ```<minecraft:tnt>``` registered under the ```IFluid``` category?

**Comment by Blue64** [comment]
#257 found another problem, the [OreDict Tutorial for 1.7.X](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Ore_Dictionary) is missing information on how to actually REMOVE an OreDict entry, such as:
```
// Direct Ref
<ore:ingotGold>.remove(<minecraft:iron_ingot>);

// OreDict Ref
<ore:ingotGold>.remove(<ore:ingotIron>);

// Var/Val Ref
var IronIngot = <minecraft:iron_ingot>;
<ore:ingotGold>.remove(IronIngot);
```
that's kind of important to have in a tutorial about addition and removal of OreDict entries

**Comment by jaredlll08** [comment]
you should be able to login and create a wiki account now :)

Also this is kinda a Modtweaker repo issue

**Comment by Blue64** [comment]
Login shows up as an available option, but I see no way to create an account that is recognized, it's not recognizing the MediaWiki Account that I created a few weeks ago (which I was taken to when I tried to explore the Login Page)

**Comment by jaredlll08** [comment]
what you need to do is make an account on the forums, then you can use those login details
