### ISSUE TITLE
recipes.removeShapeless() remove shaped recipes

### ISSUE THREAD

**Issue by skydark** [stanhebben/MineTweaker3#294]
### How to reproduce:

``` javascript
recipes.removeShapeless(<minecraft:wool:*>, [<minecraft:wool>], true);
```
### What's the result:

All wool coloring recipes were removed. (expected)
All wool shaped recipes(like 4 strings -> wool) were removed. (_NOT_ expected)
It will also happen if use `recipes.removeShaped(<...>, [...])`(All shapeless recipes with the same output will be removed).
It will not happen if use `recipes.removeShapeless(<...>)` or `recipes.removeShaped(<...>)`.
### How to fix:

At https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Main/src/main/java/minetweaker/mc1710/recipes/MCRecipeManager.java#L210 ,

``` java
if (ingredients != null) {
    if (recipe instanceof ShapelessRecipes) {
        // ...
    } else if (recipe instanceof ShapelessOreRecipe) {
        // ...
    }
    // else { continue; }   // <- missing a else-continue branch here!
} else {
    // ...
}
toRemove.add(recipe);
removeIndex.add(i);
```

For removeShaped, see line 144.
For 1.8, see:
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC18-Main/src/main/java/minetweaker/mc18/recipes/MCRecipeManager.java

**Comment by jaredlll08** [comment]
1.8 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
