### ISSUE TITLE
recipes.remove*() remove irrelative recipes

### ISSUE THREAD

**Issue by skydark** [stanhebben/MineTweaker3#295]
### How to reproduce:

``` javascript
recipes.removeShaped(<minecraft:iron_block>, [[<minecraft:book>, <minecraft:book>, <minecraft:book>],
[<minecraft:book>, <minecraft:book>, <minecraft:book>],
[<minecraft:book>, <minecraft:book>, <minecraft:book>]]);
recipes.removeShaped(<minecraft:bookshelf>, [[<minecraft:book>, <minecraft:book>, <minecraft:book>],
[<minecraft:book>, <minecraft:book>, <minecraft:book>],
[<minecraft:book>, <minecraft:book>, <minecraft:book>]]);
recipes.removeShapeless(<minecraft:wool:15>, [<minecraft:dirt>, <minecraft:wool>]);
```
### What's the result:

All bookshelf/iron block/black wool recipes were removed. (_NOT_ expected)
### How to fix:

At https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Main/src/main/java/minetweaker/mc1710/recipes/MCRecipeManager.java#L406 ,

``` java
private static boolean matches(Object input, IIngredient ingredient) {
    if ((input == null) != (ingredient == null)) {
        return false;
    } else if (ingredient != null) {
        if (input instanceof ItemStack) {
            // ...
        } else if (input instanceof String) {
            // ...
            if (!ingredient.contains(getOreDict((String) input))) {
                return false;
            }
        }
        // else if (input instanceof List) {   // <- need to process this branch!
        /* see https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java#L106  */
        // } else {...}
    }
    return true;
}
```

For 1.8, see:
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC18-Main/src/main/java/minetweaker/mc18/recipes/MCRecipeManager.java

**Comment by Blue64** [comment]
Are you sure this also affects shapeless? Title says remove* meaning shaped & shapeless both, but I only see shaped examples.

**Comment by Blue64** [comment]
https://github.com/stanhebben/MineTweaker3/issues/294 this explained it in example better

**Comment by skydark** [comment]
OK, I added a shapeless example.

**Comment by jaredlll08** [comment]
1.8 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
