### ISSUE TITLE
Items with different tags are identical as the input in any recipes.

### ISSUE THREAD

**Issue by desertir** [stanhebben/MineTweaker3#300]
Railcraft's tracks identified by tags. But in special cases they also have metha numbers.
I want write recipes for junction/switch/wye tracks from theirs basic (direct) tracks.
So Reinforsed Track and Electric Track no have methadata (only diff tags) and they conflict together as input items.
Recipes look like this (GT's Assembler):
```
//// Reinforsed
var reinforcedTrack = <Railcraft:track>.withTag({track: "railcraft:track.reinforced"});
var reinforcedJuncTrack = <Railcraft:track:764>.withTag({track: "railcraft:track.reinforced.junction"});
var reinforcedSwitchTrack = <Railcraft:track>.withTag({track: "railcraft:track.reinforced.switch"});
var reinforcedWyeTrack = <Railcraft:track>.withTag({track: "railcraft:track.reinforced.wye"});
var reinforcedBoostTrack = <Railcraft:track>.withTag({track: "railcraft:track.reinforced.boost"});

//// Electric
var electricTrack = <Railcraft:track>.withTag({track: "railcraft:track.electric"});
var electricJuncTrack = <Railcraft:track>.withTag({track: "railcraft:track.electric.junction"});
var electricSwitchTrack = <Railcraft:track:10488>.withTag({track: "railcraft:track.electric.switch"});
var electricWyeTrack = <Railcraft:track>.withTag({track: "railcraft:track.electric.wye"});
...
Assembler.addRecipe(reinforcedJuncTrack, reinforcedTrack * 2, gtIntCircuit01 * 0, 100, 16);
Assembler.addRecipe(reinforcedSwitchTrack, reinforcedTrack * 2, gtIntCircuit02 * 0, 100, 16);
Assembler.addRecipe(reinforcedWyeTrack, reinforcedTrack * 2, gtIntCircuit03 * 0, 100, 16);
Assembler.addRecipe(reinforcedBoostTrack, reinforcedTrack * 2, goldFineWire * 2, moltenRedstone * 144, 100, 16);
...
Assembler.addRecipe(electricJuncTrack, electricTrack * 2, gtIntCircuit01 * 0, 100, 16);
Assembler.addRecipe(electricSwitchTrack, electricTrack * 2, gtIntCircuit02 * 0, 100, 16);
Assembler.addRecipe(electricWyeTrack, electricTrack * 2, gtIntCircuit03 * 0, 100, 16);
```
As a result, in an assembler I got reinforced typed tracks from the electric track because theirs recipes are the first in the script.
No problem with Wooden/H.S. tracks because they have methadata numbers.
```
var woodenTrack = <Railcraft:track:736>.withTag({track: "railcraft:track.slow"});
...
var hsTrack = <Railcraft:track:816>.withTag({track: "railcraft:track.speed"});
```
As well as if to use items only with tags like the output - looks good.
Please, can you tell me how fix or hack this issue?
PS: I'm 300'th :)

**Comment by desertir** [comment]
Forgot about versions:
MineTweaker3-1.7.10-3.0.10B
ModTweaker2-0.9.5
Railcraft_1.7.10-9.8.0.0
gregtech-5.09.19
...
Arrrgh... maybe is it ModTweaker issue? Sorry if it's true.

**Comment by Voidi** [comment]
Could you test this with a vanilla crafting table recipe? if this works with the same items, then there might be a Problem with the Minetweaker Support for Gregtech(not be compare the NBT Data of inputs)
Minetweaker Support for Gregtech is not done by Modtweaker, instead https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon

@Dream-Master

**Comment by jaredlll08** [comment]
There is also no '''.''' Between the item and the withTag, like,
'''<minecraft:dirt>.withTag'''

**Comment by desertir** [comment]
Oh, guys thanx for fast comments.
@Voidi no matter 'where' I create recipes. All tracks (see screens) without meta can be used in the recipe below (pay attention - the switch track has metadata)
```
recipes.addShaped(electricSwitchTrack, [
	[null, electricTrack, null],
 	[electricTrack, null, electricTrack],
	[null, electricTrack, null]]);
```
![image](https://cloud.githubusercontent.com/assets/10061582/12267862/feaf7354-b96b-11e5-9ee7-1213fd332d11.png)
![image](https://cloud.githubusercontent.com/assets/10061582/12267874/07276bfe-b96c-11e5-8ef7-3e25ac3d7da3.png)
![image](https://cloud.githubusercontent.com/assets/10061582/12267891/149f71f0-b96c-11e5-8d48-68e847556778.png)
etc.

But new fact - if the input and the output both are only tagged items (without meta f.ex. electricTrack -> electricJuncTrack) such recipe not works at all :/
```
recipes.addShaped(electricJuncTrack, [
	[null, electricTrack, null],
 	[electricTrack, null, electricTrack],
	[null, electricTrack, null]]);
```
![image](https://cloud.githubusercontent.com/assets/10061582/12267945/6803f2b2-b96c-11e5-917b-78778ee022cd.png)
what.a.hell

@jaredlll08 where I fogot a dot? Or do you mean something else?

Like a conclusion: I can use tag-item in recipes only like the output. Sadly...
PS: metHa, lol, you didn't see this :)

**Comment by PrincessRTFM** [comment]
Aren't input items supposed to use `.onlyWithTag()` instead? I though `.withTag()` was for outputs...

**Comment by Voidi** [comment]
@PrincessRTFM @desertir ey yes to have input conditions *for vanilla crafting mechanics* you must use `onlyWithTag()`
this may a problem how GregTech checks for if recipe matches

**Comment by desertir** [comment]
OMG, how I missed `onlyWithTag()` method? Boob :/ I am sorry for my nescience.
So, `onlyWithTag` returns an instance of `IIngredient` (`IngredientCondition` I think) but `addRecipe` for the Assembler takes `IItemStack` params.
I tried get a first item somehow... no results: 'Not supported yet' or 'Not yet implemented'.
Also for regular recipes it works. Practically. But something wrong is happening when I see the recipe (R-button) of the Reinforced Junction Track.
```
var reinforcedTrackInput = <Railcraft:track>.onlyWithTag({track: "railcraft:track.reinforced"});

recipes.addShaped(reinforcedJuncTrack, [
[null, reinforcedTrackInput, null],
[reinforcedTrackInput, null, reinforcedTrackInput],
[null, reinforcedTrackInput, null]]);
```
![image](https://cloud.githubusercontent.com/assets/10061582/12298584/adabceca-ba34-11e5-86e6-cd27fd0014dd.png)

So we decided that basic tracks are no will be used in recipes. Maybe this issue has a solution but it's no matter for me.
Thanx again!

**Comment by Voidi** [comment]
The wrong display name in NEI: this shouln't be wrong. i don't know maybe there is something wrong with NEI? I know other cases where it didn't show all recipes with different NBT data.

For the Assembler recipe function: there is nothing we can do at Minetweaker, the mods implenting the support has to do that. Most of them don't an can't do that.

**Comment by jaredlll08** [comment]
Ok, well I fixed .getFirstItem, so that should work now
