### ISSUE TITLE
[Request] log settings to not write error details

### ISSUE THREAD

**Issue by karakufire** [stanhebben/MineTweaker3#304]
presently, when fatal script error cause, too many lines written to chat and infect chat log.

**Comment by jaredlll08** [comment]
Yeah...  Those lines are there to tell you to fix them.

**Comment by karakufire** [comment]
Are byte codes useful to fix script?

**Comment by jaredlll08** [comment]
Pardon me?

**Comment by Voidi** [comment]
@jaredlll08 you should more use Minetweaker itself. ;)
Yes depending on the error a lot of gibberish error messages printet to stream.
First we should identify which error types are present.

**Comment by Blue64** [comment]
Lol yea, some errors are just speaking Assembly at us lol I don't speak nor read Assembly ByteCode ```:P``` I figured that out while trying to get access to ```<fluid:Life Essence>``` (which I never did)

**Comment by jaredlll08** [comment]
huh never had that, never had time to actually use minetweaker extensively

**Comment by Blue64** [comment]
If you bracket ```<fluid:Life Essence>``` wrong you'll get this result, amongst others, though I don't think any of them actually mentioned an invalid Bracket Type as their error.

**Comment by jaredlll08** [comment]
Ok, well, so I can't reproduce, but if it was caused by a space in a fluid name, I fixed it so that fluid names can't contain spaces, so `<fluid:LifeEssence>` will work

**Comment by jaredlll08** [comment]
Also why would we disable things that help us fix issues?
