### ISSUE TITLE
[Feature Request] Add text pages to NEI

### ISSUE THREAD

**Issue by dexman545** [stanhebben/MineTweaker3#307]
Requesting that the ability to add text pages to NEI for items (similar to what extra utilities does) to provide users of modpacks with information about an item that is to large to fit in a tolltip

**Comment by Blue64** [comment]
:+1: this would also allow Personal Notes, and Lore additions, without increasing the File Size of the Item's ```MetaData``` (AE2 for example had a crash when Network Compressed Packet Size exceeded 4MB, and with items like the ```ExtraUtilities``` ```Bag of Holding```, or the various Books (```TiCon```, ```BloodMagic```, etc.), which stores all of it's contents within it's ```MetaData```, this can easily offer a complete work-around for even the ```IGW Mod``` when done correctly! (powerful!)

**Comment by PrincessRTFM** [comment]
I'd love to see this, but it sounds like it'd be rather difficult, assuming NEI even allows such things. I haven't looked into the inner workings of NEI, so I don't know if its handlers will allow dynamic changes like this.

**Comment by jaredlll08** [comment]
Hmm,  it *may* be possible,  however,  1.7 and 1.8 uses different mods,
1.8 uses jei,  so it may not be possible there,  or I would just need to
rewrite it

**Comment by PrincessRTFM** [comment]
From what I hear (I still play with and code for 1.7.10) JEI is actually easier to work with than NEI. I know even less about JEI though, so such things may not even be possible at all as it currently stands.

**Comment by Blue64** [comment]
Mods can add the pages somehow, it shouldn't be impossible via MineTweaker+NEI. Most mods in 1.8 are doing complete overhauls to update their API & Code, usually making things easier to access and perform, this is the usual path any kind of progressive Code normally follows, BloodMagic & JEI are not exceptions.

I would love to see this wonderful feature in 1.7.10 if possible.

**Comment by PrincessRTFM** [comment]
I mean, did ExU have to provide custom textures as fake backgrounds and not put anything on the "foreground" to make its info pages? Cause that might complicate things.

**Comment by jaredlll08** [comment]
I am not 100% sure how exu did it, all I know is that nei api is the worst api to deal with

**Comment by Blue64** [comment]
At least it's been done before and we can study that example.

**Comment by Yulife** [comment]
You still would do this for 1.7.10? Tbh just go for 1.8.9 like most other mods and go for JEI.

**Comment by VariableVixen** [comment]
Some people (myself included) are still playing 1.7.10 until more mods update. I have a modpack with 250+ mods in it, it'll take some time for them all to update.

**Comment by Yulife** [comment]
But 1.7.10 is pretty much dead modding (not playing) wise so them effort to do some tedious NEI stuff that probably won't be used (JEI) in 1.8.9 is not worth it.

**Comment by Shahelion** [comment]
@Yulife, I'd have to disagree. 1.7.10 is still a major version, and lots of people still use it.

**Comment by Voidi** [comment]
@Zsashas  May sound rude, but it doesn't matter how many persons use a version.
Determining is what developers treat as active Version (which is for most 1.9).

**Comment by jaredlll08** [comment]
Look, yes 1.7 is still a major version, however, I would not call it a major DEV version:
http://www.blamejared.com/content/2016-07-07_18-38-40.png

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
