### ISSUE TITLE
My Server doesn't start up and MineTweaker seems to be the problem

### ISSUE THREAD

**Issue by Mellow1000** [stanhebben/MineTweaker3#309]
I have a crundee craft server and tried updating it because of the new update but everytime I run the server I get this error. http://pastebin.com/jRUxUUcT
Minetweaker seems to be the problem but when I disable it, it doesn't seem to work.

**Comment by jaredlll08** [comment]
Before I even get to the actual issue, which is not our fault btw,  please
can you explain how,  when you remove the mod,  and it crashes,  it is our
fault? Think of it like this,  if you buy a  microwave,  and then you start
getting bad cellphone signal,  but then remove the microwave and still get
bad signal, is it the microwaves fault? (the answer is no). Now onto your
actual issue, that is an asm issue, meaning that some mod is changing Forge
or another mod, unfortunately, it is impossible to tell which mod without
eliminating all the mods one by one.  You say that you just updated,  my
guess is that when you updated,  you probably forgot to update Forge, or
the crudee craft dev did no testing. Either way,  this issue has nothing to
do with us,  some mod is using outdated mappings for their asm,  causing us
to crash,  and from the sounds of it,  other mods (from when you removed
minetweaker and it still crashed)

**Comment by Mellow1000** [comment]
Ok, it was fixed but when I read the report the only issue seems to be minetweaker

**Comment by jaredlll08** [comment]
Yes, for this crash, minetweaker was the 'cause', or well a better word would be scape goat.

**Comment by UndeadZeratul** [comment]
Happened to be in the wrong place at the wrong time?

**Comment by jaredlll08** [comment]
It is like how in school,  if the person next to you is talking you get
scolded.
