### ISSUE TITLE
Fluid properties in 1.7.10

### ISSUE THREAD

**Issue by parcel31u** [stanhebben/MineTweaker3#313]
Fluids have state, temperature, luminosity, density, and viscosity.

**Comment by PrincessRTFM** [comment]
Is it even possible to change those externally, without ASM?

**Comment by jaredlll08** [comment]
Pretty sure

**Comment by Blue64** [comment]
should be possible. I would love to tinker with the various temperatures of the fluids in my worlds lol

**Comment by jaredlll08** [comment]
So apparently this is already added, however it doesn't work, I have no idea on how to fix it, as it is coded perfectly and should work in theory. So this will unfortunately not be happening ;(
