### ISSUE TITLE
[Request] 1.8.9 Update

### ISSUE THREAD

**Issue by jules552** [stanhebben/MineTweaker3#314]
Hi,

I love this mod and i would like to use it in version 1.8.9,
Can you update to 1.8.9 please?

Thank you for the mod :)

**Comment by Voidi** [comment]
Stan has not dropped the Mod but seems to have a lot of other things to do.
While waiting for the official release jaredlll has an unofficial one for 1.8.9 : http://minecraft.curseforge.com/projects/crafttweaker-customized-mineweaker3/

**Comment by jules552** [comment]
Okay, a big thanks for your fast answer :)
