### ISSUE TITLE
Wrong class name for expansion by IC2 module

### ISSUE THREAD

**Issue by Techlone** [stanhebben/MineTweaker3#315]
Holy crap, I found it!
After a couple hours of debugging of everything I finally saw that the Zen class name [here](https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Mod-IC2/src/main/java/minetweaker/mods/ic2/expand/ItemExpansion.java#L20) is wrong T_T Must be `minetweaker.item.IItemStack`. Phew... I'm tired

**Comment by Techlone** [comment]
PIng somebody...

**Comment by jaredlll08** [comment]
You could have just made a pr...

**Comment by Techlone** [comment]
Uuuh, okay...
