### ISSUE TITLE
[Suggestion] Change fishing rod drops

### ISSUE THREAD

**Issue by PrincessRTFM** [stanhebben/MineTweaker3#316]
In 1.7, Minecraft fishing was overhauled, and assorted "junk" items became obtainable. Would it be possible to change the items that can be caught? If so, could items be weighted and linked to enchantments, so that they are more or less likely with Lure or Luck Of The Sea?

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
