### ISSUE TITLE
can i make a Minetweaker Crafting repice That needs a Portable Tank(thermal expansion) fill with XXXX fluid? instead of a empty one

### ISSUE THREAD

**Issue by mariodk** [stanhebben/MineTweaker3#317]
Hey im trying to make a repice like this: 
http://i.imgur.com/1YH9QId.png
 for a Modpack im making
where you needing a portable Tank(thermal expansion) fill with Matter plamsa(Matteroverdrive) to craft magical crops (higher tier crops needs higher tier portable tank fill with plamsa)
but when i have made the repice the repice just needing a empty portable tank instead of one Fill with Plamsa(or other fluid) like here: 
http://i.imgur.com/EDsNXNb.png
so wanna know how i can make this in minetweaker/modtweaker (i know how to make script abit for minetweak but still new to it only using minetweaker repice maker for make it easier for myself)

**Comment by mariodk** [comment]
i kinda found it out:
ThermalExpansion:Tank:1.onlyWithTag({Fluid: {FluidName: "matter_plasma", Amount:8000}}).giveBack(ThermalExpansion:Tank:1)

it works but wont show in NEI
in NEI it shows this repice as a Empty portable Tank: (but wont craft if putting empty tank in there only work with full one and that is perfect)
so if not possible to show it as a Full tank
is it possible to add a Small text or something for a Repice that say Full This Tank up with Matter Plasma(Matter overdrive) ? via minetweaker/modtweaker

also it crashes if using auto crafting tables(like machines)
but not having a Full portable tank in that auto crafter

**Comment by Techlone** [comment]
The same problem with Universal Fluid cell (IC2). Works but not show in NEI.
Maybe NEI bug?

**Comment by mariodk** [comment]
i dont think it
since i have seen repices in NEI
where it needs stuff like this and shows it but repice not via minetweaker but via the mod itself

**Comment by AnrDaemon** [comment]
Recipes - regular crafting recipes? More likely you've seen modded recipes, and the mod itself handles them. So, of course, they are correct.
the reason NEI can't show recipe is probably because it can't convert your partial item description to a full blown ItemStack. I would consider yourself lucky that it shows anything at all and doesn't crash.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
