### ISSUE TITLE
Minetweaker doesn't load recipes upon joining world (SP, MP)

### ISSUE THREAD

**Issue by AlexanderBulanov** [stanhebben/MineTweaker3#319]
I have added many recipes for different items in order to increase unity between mods. However, upon joining world be it singleplayer or multiplayer, the recipes don't show up. After executing "/mt reload" command, the recipes start showing up in NEI.

EDIT:
Forge version 10.13.4.1614
MineTweaker3 3.0.10B

**Comment by notfood** [comment]
Same thing here. Didn't happen in previous forge. I resorted to adding a job to run /mt reload after server has started.
Forge version 10.13.4.1614
MineTweaker3 3.0.10B

**Comment by DaNeo61** [comment]
Same problem with
Forge version 10.13.4.1614
MineTweaker3 3.0.10B
FTBLib 1.7.10-1.0.17.4

**Comment by jaredlll08** [comment]
Can someone pass me their minetweaker log and the game log please

**Comment by AlexanderBulanov** [comment]
Here's my minetweaker.log
http://pastebin.com/zTQx1tfh
And here's my main game log (it's 2.71MB, had to use Mediafire to host it)
https://www.mediafire.com/?99b2sikfkbap5xc

**Comment by jaredlll08** [comment]
Ok do me a favor please, at the beginning of your script, put a
print("start") and the end, put print("end")
This way I can see where you do the reload

**Comment by AlexanderBulanov** [comment]
Updated minetweaker.log
http://pastebin.com/spRg4wqb
Updated main game log
http://www.mediafire.com/download/n83huvxuqqtdud9/fml-client-latest.log

**Comment by DaNeo61** [comment]
I tried it now with downgrade forge and sortend mods thats was to new for Forge 1558 i still have the issue that the client not getting the Recipes from the server here is my last Log and minetweaker log

http://fastdl.hbs-gaming.net/minecraft/logs.zip

**Comment by jaredlll08** [comment]
Wait, stupid question, but the scripts are on both client and server right?
With the exact same scripts

**Comment by notfood** [comment]
minetweaker.log
http://pastebin.com/DaKYSdjc

fml-server-latest.log
http://www.mediafire.com/download/g2t6ocrf5a7dpdj/fml-server-latest.zip

> Wait, stupid question, but the scripts are on both client and server right?
> With the exact same scripts

No? I didn't need to do that before. Clients received recipes on connecting.

Per this > http://minetweaker3.powerofbytes.com/wiki/MineTweaker_synchronization

**Comment by notfood** [comment]
Tried with both locations
under scripts and under world/scripts
It somewhat fixes itself for those online when you do a /mt reload
If client disconnects and reconnects, scripts hasn't been received.

It seems that the only solution is to run /mt reload when a client connects, seems bad.

**Comment by jaredlll08** [comment]
Do me a favor, just test it please, just so we can locate the exact bug

**Comment by DaNeo61** [comment]
if i install the script local it will work until i add a new recipe without update the client

I tested the locations "/scripts" and "/local/default/scripts" (FTB-Lib) both are working but only after /mt reload after every client connect

**Comment by jaredlll08** [comment]
Ok, so it is only affected by scripts sent from the server?

**Comment by DaNeo61** [comment]
yes if i have client and server synced it will work but if i change on server a recipe it will not showed after reconnect only if i use /mt reload everytime when i connect

if i update the client then it will work until there are changes again.

**Comment by notfood** [comment]
Copied my zs script to the client and it didn't apply.

As in, it didn't load at all.

**Comment by notfood** [comment]
I did more testing. It doesn't even work in single player until you issue an /mt reload.

**Comment by notfood** [comment]
Can we compare modlists? I think some other mod is causing conflicts because it works fine if you run MT alone under latest forge.

modlist.txt
http://pastebin.com/raw/hDzQH64J

**Comment by DaNeo61** [comment]
This is now my Forge 1558 modlist 
my 1614 i deleted but i can say every mod are the same like the list i post only the newsest versions
http://pastebin.com/dQ1ScSN6
And it is still not working ...
I am just getting mad about.

**Comment by DaNeo61** [comment]
My Problem was the newest version of FTBLib and Utilities
I Deleted them now and it works

**Comment by jaredlll08** [comment]
do you use FTBTweaks at all? or just FTBLib and Utils?

**Comment by notfood** [comment]
Mine seems to be more localized, I double checked the script and it's just some recipes I can't remove before the world loads. PortalGun is the one I was interested in removing. I can work around this one.

It was working fine before I did a general mod update. I'm not sure which mod is causing it. I'll try to do a more exhaustive search later.

Some mod is adding the recipe back after I removed them, even in the client. I don't believe this is MT's fault.

**Comment by jaredlll08** [comment]
Portal gun is stupid and loads things super super late, after we add stuff.

**Comment by notfood** [comment]
Ah. I see. Consider it closed for me.

**Comment by AlexanderBulanov** [comment]
Here's my mod list:
https://docs.google.com/spreadsheets/d/1HIvZCDE9akNAcYScCazkNT3rGnEZPRkvJMaHGTaOvqo/edit?usp=sharing
I have the same scripts both on client and on server. The recipes don't show up regardless if I test them in singeplayer or multiplayer unless I run /mt reload.

**Comment by AlexanderBulanov** [comment]
I tried only having scripts on the server but again, nothing happens until "/mt reload" is executed.

**Comment by DaNeo61** [comment]
@ jaredlll08 i had installed all three of them 
and yes portalgun is realy Stupid xD

**Comment by jaredlll08** [comment]
- [X] @notfood closed
- [ ] @DaNeo61 closed
- [ ] @AlexanderBulanov closed

Just so we can keep track

**Comment by jaredlll08** [comment]
ok so @DaNeo61 you seem to be using ftbtweaks, that changes the script location, so you need to use the new script location, the default one won't always work

**Comment by jaredlll08** [comment]
hhm @AlexanderBulanov post your script?

**Comment by AlexanderBulanov** [comment]
ExtraRecipes.zs
http://pastebin.com/usJYDfYE

ExtraTiCCompat.zs
http://pastebin.com/Ry2VzMuz

ExtraTiCFixes.zs
http://pastebin.com/US4bqjG2

MetallurgyExplosives.zs
http://pastebin.com/4QDBx7Ld

MoreChisels.zs (I didn't fully finish this one)
http://pastebin.com/c3VmV1Y7

RangedTiC.zs
http://pastebin.com/rKZFMm2E

ThaumcraftCompat.zs
http://pastebin.com/xWQjkiBS

TSteelworksCompat.zs
http://pastebin.com/CqSDzzbv

**Comment by jaredlll08** [comment]
@DaNeo61 is the problem solved for you?

**Comment by Krysinski** [comment]
I have same problem on random clients (players): new receipts in NEI dont changing but work.
mt reload dont help(((
Windows users have this issue. On Linux run normal.
Copying scripts to client not help.
server modlist:
[1.7.10]Treecapitator-universal-2.0.4.jar
AppleCore-mc1.7.10-1.1.0.jar
BiblioWoods[Forestry][v1.7].jar
Carpenter's Blocks v3.3.8_dev_r6 - MC 1.7.10.jar
catwalks-2.0.3.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.3.10.37.jar
[CLIENT]neiaddons-1.12.13.38-mc1.7.10.jar
[CLIENT]NEIIntegration-MC1.7.10-1.0.13.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
coroutil-1.1.3 for MC v1.7.10.jar
CustomOreGen-1.7.10-1.2.24.jar
CyanosLootableBodies-1.7.10-backport_1.3.7.jar
EventHelper-1.2.jar
ExtraCells-1.7.10-2.3.9b189.jar
forestry_1.7.10-4.2.5.53.jar
GalacticGreg-0.5.jar
GalacticraftCore-1.7-3.0.12.454.jar
Galacticraft-Planets-1.7-3.0.12.454.jar
gregtech-5.09.21.jar
GTTweaker-1.7.10-1.0.9.jar
HardcoreDarkness-MC1.7.10-1.7.jar
IC2NuclearControl-2.3.4a.jar
immibis-core-59.1.4.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IronChestMinecarts-1.0.3.jar
MicdoodleCore-1.7-3.0.12.454.jar
MineTweaker3-1.7.10-3.0.10B.jar
MoreBows2-1.2.jar
Morpheus-1.7.10-1.6.10 (1).jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
OpenComputers-MC1.7.10-1.5.22.46-universal.jar
Pam's HarvestCraft 1.7.10j.jar
PFAA-1.7.10-0.2.27.jar
redlogic-59.1.11.jar
[SERVER]FastLeafDecay-1.7.10-1.0.jar
[SERVER-FIXED]BiblioCraft[v1.10.6][MC1.7.10].jar
[SERVER]industrialcraft-2-2.2.817-experimental.jar
[SERVER-NOCLIENT]appliedenergistics2-rv2-stable-10.jar
[SERVER-NOCLIENT]weaponmod-1.14.3.jar
[SERVER]Railcraft-1.7.10-9.8.0.0.jar
SpiceOfLife-mc1.7.10-1.2.4.jar
zombieawareness-1.9.6 for MC v1.7.10.jar

**Comment by Krysinski** [comment]
For all clients this is problem:
after restarting server player need to restart client too, then he can view some receips again.

**Comment by Krysinski** [comment]
There are logs from clients on Linux and Windows systems: https://drive.google.com/folderview?id=0B3rROac4Sbv4ZjZLcG9KQnJTWkE&usp=sharing
When i put scripts into client i get strange errors for a few scripts like this:
WARNING: No furnace recipes for GalacticraftMars:item.itemBasicAsteroids:5
[23:19:29] [Client thread/INFO]: [CHAT] ERROR: Error loading Railcraft.zs: stanhebben.zenscript.parser.TokenException: Invalid character at Railcraft.zs:1283 - В
These strings are just comments and normal work on Linux client and server))) I delete this strings and scripts load normal.

**Comment by AlexanderBulanov** [comment]
I just fixed my problem by removing InGameConfigManager (Previously InGameCraftingManager) from my modpack. Now recipes load upon joining world both in singleplayer and multiplayer.

@Krysinski I'm closing this thread since your issue seems to be different. Submit a new thread for your problem. Best of luck!

**Comment by jaredlll08** [comment]
@AlexanderBulanov =D thank you for enforcing rules for us
@Krysinski Make a new thread. include your SCRIPTS.
