### ISSUE TITLE
Wiki info.

### ISSUE THREAD

**Issue by rbmclean** [stanhebben/MineTweaker3#320]
On the Tinker's Constuct Modtweaker Support wiki page, `mods.tconstruct.ToolStats.setBowDrawSpeed` should be written as `mods.tconstruct.ToolStats.setBowDrawspeed`. I couldn't figure out what I was doing wrong until I looked at modtweaker's source code.

Also, sorry if I should have posted somewhere else. I couldn't find anywhere on the wiki to post it.

**Comment by Yulife** [comment]
In the future, note that you can fix this as soon as you see it, the wiki is open to edit. You can close this :P

**Comment by rbmclean** [comment]
I cann't find an edit button anywhere. There also isn't a sign up button
anywhere, only a login one. I don't even have permission to create a user
page for my IP address.

**Comment by Yulife** [comment]
[All the things you are looking for in a small square.](http://i.imgur.com/wCKZyUK.png)

**Comment by rbmclean** [comment]
That does not exist! https://imgur.com/OzbkxLL

**Comment by Yulife** [comment]
Then click "Log in" and look for "Help with logging in" you can register there :D

**Comment by rbmclean** [comment]
According to the page I'm redirected to on mediawiki.org, there is supposed
to be a "create account" button after clicking "log in". It does not exist.
There must be some config setting you need to change.

**Comment by jaredlll08** [comment]
https://www.mediawiki.org/wiki/Special:UserLogin/signup
We currently do not have access to change the wiki.
Use that link, it should work

@stanhebben

**Comment by Voidi** [comment]
The Wiki uses the same account as the forum, simply use that / register there.

**Comment by rbmclean** [comment]
I was able to sign up and login for mediawiki, but the minetweaker wiki
said "You have not not specified a valid username." I don't think the two
wikis are linked in any way.

**Comment by rbmclean** [comment]
I was now able to register via the forums. The username and password did work on the wiki now. Thanks for the help!
