### ISSUE TITLE
Recipe bork.

### ISSUE THREAD

**Issue by SneakyDevil** [stanhebben/MineTweaker3#322]
So I had an issue where  the recipes for Immersive Engineering's Crusher were not being loaded. I cleaned up the script file(removing outdated references and mods) and now the recipes show up in NEI just fine(and can also be used). I can search each recipe without a problem, but if I try to view all recipes for the Crusher the game crashes.

Crash report: http://puu.sh/nncWh/75966054c7.txt
Script: http://puu.sh/nncX5/b0c2db70c3.zs
latest log: http://puu.sh/nnd27/76aa02eab1.log
fml-client-latest log: http://puu.sh/nnd27/76aa02eab1.log

Just tell me if you need anything else, because for the life of me I can't troubleshoot this anymore.

**Comment by LokeYourC3PH** [comment]
Do you also have ModTweaker? If not, add that, and try adding the recipe through it. ModTweaker is an addition to MineTweaker, with better aspects for mod support, while MineTweaker gives the main functions.

**Comment by jaredlll08** [comment]
This is a crash for @yulife and Immersion engineering, they add support not
us

**Comment by LokeYourC3PH** [comment]
jared, could you check out mine for a sec, since you are here? Im going to publish the issue now.

**Comment by jaredlll08** [comment]
I'm always here xD just decided to reply now

**Comment by LokeYourC3PH** [comment]
Oh ok :P Well ye i released mine now, take a look if you can.

**Comment by SneakyDevil** [comment]
Not to be rude, but how is this an Immersive Engineering problem? The bug only existed after I cleaned up the mod/minetweaker scripts.

**Comment by jaredlll08** [comment]
We do not add Immersion engineering support, plain as that, they add
support natively, hence, we don't have / know the code, hence we can't help

**Comment by SneakyDevil** [comment]
AH, alrighty. Thanks.
