### ISSUE TITLE
NBT Tag correct, getting script error

### ISSUE THREAD

**Issue by LokeYourC3PH** [stanhebben/MineTweaker3#323]
According to the wiki, my script is correct. But when i try to do /mt reload in game, it gives me a script error on line 9, saying "-- ) expected". What now? Here my script:

http://pastebin.com/s9Vk9iaL

**Comment by jaredlll08** [comment]
Try using the actual item instead of calling a variable, on line 9 that is

**Comment by LokeYourC3PH** [comment]
You mean like "val crystalm = < IC2:itemcrystalmemory >.onlyWithTag({ } );"?

**Comment by Yanniclord** [comment]
Dang it, stop removing the < > github -_-

**Comment by jaredlll08** [comment]
Yea try that

**Comment by LokeYourC3PH** [comment]
Ok will do.

**Comment by jaredlll08** [comment]
Take it that it worked? ;)
