### ISSUE TITLE
Recipes like ore dictionary but does not use it.

### ISSUE THREAD

**Issue by Dijkstra1-zz** [stanhebben/MineTweaker3#325]
What i mean is i want to say use this or something but they should not been seen as the same ore

**Comment by jaredlll08** [comment]
Could you try and explain your problem a bit better please.

**Comment by Dijkstra1-zz** [comment]
You know when use a ore dictionary item it shows you can use say oak wood or jungle wood and any woods, but what if say use ender pearl or TNT i do not want to say the same ore dictionary item but would like it to show like that

**Comment by jaredlll08** [comment]
Do you mean how to define a single item? like make it that you can only craft X item with oak wood and not birch wood?

**Comment by Dijkstra1-zz** [comment]
no 
`var wood = ore:log;
 var replaceableItems = [minecraft:TNT, minecraft:ender_pearl] as ItemStack[];

recipes.addShaped(mod:item, [[wood,wood,wood], [wood, replaceableItems, wood], [wood, wood, wood]];  
`

I know bad example and probably zenscript. but what i want to say is mod item will be craft from any wood and an tnt or ender pearl in the middle, the ender pearl and and the tnt should been seen like an ore dictionary item but i do not want set as one

**Comment by jaredlll08** [comment]
Yea, that isn't possible unless you create 2 recipes for each item, the best idea is to use oredicts.

**Comment by Dijkstra1-zz** [comment]
but wont basic mean if ender pearl and tnt are on same oredict value then people could do tnt plus blaze equal eye ender something like that i may just have do them individually, but it would have been nice to have like an oredict value

**Comment by VariableVixen** [comment]
Just make an oredict entry with a general name. I did something similar and named my entry `essenceCatalyst`. You can make your own entries and then populate them like so:

```
val myOreDict = <ore:myEntryName>;
myOreDict.add(<modid:item1>);
myOreDict.add(<modid:item2>);
myOreDict.addAll(<ore:anotherEntry>);
```

**Comment by Techlone** [comment]
@jaredlll08 
I though that `or` operator works. Like so

```
var wood = <ore:log>;
var replaceableItems = <minecraft:TNT> or <minecraft:ender_pearl>;

recipes.addShaped(<mod:item>, [[wood,wood,wood], [wood, replaceableItems, wood], [wood, wood, wood]];
```

What would you say?

**Comment by VariableVixen** [comment]
Probably need a whole new type in the internals, and there's really no point when the oredict works perfectly well, and also allows NEI to cycle through items. What you're proposing wouldn't, unless NEI (and probably forge) added special support. All in all, it's an interesting idea, but (IMHO) ultimately _worse_ than using the oredict. True, you need a unique name for your entry, but you can just grab the SHA1 of a UUID.

**Comment by EverybodyLies** [comment]
@Dijkstra1, Just use the loops.

```
var wood = <ore:log>;
var replaceableItems = [<minecraft:TNT>, <minecraft:ender_pearl>];

for item in replaceableItems {
    recipes.addShaped(<mod:item>, [
        [wood, wood, wood],
        [wood, item, wood], 
        [wood, wood, wood]
    ]);
}
```

**Comment by jaredlll08** [comment]
Just do what @EverybodyLies says.
