### ISSUE TITLE
[Request] Varargs on <oredictEntry>.add()

### ISSUE THREAD

**Issue by VariableVixen** [stanhebben/MineTweaker3#327]
As it is now, if I want to add a number of items to an oredict entry, I have to call `myOreDict.add(item)` for each item I want to add. If possible, I'd like to be able to call it as `myOreDict.add(item1, item2, item3, ...)` instead. Not a big deal, just a small convenience.

**Comment by EverybodyLies** [comment]
It would be great :(

**Comment by jaredlll08** [comment]
Yea this will hopefully be added, I just need time to do it :)

**Comment by jaredlll08** [comment]
So zenscript doesn't like varargs, so I made it an array, you can now do

```
val iron = <ore:ingotIron>
iron.add([<minecraft:diamond>, <minecraft:dirt>]);
```

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/CraftTweaker/commit/e43d4662f91cc1f98adfbb7a7b812df5f4ef7762

**Comment by VariableVixen** [comment]
When you say "made it an array" do you mean _replaced_ the old method (which would break old scripts) or _added a new method_ with the same name?

**Comment by jaredlll08** [comment]
New method, same name
