### ISSUE TITLE
Global values

### ISSUE THREAD

**Issue by Techlone** [stanhebben/MineTweaker3#331]
How can I to add a global value? I think I can't do this.
So I want start to work on this issue but first I need an answer it's the good idea? :)
I want to add new keyword `global` like `val`. Example
`global mcStone = <minecraft:stone>;`
And I think a global value must be unchangeable or final (Java).
ping @jaredlll08 @stanhebben

**Comment by jaredlll08** [comment]
This has been asked before, please look through the issues before posting

**Comment by Techlone** [comment]
And nobody answered.
Clone #318
