### ISSUE TITLE
<liquid:life essence> not recognized from Mariculture Vat recipe

### ISSUE THREAD

**Issue by LachimHeigrim** [stanhebben/MineTweaker3#334]
Testing the following recipe:

```
# Natura blood from Life Essence and Water
mods.mariculture.Vat.addRecipe(<liquid:life essence> * 250, <liquid:water> * 750, <liquid:hell_blood> * 1000,10);
```

After  `/mt reload` getting the following in minetweaker.log

```
ERROR: Mariculture.zs:21: Could not resolve <liquid : life essence>
ERROR: Error executing Mariculture.zs: Bad type on operand stack
Exception Details:
  Location:
    Mariculture.__script__()V @183: ifnonnull
  Reason:
    Type integer (current frame, stack[2]) is not assignable to reference type
  Current Frame:
    bci: @183
    flags: { }
    locals: { top, 'minetweaker/api/item/IItemStack', top, 'minetweaker/api/item/IItemStack' }
    stack: { null, integer, integer } 
```

Recipe works fine with liquids other than `<liquid:life essence>`. Maybe the space is the problem? It is the only liquid with space in the name.

I am using
- Forge: 1.7.10-10.13.4.1614-1.7.10:universal
- BloodMagic-1.7.10-1.3.3-17.jar 
- ModTweaker2-0.9.5.jar 
- MineTweaker3-1.7.10-3.0.10B.jar 
- Mariculture-Deluxe-1.7.10-1.2.4.2a.jar

**Comment by VariableVixen** [comment]
Spaces in liquid names have been a problem for a while. Mod authors aren't supposed to use spaces in names like that, because it causes problems - like Minetweaker not being able to resolve it.

**Comment by jaredlll08** [comment]
This was actually resolved in the latest release of Crafttweaker

**Comment by LachimHeigrim** [comment]
@PrincessRTFM is that fixable? Originally I suspected the problem will be in tokenization (parsing) of the ZenScript but from the error message it seems liquid name was parsed correctly. As you wrote, it fails in resolution phase, which is a bit surprising as I'd guess it it just lookup through some HashMap (I did not look at the actual code yet, just guessing).

**Comment by LachimHeigrim** [comment]
@jaredlll08 thanks for info. Is Crafttweaker official successor of Minetweaker?

Also in in #329 you provided a custom build for 1.7.10. I managed to download it so I'll test the above recipe in it too. Cheers.

Btw. thank you both for your fast response

**Comment by LachimHeigrim** [comment]
Tested on the Crafttweaker build in #329 and indeed no errors on `/mt reload` and recipe works as expected.

**Comment by jaredlll08** [comment]
No idea why this wasn't closed sooner
