### ISSUE TITLE
Reuse, giveBack, transform not working in Arcane Workbench

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#336]
Example script:
recipes.addShaped(output, [[inputA.reuse(), inputB]]);

In normal crafting table inputA stays in crafting table. But when I try to craft that same item in Arcane Workbench the inputA is consumed.

Same goes for giveBack, transformDamage, transformReplace

It is probably Thaumcraft's fault, but is there any chance there could be made some workaround this? Also found another mod, which is missbehaving the same, that mod is XACT

MineTweaker: 3.0.10B

**Comment by Voidi** [comment]
1. The Minetweaker Support for Thaumcraft is done via [Modtweaker](https://github.com/jaredlll08/ModTweaker2).
2. All the Advanced recipe 'things' like reuse, transform require that the recipe handler for this crafting method accept IIngriedent, which the one for the Arcane Crafting Table doesn't (like many from other mods)
3. Before you ask: implementing this in Modtweaker might be possible, but is a bit painful for the developers, it would be better if Thaumcraft would support Minetweaker itself. Furthermore i don't think that there would come any updates for 1.7.10 and Thaumcraft 4 as @jaredlll08 has began to work on the support for Thaumcraft 5.

**Comment by jaredlll08** [comment]
this has to be handled thaumcraft side iirc.
