### ISSUE TITLE
Unable to check for missing NBT Tag

### ISSUE THREAD

**Issue by Sil3ntStorm** [stanhebben/MineTweaker3#338]
I need to use NBT tag values of multiple ingredients in a function recipe and do stuff with them, however in certain conditions the NBT tag is not present.

It'd be kind of easy if getTag would return null if there is no such tag, since one can apparently check for != null in ZenScript (at least it didn't complain about that, but may also be because of other errors that came before).

The problem is that I cannot seem to come up with a way that represents https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/api/data/DataMap.java#L14 in ZenScript.

```
val absent = [] as IData[]; // Complains it cannot convert IData[] to IData which makes sense
val absent = {}; // Makes MineTweaker complain about missing stuff like ) or ;
val absent = {} as IData; // Same as above
```

From what I understand one of the latter two should work but it doesn't.

**Comment by jaredlll08** [comment]
Could you provide the minetweaker.log file please, so we can see exact errors

**Comment by Sil3ntStorm** [comment]
It's been quite a while ago, so I don't have the files, scripts or logs anymore. I don't even think I still have the minecraft setup from back then anymore. 
Note though that this is due to the linked issue of the NPE crash when NBT data is missing, for which there is crash data (though no MT log). In here I just tried to reconstruct the empty datamap in order to compare it to the returned NBT data from the .tag property so that I could workaround the crash by checking for non existing nbt data myself prior to working with the values (which ideally would be done by MT itself before accessing the values).

I could try and setup a Minecraft instance again to reproduce the issue if necessary, probably not before next week though.

**Comment by Sil3ntStorm** [comment]
Sorry for delay.

```
val absent = {};
```

results in "ERROR: Error parsing harder.zs:7 -- ; expected" (with Line 7 of the script being the above)

```
val absent = {} as IData;
val t1 = inputs.tab1.tag.electricity;
```

results in "ERROR: Error parsing harder.zs:8 -- ; expected" with the above being line 7 and 8

If you change line 7 to this:

```
val absent = {};;
```

It'll produce the following: https://gist.github.com/Sil3ntStorm/4080e6d2af3a22dfe32473abbd5d048c

See Full script here: https://gist.github.com/Sil3ntStorm/576da27f7b2b733307430a3c7ec7901f

**Comment by jaredlll08** [comment]
Just use an if statement to see if the tag is empty.
