### ISSUE TITLE
NPE Crash when using missing NBT tags in function recipe

### ISSUE THREAD

**Issue by Sil3ntStorm** [stanhebben/MineTweaker3#339]
When doing things like
`recipes.addShaped(coolItem, [[coolIngredient, coolIngredient2.marked("item"), cool3.marked("item2")]], function (output, inputs, crafting) {
    energy1 = inputs.item1.tag.energyStored;
    energy2 = inputs.item2.tag.energyStored;
    return coolItem.withTag({energyStored: energy1 + energy2});
});`
the game will crash as soon as you put the final piece of the recipe in the crafting grid if one of the items is missing the energyStored NBT tag.
I tried checking for the NBT tag being there but ended up with #338 

Maybe the code could check if one of the operands is equal to DataMap.EMPTY and treat it as 0 for arithmetic functions?

http://pastebin.com/vQnk4p98

**Comment by jaredlll08** [comment]
Just use an if statement to see if the tag is empty

**Comment by Red3Tango** [comment]
I know this is a bit of a Necro, but I am completely lost. I have been having this same issues and cannot find a way around.

I need to check if the tag exists, however, if the tag is missing I get the same issue as the OP. The help of "Just use an if statement to see if the tag is empty" does not work, as if the tag does not exist, if you reference it at all, you get a NRE and crash.

So if someone has found a way around this, please comment.
