### ISSUE TITLE
Minetweaker not working at all with scripts

### ISSUE THREAD

**Issue by Jackzmc** [stanhebben/MineTweaker3#340]
I'm running on FTBInfinity 2.2.2 with a few custom mods. I have made my own scripts, and have FTBInfinity's script too. The problem is that there are no errors in console, but no changes to recipes have taken effect. I removed my custom code, and the ftbinfinity script nothing works still.

I've done /minetweaker reload, no errors. I've relogged on singleplayer, no changes.
I have the scripts stored in .ftb\FTBInfinity\minecraft\scripts and I tried in my saves folder for the test world. Nothing. Sorry If I should post this elsewhere

**Comment by jaredlll08** [comment]
First of all, wrong place, doesn't matter since I'm also the dev of FTBTweaks.
Secondly, put your scripts into the custom script folder that FTBInfinity adds.

**Comment by Jackzmc** [comment]
Oh I had no clue FTB infinity had it's own custom location. Sorry then, but it did look like in log they were loaded. I'll try later. Thanks
