### ISSUE TITLE
Loading Order

### ISSUE THREAD

**Issue by Sir-Will** [stanhebben/MineTweaker3#341]
hey,

any chance the loading order could be changed so that scripts in the world directory get loaded after the others?

As I would like to overwrite recipes for items which are already defined in main scripts folder.

Example how it is atm:
-   `scripts` --> removes and adds a recipe
-   `world/scripts` --> adds or removes a recipe

`world/scripts` gets overwritten by scripts.

**Comment by Dream-Master** [comment]
https://github.com/stanhebben/MineTweaker3/pull/274

**Comment by jaredlll08** [comment]
@Dream-Master not what he is wanting, that will load the files in the scripts folder, but apparently (I say that because I have NEVER seen someone actually use it...) you can put scripts in the world folder, so even if that was pulled, it wouldn't make a difference to this. Anyway, this is low priority right now, sorry.

**Comment by Sir-Will** [comment]
@jaredlll08 the `world/scripts` folder is mainly useful for servers as it sends the recipes in there to all connected clients.

**Comment by Dream-Master** [comment]
Ah sorry not see it but this is a good idea not shiping all scripts in the pack and let it only on the server.

**Comment by jaredlll08** [comment]
Yes, but using the default scripts folder it does the same thing.

**Comment by Sir-Will** [comment]
Oh okay, wiki did say something else^^ 
However, does unfortunately not solve the issue :/

**Comment by jaredlll08** [comment]
Just did this, just for future reference, Scripts are loaded as follows:
IMC Scripts = Scripts sent from mods (isn't used afaik)
ScriptsLocal = world/scripts (since the change that I just made)
ScriptsGlocal = global /scripts/ folder

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/CraftTweaker/commit/ab1eb5cff531103aba06dd19d33265df848c89c1

**Comment by Sir-Will** [comment]
Hm, in this order global will overwrite the local scripts or not?

**Comment by jaredlll08** [comment]
Is that not what you wanted? If not, then I can't do anything, it was
originally
Imc
Global
Server

So I don't know what else I can do

**Comment by Sir-Will** [comment]
I would like that local overwrites the global scripts and also does send the scripts to the client like that.
That way I can overwrite the scripts from modpack authors without editing the modpack files.

**Comment by AnrDaemon** [comment]
World scripts should execute last, and the order in which scripts executed in each category, should be uniform.

**Comment by AnrDaemon** [comment]
While [wiki states](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Introduction), that "scripts can be bundled with worlds, making it possible to make modifications available to specific worlds only", any modifications you make in the world scripts will be overridden by the global scripts.
And conversely, any global registrations you make, such as OreDict registrations, will not be available to world specific scripts.
