### ISSUE TITLE
MineTweaker re-registers base command on reload.

### ISSUE THREAD

**Issue by Aaron1011** [stanhebben/MineTweaker3#342]
Currently, MineTweaker re-registers its [base command](https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/MineTweakerImplementationAPI.java#L640) whenever the `/mt reload` command is run. 

This is causing an [issue with SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/601), which takes over command handling. Sponge requires that a given alias only have a command registered to it once.

If you wouldn't mind only registering your command once, when the server initially starts up, it would be much appreciated.

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/CraftTweaker/issues/15
