### ISSUE TITLE
[Clarification/Request] Thermal Expansion

### ISSUE THREAD

**Issue by VariableVixen** [stanhebben/MineTweaker3#344]
What exactly is causing the (for lack of a better phrase) recipe stickiness in ThermEx? The problems with recipes not quite updating correctly, or not being able to remove recipes? Is it the "allow <machine> recipe overwrite" option in ThermEx's config files? Is it just the way ThermEx is written? And whatever it is, is there any way to fix it on MT's side, or does it need to be a change in ThermEx itself?

**Comment by AnrDaemon** [comment]
TE itself. It heavily caching the recipes, preventing modification.

**Comment by jaredlll08** [comment]
As @AnrDaemon said, it is all TE side, but I understand why they do what they do, and while I could probably get around the caching, it isn't worth it.
