### ISSUE TITLE
error

### ISSUE THREAD

**Issue by leytilera** [stanhebben/MineTweaker3#345]
some recepies from this script wont work:
http://pastebin.com/cf4Ti9PY

**Comment by jaredlll08** [comment]
It would be great if we knew which recipes were broken. Honestly, you
expect us to fix something when all you tell us is "1 of these 50000 things
are broken!"

**Comment by leytilera** [comment]
the warpbook, the avaritia and the other with project e things.

**Comment by jaredlll08** [comment]
Now we are getting somewhere.
What error does it give?

**Comment by leytilera** [comment]
it say scrips reloaded but when i check the recepies with nei there ist no for the things

**Comment by jaredlll08** [comment]
Game version?
Minetweaker3 version?
Minetweaker or crafttweaker?
Modtweaker installed?
Minetweaker log?

**Comment by leytilera** [comment]
game version: 1.7.10
minetweaker version: 3.0.10b
modtweaker installed
minetweaker log: wait. minecraft must start first.

**Comment by leytilera** [comment]
here ist the log: http://pastebin.com/Zr0AuVBe but i must go afk. i come back in 1 hour.

**Comment by jaredlll08** [comment]
There are no errors in the log, so this isn't an issue with us, it is more of a script issue.

It seems that you are adding recipes then removing recipes, ALWAYS remove recipes then add them

**Comment by leytilera** [comment]
what is with this in the log?: INFO: Un-adding Xtreme Crafting Recipe for Philosopher's Stone

**Comment by jaredlll08** [comment]
Look at the warp book recipe

**Comment by leytilera** [comment]
what is there?

**Comment by jaredlll08** [comment]
Omg, I'm not fixing your script for you. If this was an issue / error, the
log would say so. This is user error, in your script, remove shit, then add
shit, not the other way around.

**Comment by leytilera** [comment]
i mean what is with the warpbook recepie?

**Comment by jaredlll08** [comment]
You are adding the recipe then removing it. Simple as that. Use yours eyes.

**Comment by leytilera** [comment]
oh, i dont know that there is an order for the recepies. thank you for saying that.

**Comment by jaredlll08** [comment]
This seems to be user error
