### ISSUE TITLE
New receipts not showing in NEI under OS Windows clients. Fake script's errors when loading scripts.

### ISSUE THREAD

**Issue by Krysinski** [stanhebben/MineTweaker3#346]
Server: Thermos 1.7.10-1614.46
Forge version 10.13.4.1614
MineTweaker3 3.0.10B
1. Need to restart client after "mt reload" or restarting server beacose a part of new receipts disapear from NEI.
2. Windows OS: local scripts loading with fake errors:
[23:19:29] [Client thread/INFO]: [CHAT] ERROR: Error loading Railcraft.zs: stanhebben.zenscript.parser.TokenException: Invalid character at Railcraft.zs:1283 - В
String 1283 in Railcraft.zs contains this: // --- HobbyistÂ´s Steam Engine ---  
There was some few random similar errors with commented strings. After deleting this "error" strings scripts were loaded without errors, NEI show new receipts. That was in single game.
3. Windows OS: after connecting to server NEI wont show new receipts, "mt reload" wont help.
4. Linux OS (same machine are tested too): NEI work normal  except issue 1.

There are logs from clients on Linux and Windows systems, scripts, server mods, client mods: https://drive.google.com/folderview?id=0B3rROac4Sbv4ZjZLcG9KQnJTWkE&usp=sharing

I cant reproduce this bug myself, i dont have any Windows on my machines. But i try ask help from frends if needed.

**Comment by jaredlll08** [comment]
ok so basically, all your issues stem from errors in the script?

on line 1283 of "RailCraft.zs", you use the character "´" which is not a normal English character, I would suggest going into all your scripts, changing the character to an english char and going from there.

**Comment by Krysinski** [comment]
I take most of scripts from Arch github (project Grind Complex), Arch is owner of Kirara servers at now.
Ok, i try to change scripts. But at UTF-8 based system all work normal with chars))))
Server transmit comments from script to client also?

**Comment by jaredlll08** [comment]
I am not sure, but I think it does take the comments

**Comment by Krysinski** [comment]
Problem 2. and 3. solved by removing non-ASCII chars from scripts.
I use this to mark and view non-ASCII chars in scripts files:
`grep --color='auto' -P -n "[\x80-\xFF]" *.zs`
This will remove non-ASCII chars and save files:
`perl -pi -e 's/[[:^ascii:]]//g' filename`
(code taked from http://stackoverflow.com/questions/3264915/remove-non-ascii-characters-in-a-file)

Problem 1. is still actual.

**Comment by jaredlll08** [comment]
Do the recipes still work? And just not update in NEI?

**Comment by Krysinski** [comment]
Yes. Old receipt was removed by script and new not showing in NEI (cant find item/block by ID or name).
Console say that after mt reload:
`[22:57:08] [Client thread/INFO]: [CHAT] WARNING: 622 modifications were stuck
[22:57:30] [Client thread/INFO]: [CHAT] Scripts reloaded`
"stuck" linked with changing receipt for IC2 machines, right? That is a limitation of reloading scripts and nothing we can do?

**Comment by jaredlll08** [comment]
Do not reload scripts. That instantly voids warranty for my help. NEI is
terribly broken.

**Comment by Krysinski** [comment]
I know about NEI( But servers must be reloaded every 4-6 hours for normal work. NEI do not reload receipts after disconecting from server, that is problem.
Very thanks for help. Please add warning about non-ASCII chars in Minetweaker WIKI.

**Comment by AnrDaemon** [comment]
Even forcing Java to work with UTF-8 (`-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8`, why MT does not  do that by itself, anyway?), MT will still choke on Unicode symbols in comments. Even those 100% legal in ANSI, such as horizontal ellipsis ("…", U+2026).
`ERROR: Error loading TiC-tweaks.2.zs: stanhebben.zenscript.parser.TokenException: Invalid character at TiC-tweaks.2.zs:19 - …`
The line it is complaining about is a COMMENT.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
