### ISSUE TITLE
Can't set block hardness

### ISSUE THREAD

**Issue by trkei** [stanhebben/MineTweaker3#348]
I attempted to change the hardness of oak wood, this is what happens:
[Error](http://pastebin.com/PMA4QLNn)
[Scripts](http://pastebin.com/U01g966R)

[Log](http://pastebin.com/VYTU65ag)
I have FastCraft, I don't know if that matters.
#239 had the same issue, but it doesn't say how his was resolved.

Speaking of, here's the questions jared asked
MC Version: 1.7.10
Forge Version: 10.13.4.1614
MineTweaker Version: 3.0.10B

**Comment by jaredlll08** [comment]
Use the version here: http://minecraft.curseforge.com/projects/crafttweaker-customized-minetweaker3
