### ISSUE TITLE
[Request] Default Localization LanguageCode

### ISSUE THREAD

**Issue by 5lx** [stanhebben/MineTweaker3#349]
If I use a script which set localization LanguageCode to en_US in another language environment, the text will only show the key. So I think it will be more convenient, if we can set a default localization LanguageCode for each script files, instead change all the LanguageCode to match gaming environment. And the specific localization text setting in different language will override the default one.

**Comment by VariableVixen** [comment]
Something like `game.setDefaultLanguageCode(string)` you mean?

**Comment by 5lx** [comment]
I think it already have the function `game.setLocalization(KEY, TEXT)`
This will override no matter the language.
