### ISSUE TITLE
MFR Planter - Unable to specify blocks to plant on

### ISSUE THREAD

**Issue by j-carrington** [stanhebben/MineTweaker3#350]
I'm trying to properly integrate the BoP trees with the MFR Harvester and Planter machines as most of the existing scripts are incomplete.

I'm running into problems while trying to specify custom blocks on which it should be possible to plant certain saplings, for example BiomesOPlenty:longGrass.

mods.mfr.Planter exposes a public method which should make this possible:

``` java
@ZenMethod
public static void addPlantable(IItemStack seed, @Optional IBlockPattern canPlantOn) 
```

However I am unable to pass a variable of type IBlockPattern as ZenScript doesn't appear to allow me to correctly cast.

```
import mods.mfr.Planter;
import mods.mfr.Harvester;
import minetweaker.item.IItemStack;
import minetweaker.block.IBlock;
import minetweaker.block.IBlockPattern;

var MagicSapling = <BiomesOPlenty:saplings:3>;
var LongGrass = <BiomesOPlenty:longGrass:*>;

Planter.addPlantable(MagicSapling, LongGrass as IBlockPattern); // "Cannot cast minetweaker.item.IItemStack to minetweaker.item.IBlockPattern"
```

Neither does it allow me to cast to type IBlock:

```
var LongGrass = <BiomesOPlenty:longGrass:*> as IBlock; // "Cannot cast minetweaker.item.IItemStack to minetweaker.item.IBlock"
```

**Comment by jaredlll08** [comment]
The MFR support was always broken, when I get time I'll look into fixing it a bit

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
