### ISSUE TITLE
script load order broken on non-windows plaforms

### ISSUE THREAD

**Issue by perlguy** [stanhebben/MineTweaker3#351]
File.listFiles() is not guaranteed to return files in any given order.    From the java docs on File:

There is no guarantee that the name strings in the resulting array will appear in any specific order; they are not, in particular, guaranteed to appear in alphabetical order.

On non-windows platforms, files are returned in whatever order they are stored on the filesystem... you  need to explicitly sort the list if you want predictable behavior with respect to removing/adding recipes for the same items/blocks across multiple scripts.  I suspect this is why it "works fine" on windows, but is causing problems for people on other platforms.

**Comment by AnrDaemon** [comment]
#341 and documentation explicitly states that scripts are to be loaded in a random order :/

**Comment by perlguy** [comment]
Fair enough. I'll pass that on to the ftb guys who are relying on predictable load order.
