### ISSUE TITLE
IngredientStack has no getter for the contained IIngredient

### ISSUE THREAD

**Issue by Daomephsta** [stanhebben/MineTweaker3#352]
This means that it's impossible to create OreDict recipes from an Ingredient stack, because you cannot retrieve the contained IIngredient and check if it is an IOreDictEntry. The commit that closed #282 did not solve this.

**Comment by LakMoore** [comment]
I believe you call getInternal() on your Ingredient and test the response.  If the Ingredient is an OreDict entry it will return its own name.

From MCOreDictEntry:

``` javascript
@Override
public Object getInternal() {
    return OreDictionary.getOreName(id);
}
```
