### ISSUE TITLE
Comamnd will not work

### ISSUE THREAD

**Issue by Jackzmc** [stanhebben/MineTweaker3#353]
Hello so I'm trying to use minetweaker on mc1.7.10 on the server (issue also occurs in client singleplayer). The command /minetweaker will not work. It will say 'Unknown command'.

In the log it says it removed the command minetweaker and I cannot find a config file for it anywhere. The script I have (it removes all recipes) is in /modpack/default (using Ftbutilities/Lib/Tweaks)

**Comment by jaredlll08** [comment]
Crafttweaker or minetweaker?

**Comment by Jackzmc** [comment]
Minetweaker

**Comment by jaredlll08** [comment]
Post your minetweaker.log file please

**Comment by Jackzmc** [comment]
I can't upload .log so i put .txt at the end
[minetweaker.log.txt](https://github.com/stanhebben/MineTweaker3/files/294586/minetweaker.log.txt)

**Comment by jaredlll08** [comment]
Could I see your scripts please

**Comment by Jackzmc** [comment]
This is all:
`recipes.remove(<*>);`
(It worked once and this worked)

**Comment by jaredlll08** [comment]
Do me a favor and try a different scripts, like instead of remove all just
remove a single item

**Comment by Jackzmc** [comment]
I did 
`recipes.remove(<minecraft:planks>);` and it worked
but the command does not work still (unknown command) 

I can try /reload (from Ftbutilities) but it might not do much

**Comment by jaredlll08** [comment]
This is weird, try using /mt instead of /minetweaker

Alternatively, use crafttweaker, as it does not reload the commands

**Comment by Jackzmc** [comment]
I've tried /mt and /minetweaker neither work. Does crafttweaker replace minetweaker, or needs minetweaker?

**Comment by jaredlll08** [comment]
Replaces it

**Comment by Jackzmc** [comment]
Looks to be working now with crafttweaker. Thanks
