### ISSUE TITLE
Could not resolve <mcheli : 46>

### ISSUE THREAD

**Issue by Polyana-Fontes** [stanhebben/MineTweaker3#355]
I have MC Helicopter mod on my sever but I blocked military itens on my server using MineTweaker. It worked fine but I'm unable to block 46cmCanon because it's ID is mcheli:46, so `recipes.remove(<mcheli:46>)` results in an error:  `Could not resolve <mcheli : 46>`

PS: I'm reporting here again because I think that I reported on the [wrong repository](https://github.com/stanhebben/MineTweaker/issues/39).

**Comment by jaredlll08** [comment]
Do /mt hand

While holding the item, then use that name

**Comment by jaredlll08** [comment]
So? did it work?

**Comment by jaredlll08** [comment]
Closing this since there has been no info
