### ISSUE TITLE
NullPointerException processing script

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#356]
Im getting this error: http://pastebin.com/n5Dt3Vsi
The script im using is this: http://pastebin.com/Su96fb98

**Comment by jaredlll08** [comment]
Need full script on pastebin or similar site.

**Comment by ghost** [comment]
updated

**Comment by jaredlll08** [comment]
on line 19, you mispelt "legs" fix that and try again

**Comment by ghost** [comment]
and i though it was some kind of syntax error...
