### ISSUE TITLE
MineTweaker 'Error parsing'

### ISSUE THREAD

**Issue by Wolfaunote** [stanhebben/MineTweaker3#358]
Hey !
MineTweaker says me 'Error parsing MineTweaker.zs:11 -- ] expected.
## I don't know why, can you help me please ?

My files :
# Osmium seed craft

recipes.addShaped(magicalcrops:magicalcrops_ModMagicSeedsOsmium \* 1, [[Mekanism:Ingot:1, magicalcrops:magicalcrops_MagicEssence:3, Mekanism:Ingot:1], [magicalcrops:magicalcrops_MagicEssence:3, minecraft:wheat_seeds, magicalcrops:magicalcrops_MagicEssence:3], [Mekanism:Ingot:1, magicalcrops:magicalcrops_MagicEssence:3, Mekanism:Ingot:1]]);
# Osmium craft

recipes.addShaped(Mekanism:OreBlock \* 12, [[magicalcrops:magicalcrops_ModCropEssence:25, magicalcrops:magicalcrops_ModCropEssence:25, magicalcrops:magicalcrops_ModCropEssence:25], [magicalcrops:magicalcrops_ModCropEssence:25, null, magicalcrops:magicalcrops_ModCropEssence:25], [magicalcrops:magicalcrops_ModCropEssence:25, magicalcrops:magicalcrops_ModCropEssence:25, magicalcrops:magicalcrops_ModCropEssence:25]]);
# Wood craft

recipes.addShaped(minecraft:log \* 32, [[magicalcrops:magicalcrops_ElementEssence:2, magicalcrops:magicalcrops_ElementEssence:2, magicalcrops:magicalcrops_ElementEssence:2], [magicalcrops:magicalcrops_ElementEssence:3, magicalcrops:magicalcrops_ElementEssence:3, magicalcrops:magicalcrops_ElementEssence:3], [magicalcrops:magicalcrops_ElementEssence:2, magicalcrops:magicalcrops_ElementEssence:2, magicalcrops:magicalcrops_ElementEssence:2]]);
# Yellorium craft

recipes.addShaped(BigReactors:BRIngot \* 16 [[magicalcrops:magicalcrops_CropEssence:13, magicalcrops:magicalcrops_CropEssence:13, magicalcrops:magicalcrops_CropEssence:13], [null, null, null], [magicalcrops:magicalcrops_CropEssence:4, magicalcrops:magicalcrops_CropEssence:4, magicalcrops:magicalcrops_CropEssence:4]]);
# Ludicrite craft

recipes.addShaped(BigReactors:BRIngot:8 \* 8 [[BigReactors:BRIngot:4, BigReactors:BRIngot:4, BigReactors:BRIngot:4], [BigReactors:BRIngot:4, BigReactors:BRIngot:4, BigReactors:BRIngot:4], [BigReactors:BRIngot:4, BigReactors:BRIngot:4, BigReactors:BRIngot:4]]);

**Comment by jaredlll08** [comment]
We will only help if you post a pastebin of all scripts and minetweaker.log
file.

**Comment by Wolfaunote** [comment]
http://pastebin.com/UY1kUfZ8

**Comment by jaredlll08** [comment]
Look on line 11, you are missing a ","
