### ISSUE TITLE
[Request] Set food values

### ISSUE THREAD

**Issue by VariableVixen** [stanhebben/MineTweaker3#359]
I'd love to be able to set food values (hunger/saturation given) for items, or at least for existing foods. Is this technically possible for 1.7.10?

**Comment by jaredlll08** [comment]
Just checked, this isn't possible, sorry :/

**Comment by VariableVixen** [comment]
Ah, well. Does it look possible in the future, or is that mechanic pretty much set in stone?

**Comment by jaredlll08** [comment]
@PrincessRTFM problem is because of how food items are done, there is no registry of them that we can change, and there is no field that we can change either :/
