### ISSUE TITLE
is it possible to remove drops from mobs

### ISSUE THREAD

**Issue by tyler489** [stanhebben/MineTweaker3#360]
i saw somewhere that 3.1 has support for removing drops for mobs but cant seen to find documention on it
i want to remove carrots and potatoes from zombies and angry zombies

this is 1.7.10

**Comment by jaredlll08** [comment]
That is because 3.1 doesn't exist.

**Comment by tyler489** [comment]
thats what i figured  but someone was telling me it was possible in 3.0 as well

**Comment by jaredlll08** [comment]
Yea, if there isn't doc for it, we don't add it, sorry
