### ISSUE TITLE
[Feature Request] Make recipes invisible in NEI

### ISSUE THREAD

**Issue by Shahelion** [stanhebben/MineTweaker3#361]
I want there to be recipes for things that can't be looked up in NEI (I'm putting them in a book in-game).

Preferably with ModTweaker recipe support as well.

**Comment by Vankka** [comment]
import mods.nei.NEI;

NEI.hide(minecraft:bread);

**Comment by jaredlll08** [comment]
That hides the item, not the recipe, he wants the item to show, without the
recipe showing

**Comment by Vankka** [comment]
Ah. Sorry

**Comment by LakMoore** [comment]
I think that would have to be a feature of NEI!?!?

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
