### ISSUE TITLE
Difficulty with null error in Thaumcraft 4 recipe

### ISSUE THREAD

**Issue by wizard1399** [stanhebben/MineTweaker3#362]
Hello,

I keep getting a  error executing null whenever I try to modify the recipe for the lowest thaumcraft wand. 
[Thaumcraft Wand Recipe](http://pastebin.com/HQv38tpf)
[From the MT log](http://pastebin.com/HuUimzJS)

Is this my poor coding or is there really an issue here?

**Comment by jaredlll08** [comment]
There is no such thing as `recipes.addShaped.mirrored`, use `recipes.addShapedMirrored`
