### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by andrewminer** [stanhebben/MineTweaker3#364]
I'd like to make a contribution to MineTweaker, but I'm having trouble even getting things to build.  I've forked the repository, cloned a local copy, and installed gradle (Gradle v2.3 on MacOS X Yosemite using Java v1.8.0_31).  However, when I run any of the gradle commands specified in [readme.md](https://github.com/stanhebben/MineTweaker3/blob/master/readme.md), I wind up with the following error and no build artifacts:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/andrew/Documents/Source/MineTweaker3/build.gradle' line: 42

* What went wrong:
A problem occurred evaluating root project 'MineTweaker3'.
> Project with path 'MineTweaker3-MC18-Mod-NEI' could not be found in root project 'MineTweaker3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

My repository _does_ have the directory mentioned, but it seems to be the only project directory missing a `build.gradle` file.  Did you perhaps forget to check that one in?

**Comment by jaredlll08** [comment]
Hey, this is a known issue, but this repo isn't really used anymore: https://github.com/jaredlll08/CraftTweaker
