### ISSUE TITLE
Harvester.removeHarvestable(IBlockPattern pattern) 

### ISSUE THREAD

**Issue by boop5** [stanhebben/MineTweaker3#365]
Can you give an example of how to use `Harvester.removeHarvestable`?

I want to add vanilla fern to the planter

```
Planter.addPlantable(<minecraft:tallgrass:2>);
```

Works perfect

Now I want to remove it from the Harvester

```
Harvester.removeHarvestable(<minecraft:tallgrass:2>);
```

That throws an exception tho, that it does not accept an `IItemStack`

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
