### ISSUE TITLE
More mod compatibality/Weird item stacks

### ISSUE THREAD

**Issue by the-creamster** [stanhebben/MineTweaker3#366]
There's a few more mods which currently don't have support, which would be nice to have the support.
New Mods:
- PSI (material infusions; psidust, psimetal & psigems)
- Roots (imbuer, mortar & pestle, casting altar)
- Deep Resonance (laser catalyst processing stage)

The PSI support is what the other admin & i want atm as it'll let us properly implement our ideas. As for the weird item stack when referencing <ore:plateIron/Gold etc...>; its placing a stack of 9 instead of 1; any ideas.

A recipe that is working and has the unsual plate stack size in the recipe (got another 17 that are doing the same for both iron/gold references).
//Iron Helmet
recipes.remove(minecraft:iron_helmet);
recipes.addShaped(minecraft:iron_helmet,
    [[ore:plateIron, ore:plateIron, ore:plateIron],
    [ore:plateIron, minecraft:leather_helmet, ore:plateIron],
    [null, null, null]]);

Thanks, Cream Bun.

**Comment by jaredlll08** [comment]
This should be in the modtweaker repo, but anyway,
I have looked into roots and it may be added
PSI? Please explain how that would work, I havn't actually used the mod.
Deep resonance, no idea how it would work, havn't used the mod.

**Comment by the-creamster** [comment]
PSI(Psionic Spell Casting) is based around an anime; the mod is where you use cad assemblies, sockets, cores, batteries & colourises in a cad assembler to make a cad(casting assisting device) which casts spells made in a gui style intuitive programming method. It adds 3 'tricks'(spell action component) which are used to infuse other materials into it's psi variant.
1. redstone->psidust(no trick/spell needed)
2. gold->psimteal(infusion trick in a spell)
3. diamonds->psigems(greater infusion trick in a spell)
4. coal/quartz->ebony/ivory(ebony & ivory trick in a spell)
I and the other admin want to be able to change the item needed to do any of the infusion processes.

Deep Resonance is a mod all about making crystals which produce RF. The process to make a crystal is lenghty, precise and fraught with risks at all stages except one of them.
1. Resonating Ore in smeltery creates RCL(resonating crystal liquid), if the amount of lava in a tank below the smeltery is not within a certain range the 'quality' stat will drop and can't be changed at any stage of the process.
2. This RCL is then purified using filter material in a purifier(85% maximum).
3. Once purified it can be crystallised(the final stage making the RF producing crystal) or the liquid pumped into another tank for the 'laser catalyst' stage. This stage needs items(different items change the RCL stats in different amounts) and catalyst(this is obtained from recycling crytals, you find a lot of 'junky' ones in you mining expeditions). Only with an item & catalyst will the infusing laser do its job but letting the purity drop to 0 will result in a chance to lose some of the RCL(0nce happy with the RCL stats its then crystallised and you have your crystal.

The 'laser catalyst' stage, in particular what items give whats RCL stat changes is what i'll want to be able to tweak/add other items too. These RF producing crystals are very powerful as an approx 65% strength/efficiency will result in an approx 9500RF/t crystal with a capacity of approx 1 mil RF. The power production of max stat crystals are in the order of 20000RF/t +. So Deep Resonance is a powerful mod if you spend the time on it.

**Comment by the-creamster** [comment]
As for the weird plate item stack in custom recipes you have any ideas as to why its occurring??

Thanks, The_Creamster.

Edit:
This weird item stack issue is occurring with steel for the enderio machine chassis too(its getting a stack of 9 instead of 1).
recipes.remove(enderio:itemMachinePart);
recipes.addShaped(enderio:itemMachinePart,
        [[ore:barsIron, ore:ingotSteel, ore:barsIron],
        [ore:ingotSteel, enderio:itemBasicCapacitor, ore:ingotSteel],
        [ore:barsIron, ore:ingotSteel, ore:barsIron]]);

**Comment by jaredlll08** [comment]
What weird plate itemstack issue?
And I'll look into the other mods.

**Comment by the-creamster** [comment]
Here's another few things which aren't working:
1. mods.botania.ManaInfusion.addInfusion(ore:ingotManasteel, ore:ingotSteel, 1000);
That should add a botania manapool infusion to get 1 manasteel from 1 steel at a cost of 1000 mana but is giving me the following in-game; "?:2 No such member: botania"
2. The renaming one doesn't seem to be working either and yes i have read that it doesn't work on all items.

I should've mentioned it at the start but i'm using 1.10.2 for more accurrate troubleshooting.

**Comment by jaredlll08** [comment]
@the-creamster firstly, this is the wrong repo.
Secondly, all of these should be seperate issues.
Third of all, botania support has not been added in 1.10.2
lastly, if you have read that the renaming doesn't work on all items, why even mention it -_-
