### ISSUE TITLE
Removing Mystcraft 'unlinked book' Crash

### ISSUE THREAD

**Issue by Nadiir** [stanhebben/MineTweaker3#369]
**Removing '_unlinked book_' recipe results in a Crash.**

**See: https://github.com/XCompWiz/Mystcraft-Issues/issues/166**

Note: Using '_/mt recipes hand_' with an '_Unlinked book_' produces "_No recipes for this item_".
Note: NEI won't display 'Unlinked book' recipe

`Description: Ticking memory connection

java.lang.IllegalArgumentException: Illegal character in scheme name at index 14: recipes.remove(Mystcraft:unlinkedbook);
    at java.net.URI.create(URI.java:852)
    at net.minecraftforge.common.ForgeHooks.newChatWithLinks(ForgeHooks.java:417)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:722)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 14: recipes.remove(Mystcraft:unlinkedbook);
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.parse(URI.java:3048)
    at java.net.URI.<init>(URI.java:588)
    at java.net.URI.create(URI.java:850)
    ... 11 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.net.URI.create(URI.java:852)
    at net.minecraftforge.common.ForgeHooks.newChatWithLinks(ForgeHooks.java:417)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:722)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@6156dc39
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.11.2
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 185433824 bytes (176 MB) / 1932787712 bytes (1843 MB) up to 1932787712 bytes (1843 MB)
    JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 94 mods loaded, 94 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJAAAA   AgriCraft{1.7.10-1.5.0} [AgriCraft](AgriCraft-1.7.10-1.5.0.jar) 
    UCHIJAAAA   aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes](AOBDBB-1.0.6.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar) 
    UCHIJAAAA   baublelicious{1.7.10-1.2.1} [Baublelicious](baublelicious-1.7.10-1.2.1.jar) 
    UCHIJAAAA   betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) 
    UCHIJAAAA   BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
    UCHIJAAAA   BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHIJAAAA   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJAAAA   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   ForbiddenMagic{1.7.10-0.575} [Forbidden Magic](Forbidden Magic-1.7.10-0.575.jar) 
    UCHIJAAAA   guideapi{1.7.10-1.0.1-20} [Guide-API](Guide-API-1.7.10-1.0.1-20.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   BloodArsenal{1.2-5} [Blood Arsenal](BloodArsenal-1.7.10-1.2-5.jar) 
    UCHIJAAAA   chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.8} [Carpenter's Blocks](Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAA   CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJAAAA   ExtraTiC{1.4.6} [ExtraTiC](ExtraTiC-1.7.10-1.4.6.jar) 
    UCHIJAAAA   FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ganysend{1.11.3} [Gany's End](Ganys End-1.11.3.jar) 
    UCHIJAAAA   ganysnether{1.8.3} [Gany's Nether](Ganys Nether-1.8.3.jar) 
    UCHIJAAAA   ganyssurface{1.12.8} [Gany's Surface](Ganys Surface-1.12.8.jar) 
    UCHIJAAAA   headcrumbs{1.7.4} [Headcrumbs](Headcrumbs-1.7.4.jar) 
    UCHIJAAAA   HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) 
    UCHIJAAAA   HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   JABBA{1.2.2} [JABBA](Jabba-1.2.2_1.7.10.jar) 
    UCHIJAAAA   journeymap{5.1.4p1} [JourneyMap](journeymap-1.7.10-5.1.4p1-unlimited.jar) 
    UCHIJAAAA   LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1-2.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAAAA   modtweaker2{0.9.6} [Mod Tweaker 2](ModTweaker2-0.9.6.jar) 
    UCHIJAAAA   Mystcraft{0.12.3.02} [Mystcraft](mystcraft-1.7.10-0.12.3.02.jar) 
    UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJAAAA   NetherOres{1.7.10R2.3.1} [Nether Ores](NetherOres-[1.7.10]2.3.1-22.jar) 
    UCHIJAAAA   ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
    UCHIJAAAA   OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJAAAA   OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCHIJAAAA   ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHIJAAAA   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHIJAAAA   recallstones{0.5.2} [Recall Stones](RecallStones-1.7.10-0.5.2.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   xreliquary{1.2} [Reliquary](Reliquary-1.2.257.jar) 
    UCHIJAAAA   Sanguimancy{1.7.10-1.1.9-33} [Sanguimancy](Sanguimancy-1.7.10-1.1.9-33.jar) 
    UCHIJAAAA   SpecialMobs{3.2.2} [Special Mobs](SpecialMobs-1.7.10-3.2.2.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.10.0} [Storage Drawers](StorageDrawers-1.7.10-1.10.0.jar) 
    UCHIJAAAA   StorageDrawersBop{1.7.10-1.1.1} [Storage Drawers: Biomes O' Plenty Pack](StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar) 
    UCHIJAAAA   StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack](StorageDrawers-Misc-1.7.10-1.1.2.jar) 
    UCHIJAAAA   StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack](StorageDrawers-Natura-1.7.10-1.1.1.jar) 
    UCHIJAAAA   supercraftingframe{1.7.10.3} [Super Crafting Frame](supercraftingframe-1.7.10.3.jar) 
    UCHIJAAAA   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHIJAAAA   ThaumcraftMobAspects{1.7.x-2B} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.x-2B-snapshot-18.jar) 
    UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAAAA   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar) 
    UCHIJAAAA   ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHIJAAAA   UtilityMobs{3.1.1} [Utility Mobs](UtilityMobs-1.7.10-3.1.1.jar) 
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJAAAA   aobd{2.9.2} [Another One Bites The Dust](AOBD-2.9.2.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Mantle Environment: Environment healthy.
    CoFHCore: -[1.7.10]3.1.2-325
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.1-22
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Stencil buffer state: Function set: ARB, pool: forge, bits: 8
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['butbut'/16, l='New World', x=-232.51, y=1.00, z=-1553.26]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
