### ISSUE TITLE
All recipes don't reload when using /mt reload from console

### ISSUE THREAD

**Issue by cj89898** [stanhebben/MineTweaker3#370]
I have to login to my server after every restart and manually type /mt reload even though I have it setup to run TWICE on server startup from console. No clue why this happens. I'm using the pack Project Ozone 2 on titan mode.

No errors are thrown when doing it on console or on client-side.

**Comment by cj89898** [comment]
This is the biggest issue on my server right now... Can somebody take a look into it?

**Comment by cj89898** [comment]
Okay, I found out it only loads the recipes for the users that were on the server at the time the command was launched. If they relog, they lose the recipes.

**Comment by jaredlll08** [comment]
Look, you are the only one that is reporting it. So it isn't high priority.

What version of FTBTweaks?

**Comment by cj89898** [comment]
Version 1.0.2

I realize it may be not high priority, but it is a bug where the mod doesn't work at all for updating recipes to client side

**Comment by jaredlll08** [comment]
Very weird, havnt had a report like this from any pack. It is really only
you that has the problem, do you customize the pack in any way?

**Comment by cj89898** [comment]
The only thing I'm customizing are the recipes. I am also using Thermos, I may add. I've never had this issue on my other 3 servers running thermos as well.

**Comment by jaredlll08** [comment]
What is thermos?

**Comment by cj89898** [comment]
Modded + Plugins

**Comment by jaredlll08** [comment]
Yea...  We don't support that. See if you can reproduce without thermos. If
you can, not our fault.

**Comment by cj89898** [comment]
Will test on the hour. (15min)

EDIT: Testing Now

**Comment by cj89898** [comment]
Does not work even with JUST forge

**Comment by jaredlll08** [comment]
ok yea... highly unlikely, I had the FTB beta testers test it, they returned no problem, so there are a fea things from here.

1) Are you using a customized version of Minetweaker / CraftTweaker?
2) Are you using a customized version of Modtweaker?
3) Are you using a customized version of FTBTweaks?
4) Have you customized your scripts in any way?
5) Have you customized your pack in any way (Project Ozone 2, if I am correct?)?
6) Have you customized anything about your pack that would make it different?
7) Have you customized anything about your server that would make it different?

**Comment by cj89898** [comment]
Nothing is customized at all. Only thing is the recipes I changed.

**Comment by jaredlll08** [comment]
Try without your custom recipes

**Comment by cj89898** [comment]
No... The custom recipes are the ones not showing unless I do /mt reload. All custom recipes created by the modpack author (aka the ones on the client and server) show just fine.

**Comment by jaredlll08** [comment]
That would have been good to know. Next time start with that :P

There should be a "common" folder or something of the sorts for FTBTweaks,
put your scripts in there, if there isn't, put them in the Titan folder.

**Comment by cj89898** [comment]
Sorry, I guess I never made that exactly clear. I've tried the titan folder too, didn't work.

EDIT: Put it in the common folder. Will have to wait for server restart in around 45 minutes.

**Comment by jaredlll08** [comment]
Does the client have the recipes?

**Comment by cj89898** [comment]
Client do not have the custom recipes I put in, no. That's the whole point of minetweaker right? I can customize the recipes on my server and have them update to the client, however that doesn't happen without /mt reload

**Comment by jaredlll08** [comment]
Sigh. No it does not work like that.
Look in your world folder you _should_ see a scripts folder in there, put
your custom scripts in there. I have no idea how it works with FTBTweaks,
but that folder should sync. If it does not. Then there I honestly nothing
I can do for you, and you will have to give your scripts to your players.

**Comment by cj89898** [comment]
It makes no sense at all, because I've done this exact thing before on Infinity Evolved Skyblock with ease! It must be either A. FTBTweaks/Utils/etc. or B. Minetweaker/Modtweaker/etc.

**Comment by jaredlll08** [comment]
And I dev all 3 of those. So yea... Shooting in the dark, just try the
thing I told you, the world/scripts/

**Comment by cj89898** [comment]
Just waiting on my server restart :)

**Comment by cj89898** [comment]
Should I test the common folder or the world folder?

**Comment by cj89898** [comment]
I've gone ahead and tested the world folder. Starting now.

**Comment by jaredlll08** [comment]
Oh sorry, my phone completely missed the first email, test the world
folder, that is the one that _should_ sync

**Comment by cj89898** [comment]
Like this, right? ServerFolder\SpawnWorld\scripts

**Comment by cj89898** [comment]
Did not sync, didn't even reload with /mt reload

**Comment by jaredlll08** [comment]
Then no idea

**Comment by cj89898** [comment]
Well is there even functionality to load from a world folder? Because I've NEVER seen that before. I really don't mean to be rude, but if it doesn't even load after /mt reload then I come to that conclusion.

**Comment by jaredlll08** [comment]
Heh I don't blame your rudeness, it was new to me too, but trust me, I have
had many a fight about load order, it could be FTBTweaks messing up, gimme
a while and I'll organize something for you :P

**Comment by cj89898** [comment]
Thanks for the help :)

**Comment by jaredlll08** [comment]
Is this fixed?

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
