### ISSUE TITLE
Using String.equals in script causes VM error (not yet implemented)?

### ISSUE THREAD

**Issue by cosmicdan** [stanhebben/MineTweaker3#371]
I can see in ZenCode specification that we have basic int less than/greater than conditional, but I'd like to do a string comparison. Closest I got was this:

```
# Only use M4's Block of Charcoal
for blockCharcoal in <ore:blockCharcoal>.items {
    recipes.remove(blockCharcoal);
    if blockCharcoal.name.equals("tile.metallurgy.charcoal.block") {
        mods.nei.NEI.hide(blockCharcoal);
    }
}

```

But this results in a crash:

```
Exception Details:
  Location:
    Metallurgy4.__script__()V @68: invokestatic
  Reason:
    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @68
    flags: { }
    locals: { top, top, 'java/util/Iterator', 'minetweaker/api/item/IItemStack' }
    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }
  Bytecode:
    0x0000000: 120b b800 11b9 0017 0100 b900 1d01 004d
    0x0000010: 2cb9 0023 0100 9900 592c b900 2701 00c0
    0x0000020: 0029 4eb2 002f 2db9 0035 0200 5701 1236
    0x0000030: bd00 3859 1239 123b 59c7 0008 5701 a700
    0x0000040: 06b8 0041 b800 4753 b900 4b02 00b9 004e
    0x0000050: 0100 9900 072d b800 5412 56b8 005c 2db9
    0x0000060: 0060 0100 b800 5c12 56b8 005c a7ff a4b2
    0x0000070: 002f 1262 1239 b800 6812 69bd 0013 5912
    0x0000080: 3912 6bb8 0011 5359 1236 126b b800 1153
    0x0000090: 5912 6c12 6bb8 0011 5359 126d 126b b800
    0x00000a0: 1153 5912 6e12 6bb8 0011 5359 126f 126b
    0x00000b0: b800 1153 5912 7012 6bb8 0011 5359 1271
    0x00000c0: 126b b800 1153 5912 7212 6bb8 0011 5301
    0x00000d0: b900 7604 0012 6212 39b8 0068 bb00 7859
    0x00000e0: b700 7b59 127d bb00 7859 b700 7b59 127f
    0x00000f0: 1281 b800 85b9 008b 0300 5759 128d 126c
    0x0000100: bd00 8f59 1239 1291 b800 8553 5912 3612
    0x0000110: 93b8 0085 53b8 0098 b900 8b03 0057 b800
    0x0000120: 9db9 008b 0300 57b8 009d b900 a102 00b8
    0x0000130: 00a4 b1                                
  Stackmap Table:
    append_frame(@16,Top,Top,Object[#31])
    full_frame(@65,{Top,Top,Object[#31],Object[#41]},{Null,Object[#166],Object[#166],Integer,Object[#168]})
    full_frame(@68,{Top,Top,Object[#31],Object[#41]},{Null,Object[#166],Object[#166],Integer,Object[#56]})
    same_frame(@89)
    chop_frame(@111,1)
```

Any advice? Is this even possible?

Using the 1.7.10 version if that matters.

**Comment by jaredlll08** [comment]
Uh I'm honestly not sure, try `==`
If that doesn't work, just hardcode the hide in, would be more performative anyway

**Comment by cosmicdan** [comment]
== results in an unknown operand or some such generic error that doesn't give me much to work with.

What do you mean by hardcode? You mean type it out manually for every item, and not use a for loop at all? Performance is not an issue here, making the scripts small and readable is important though. I'm just wondering if ZenCode supports this yet mainly, is all. I know the engine is still under development. If I get confirmation from dev that it's not yet implemented, then yes I will have to hardcode it.

**Comment by jaredlll08** [comment]
Well I mean you are only hiding one item, so just hardcode that item.

I'm not fully versed in zenscript, I'm only the maintainer, but as far as I
know, it isn't possible to do string stuff like this.

**Comment by cosmicdan** [comment]
Oh sorry, haha yes you are right. I am actually trying to do a NOT equal, to hide everything else. I was just testing with a more basic .equals and == first since they're less fickle than the whole ! or != placement in most languages :)

No problem, it's only for hiding some items so it's not a show stopper for me or anything. Just looking forward to get some advanced ZenScript feedback whenever possible. Maybe I will take a look at the ZenCode internals myself sometime, if I can.

**Comment by jaredlll08** [comment]
@cosmicdan well the equal code was in, it was just commented out, can I give you a test version?

**Comment by cosmicdan** [comment]
Sure thing, would ve happy to try it :)

On 22 Aug 2016, Jared notifications@github.com wrote:

> @cosmicdan well the equal code was in, it was just commented out, can I
> give you a test version?

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by jaredlll08** [comment]
Try this version :)
http://blamejared.com:8080/job/CraftTweaker/5/

**Comment by cosmicdan** [comment]
Hi Jared,

Unfortunately this still results in the same VM exception as before. I guess the code you uncommented is part of an unfinished implementation or something.

I also tried something simple like:

```
print("string".equals("string"));
```

Which gave the same VM exception.

Not a big deal if you don't know though, as I said I was just curious if it was possible.

**Comment by jaredlll08** [comment]
Can you try

```
print("string" equals "string"); or variations of that please :)
```

**Comment by cosmicdan** [comment]
Ok, I tried a few things and they resulted in the errors below:

```
print("string" equals "string");
```

Result:
Error parsing Metallurgy4.zs:8 -- ) expected

```
print("string" equals("string"));
```

Result:
Error parsing Metallurgy4.zs:8 -- ) expected

```
print(equals("string", "string"));
```

Result:
ERROR: Metallurgy4.zs:8 > could not find equals
ERROR: Error executing Metallurgy4.zs: null
java.lang.ArrayIndexOutOfBoundsException

```
print("string" == "string");
```

Results in:

```
ERROR: Error executing Metallurgy4.zs: Class java.lang.String does not implement the requested interface stanhebben.zenscript.value.IAny
java.lang.IncompatibleClassChangeError: Class java.lang.String does not implement the requested interface stanhebben.zenscript.value.IAny
    at Metallurgy4.__script__(Metallurgy4.zs:8)
    at __ZenMain__.run(Metallurgy4.zs)
    at minetweaker.runtime.MTTweaker.load(MTTweaker.java:161)
    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:75)
    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:667)
    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:116)
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at fastcraft.at.a(F:978)
    at fastcraft.H.aq(F:36)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

The last one or two seems closest to "working", if that means anything lol. I looked at the code though, I think maybe the equals method needs to be implemented in the IAny interface (at https://github.com/jaredlll08/CraftTweaker/blob/master/ZenScript/src/main/java/stanhebben/zenscript/value/IAny.java ) but I'm not sure? I had a look at ZenTypeString.java and the defineEquals method is there... my guess is the code is there but for whatever reason it's just not attached to the String functions or something.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately

**Comment by jaredlll08** [comment]
@cosmicdan the support will be in the next CraftTweaker release
