### ISSUE TITLE
Cannot cast byte[] to minetweaker.data.IData

### ISSUE THREAD

**Issue by AlexanderBulanov** [stanhebben/MineTweaker3#372]
I am having problem modifying Thermal Expansion machine recipes for a modpack. I followed the code listed here http://minetweaker3.powerofbytes.com/forum/viewtopic.php?f=4&t=474 and tried using it myself. However, I get the error "Cannot cast byte[] to minetweaker.data.IData. After that I have tried to execute "/mt hand" command while holding Thermal Expansion's Pulverizer, and the command printed the exact syntax I have already typed into my script. I tried to find working code for changing Thermal Expansion recipes, asked the question on FTB subreddit - had no luck so far. Am I overlooking something, or there is a legitimate bug with the script?

My script: http://pastebin.com/JBkd2Lsw

**Comment by jaredlll08** [comment]
You are overlooking the rest of the issues here, it's been reported before,
known bug, not an easy fix, but will be fixed eventually

**Comment by AlexanderBulanov** [comment]
Thanks for the quick reply. Do you know of any workarounds by any chance as of now?

**Comment by jaredlll08** [comment]
Unfortunately not

**Comment by LakMoore** [comment]
I think I had something similar and I just dropped one of the casts.  ZenScript seemed to be happier to determine the type itself than be told what the type was.

**Comment by jaredlll08** [comment]
Closed in the the Java 8 branch of Crafttweaker

**Comment by AlexanderBulanov** [comment]
For anyone interested in how to fix this issue for Mine/Crafttweaker 3.0.13 and below (as this issue is fixed in version 3.0.14 and above for Minecraft 1.10.2+), just remove the entire Sidecache NBT tag when working with Thermal Expansion machine/device recipes. The game will correctly assign the Sidecache NBT tag once machine is placed in-world. Incorrect/Correct examples of variable declaration are listed below.

Incorrect Variable Declaration (Even though it's retrieved by using "/mt hand" command, this block name is not recognized as valid Zenscript code in Mine/Crafttweaker 3.0.13 and below):
var resonant_magma_crucible = <ThermalExpansion:Machine:4>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2] as byte[] as byte[], Level: 3 as byte, Augments: [{Slot: 0, id: 5167 as short, Count: 1 as byte, Damage: 0 as short}, {Slot: 1, id: 5167 as short, Count: 1 as byte, Damage: 32 as short}, {Slot: 2, id: 5167 as short, Count: 1 as byte, Damage: 16 as short}]});

Incorrect Variable Declaration (Valid Zenscript code, client crash when placing crafted machine/device):
var resonant_magma_crucible = <ThermalExpansion:Machine:4>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, SideCache: [1, 1, 2, 2, 2, 2], Level: 3 as byte, Augments: [{Slot: 0, id: 5167 as short, Count: 1 as byte, Damage: 0 as short}, {Slot: 1, id: 5167 as short, Count: 1 as byte, Damage: 32 as short}, {Slot: 2, id: 5167 as short, Count: 1 as byte, Damage: 16 as short}]});

Correct Variable Declaration:
var resonant_magma_crucible = <ThermalExpansion:Machine:4>.withTag({RSControl: 0 as byte, Facing: 3 as byte, Energy: 0, Level: 3 as byte, Augments: [{Slot: 0, id: 5167 as short, Count: 1 as byte, Damage: 0 as short}, {Slot: 1, id: 5167 as short, Count: 1 as byte, Damage: 32 as short}, {Slot: 2, id: 5167 as short, Count: 1 as byte, Damage: 16 as short}]});
