### ISSUE TITLE
net.minecraft.item.ItemStack cannot be cast to java.lang.Character- Agricraft Error

### ISSUE THREAD

**Issue by TheDeathFarmer** [stanhebben/MineTweaker3#373]
My Modpack Scripts
https://www.dropbox.com/s/fojkhl30yhybc5c/Modpack%20Scripts.zip?dl=1

**Comment by jaredlll08** [comment]
And the minetweaker.log file?

**Comment by jaredlll08** [comment]
If you can't provide the log, I can't help.

**Comment by jaredlll08** [comment]
If this is an agricraft error, this is the wrong repo.
