### ISSUE TITLE
MT3 using unlocalized name?

### ISSUE THREAD

**Issue by Wyrrrd** [stanhebben/MineTweaker3#376]
Hi, uncommon request for 1.7.10 here:

I am trying to change the name and behaviour of Galacticraft's Titanium Ingot with Minetweaker.
Strangely the QuantumFlux Titanium Ingot responds to every name change I apply to the GC ingot, while the GC ingot always takes the ore dictionary entry from the QF ingot.

Critical mod setup:
- Galacticraft 3.0.12
- QuantumFlux 1.3.4
- Minetweaker 3.0.10B

I am not sure where this is coming from (my suggestion is, they have the same unlocalized name), so I am filing issues on GC and QF, too.

[Galacticraft Issue](https://github.com/micdoodle8/Galacticraft/issues/2270)
[QuantumFlux Issue](https://github.com/joekaiser/QuantumFlux/issues/111)

Thanks in advance,
Wyrrrd

![unbenannt](https://cloud.githubusercontent.com/assets/11527443/18447132/a0a67846-7925-11e6-80cc-7dcea20c8675.png)

**Comment by stanhebben** [comment]
This is indeed because they both use the same unlocalized name.

I'm afraid there is nothing I can do. One of the mod authors would have to change the unlocalized name.

I will close this ticket.

**Comment by Wyrrrd** [comment]
Another part of the problem is that somehow I cannot remove ore dictionary entries.
`<ore:entryname>.remove(<mod:itemname>);` doesn't work at all. Can you maybe point me to a solution on this?

Anyways, thanks for your time :)

Edit: Problem was related to something else with AOBD, nevermind... -.-
