### ISSUE TITLE
[1.7.10] [Mekanism] Why do Mekanism machines need NBT tags on input to match exactly?

### ISSUE THREAD

**Issue by Robijnvogel** [stanhebben/MineTweaker3#380]
See https://github.com/aidancbrady/Mekanism/issues/3799

**Comment by jaredlll08** [comment]
That is because of how mekanism does things, nothing we can do on our side.

**Comment by Robijnvogel** [comment]
Then I'm glad that today I've finally found a (workaround) way to nest for-loops, so I can iterate through all possible NBT tags while iterating through all items I want to use with those NBT tags. :)

Fyi, this issue was more to document/notify that I've asked this question on the Meknanism Issue tracker.
