### ISSUE TITLE
json help

### ISSUE THREAD

**Issue by mightydanp** [stanhebben/MineTweaker3#381]
i am having trouble with a script that i cannot find someone to help me

ERROR: Natura.zs:6 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:7 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:8 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:9 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:24 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:25 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:26 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:27 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:31 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:32 > int[] doesn't have such operator
ERROR: Natura.zs:32 > Cannot cast int[] to minetweaker.item.IIngredient
ERROR: Natura.zs:33 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:34 > int[] doesn't have such operator
ERROR: Natura.zs:34 > Cannot cast int[] to minetweaker.item.IIngredient
ERROR: Natura.zs:39 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:40 > a method available but none matches the parameters (int[])
ERROR: Natura.zs:41 > a method available but none matches the parameters (int[])
ERROR: Error executing Natura.zs: Bad type on operand stack
Exception Details:
  Location:
    Natura.**script**()V @115: ifnonnull
  Reason:
    Type integer (current frame, stack[3]) is not assignable to reference type

http://pastebin.com/wVx7ZVu8

**Comment by Voidi** [comment]
The makeStack function only supports int not int[].

**Comment by mightydanp** [comment]
any way i can fix that

**Comment by jaredlll08** [comment]
wow, I got absolutely no idea what you are trying to do, but whatever it is, is completely wrong.
There may be an easier way t do it, so what are you trying to do exactly?

**Comment by mightydanp** [comment]
var naturaOverworldLogsTypes = [0, 1, 2, 3] as int[];
is sepost to represent that there are ints 0-3 so if i do this
var naturaOverworldLogs1 = natura:overworld_logs.definition.makeStack(naturaOverworldLogsTypes);
it is telling naturaOverworldLogs1  that natura:overworld_logs has a metadata 0-3

so something like this
recipes.addShapeless(naturaOverworldPlanks1 \* 2, [naturaOverworldLogs1]);
would be read as 
recipes.addShapeless(natura:overworld_planks:0\* 2, [natura:overworld_logs:0]);
recipes.addShapeless(natura:overworld_planks:1\* 2, [natura:overworld_logs:1]);
recipes.addShapeless(natura:overworld_planks:2\* 2, [natura:overworld_logs:2]);
recipes.addShapeless(natura:overworld_planks:3\* 2, [natura:overworld_logs:3]);

**Comment by jaredlll08** [comment]
I got no idea where you even got that idea from, but that functionality
isn't even available if you had to make a mod in Java, I would keep the
Metadata in an array and loop over the array.

**Comment by mightydanp** [comment]
in 1.7.10 i used this function and had no problem i have no idea why its not working in 1.10

**Comment by jaredlll08** [comment]
I refuse to believe that, if you can show me a script AND a minetweaker.log showing this working, then I'll believe you and fix this 'issue'. Until then, I have given you a work around, and this is user error, so I will be closing this.

**Comment by mightydanp** [comment]
Alright ill give you a script in 1.7.10 that uses the same thing and i will show you that it loaded in 1.7.10 . You already it dont work in 1.10

**Comment by mightydanp** [comment]
http://pastebin.com/jcN3mfgJ
line 1495 you can see the script loading.

the whole script
http://pastebin.com/A2gPdGSP
it uses the same thing i just showed you.

**Comment by jaredlll08** [comment]
Line 30 and 31.
That starts a loop, and looks through the integers in the array, hence, not
doing what you are doing.
