### ISSUE TITLE
IC2 Compressor Recipe problem (in stuck x)

### ISSUE THREAD

**Issue by chaos234** [stanhebben/MineTweaker3#383]
Hey,

since I added GregTech 5 Unofficial to the FTB MP which I play with some others, we were not be able to craft any diamond blocks so I added back the recipe as shown below:

`import mods.ic2.Compressor;

Compressor.addRecipe(minecraft:diamond_block, minecraft:diamond*9);`

But if I use this the "in stuck" number raises still up and I can't get ride of them. Also there is no remove(Recipe) methode which means that I must life with this (if it doesn't matter) or I must change the recipes for all other Items which needs diamonds or you have any Idea how to solve this problem.

Will be fine if a solution is found without getting "in stuck" anymore.

**Comment by jaredlll08** [comment]
I understood about half of that, what in stuck?
Also what do you mean by the remove?

**Comment by chaos234** [comment]
If you have a recipe which you won't want then you can call the methode(s) remove(); and/or removeRecipe();

But I can't remove my added Recipe to get a Diamond Block from 9 Diamonds in a IC2 Compressor. And now when the ZS-Script is called, it get stucked as following:

> WARNING: 1 modifications were stuck
> INFO: Stuck: Adding compressor recipe for Block of Diamond

This comes from this mod because it tries to add the recipe again even it is already registered which confuses me because it should recognize that this recipe is already registered and since the both methodes above are not useable for the IC2 Machines I can't do anything else against this.

Well, I can write an add.Shaped/addShapless line but it will be glad if it will work with IC2 Machines without getting the message(s) above.

**Comment by jaredlll08** [comment]
Simple, don't use /mt reload.

**Comment by chaos234** [comment]
Then this cmd must be reworked because it is the only way to include the wanted recipe without restarting the server and the client (some players needing over 15 minutes to start the client).

So there must be an additional methode called which checks if the wanted recipe is already available and if so it should ignore the line otherwise it should add the recipe and on /mt reload it should also check the recipe and should skip to add it if it exists.

Means in fact we must use /mt reload because we are not able to restart the server and the hole clients uncountable times with at last 15 minutes to load so it is up to you to fix this issue which is in my eyes an issue because there is no check against existing recipes.

**Comment by jaredlll08** [comment]
No. The command works fine. Give your scripts to the player or put the
scripts in /world/scripts.

**Comment by chaos234** [comment]
I add the script to the script folder in the root folder of the MP this means that the path on client and server is MPname/minecraft/scripts where all ZS-Scripts are stored and world/scripts is still empty.

Other scripts are stored under MPname/minecraft/<difficult>/scripts so I never used world/scripts

Side question: How can I tell the recipe that I wand all kinds of diamonds to be useable for a diamond block? Writing for each a addRecipe-Line is possible but also horrible I think but I found nothing in the wiki for that :(

**Comment by jaredlll08** [comment]
Use oredict,
Does each client have the script? If not, give it to them. If you don't
want to do that, put it in /world/scripts/

**Comment by chaos234** [comment]
Ok, so this means I should use "oredict:diamond" as "minecraft:diamond"?
Also I'll try it out with /world/scripts (which means that the scripts in there will be shared to all players?)

**Comment by jaredlll08** [comment]
Yes.

**Comment by chaos234** [comment]
I found out that another recipes uses metadat for the machine and the machine which I want to have has the ID 575:1 so is it correct if I type: addRecipe(AdvancedMachines:blockAdvMachine:1, ...); ?

**Comment by chaos234** [comment]
script was added on the server in /world/scripts but it does not take affect if I look in my client in NEI so it wasn't send to the client ...

**Comment by jaredlll08** [comment]
Then there is nothing I can do for you, give the users the scripts or else
it won't work.

**Comment by chaos234** [comment]
Ok
