### ISSUE TITLE
Mekanism remove problem

### ISSUE THREAD

**Issue by Maxwelljones** [stanhebben/MineTweaker3#384]
I've been struggling for a while with mekanism and minetweaker to remove/change some recipes.
This works with other mods, but not with mekanism.

The remove ie: `recipes.remove(<Mekanism:MachineBlock:10>);` **doesn't work on map load.** 
My new recipe **works on map load** `recipes.addShaped(<Mekanism:MachineBlock:10>, [[...]]);`

I have to manually do a /mt reload. Then the removed recipe finally works as intended (and gets removed).
Anything you can help me with?

MC 1.7.10
Mekanism-1.7.10-9.1.0.281
MineTweaker3-1.7.10-3.0.10B
ModTweaker2-0.9.6
Minetweaker.log [http://pastebin.com/Bs9aNXdQ](http://pastebin.com/Bs9aNXdQ)

**Comment by jaredlll08** [comment]
mekanism adds their recipes too late for us to edit, go shout at them (my shouting at fell to deaf ears)
Also we no longer support 1.7.10, sorry.
