### ISSUE TITLE
Help, error executing: null

### ISSUE THREAD

**Issue by Siigari** [stanhebben/MineTweaker3#385]
I have this file right now. I get an error when I try to load the script (tconstruct.zs)

import mods.tconstruct.Drying;

mods.tconstruct.Drying.removeRecipe(tconstruct:edible:10);

mods.tconstruct.Drying.addRecipe(minecraft:rotten_flesh, tconstruct:edible:10, 12000);

modtweaker 1.10.2-2.0.3
crafttweaker 1.10.2-3.0.11

1.10.2 MC Forge 2098

**Comment by LakMoore** [comment]
C'mon guy...

Start by reading the manual: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support

Then copy the examples and get them working, then tweak them to fit your needs.

Hint:  these are important:   <      and      >
and the case is important too  "TContstruct" rather than "tconstruct"

Also this is the MineTweaker issues repository and you are using ModTweaker, which is here: https://github.com/jaredlll08/ModTweaker

**Comment by jaredlll08** [comment]
Don't forget, github strips `<>`, and I didn't know the wiki got updated,
that is why I hadn't replied yet.

**Comment by Siigari** [comment]
So like this?

http://i.imgur.com/OdvYtJ4.png

Because now I get this error: http://i.imgur.com/Kd8Twmd.png

**Comment by jaredlll08** [comment]
Yes, see if it works.

**Comment by Siigari** [comment]
No, edited reply.

http://i.imgur.com/Kd8Twmd.png

**Comment by Siigari** [comment]
http://pastebin.com/ZrGk18EP

**Comment by jaredlll08** [comment]
I have to ask. But do you even have Tinkers Construct installed?

**Comment by Siigari** [comment]
Yeah, have a look at my jars.

http://i.imgur.com/V4yf3xF.png

**Comment by jaredlll08** [comment]
ok well the syntax is like this

```
mods.tconstruct.Drying.addRecipe(output, input, time);
```

It seems Lak was wrong on the capitalization.

Also if you continue sending pictures instead of logs, I will have to start refusing help.

**Comment by Siigari** [comment]
Alright, well I sent a pastebin log. This is my first time really fleshing out an issue on github so I'm listening :) Anyway, so everything is typed in properly, according to you guys, correct?

**Comment by jaredlll08** [comment]
Yea, I'm going to need you to test it with the syntax I showed you, so going based on your original issue,

```
mods.tconstruct.Drying.addRecipe(<minecraft:rotten_flesh>, <tconstruct:edible:10>, 12000);
```

If you could send me a minetweaker.log file after running that, it would help :)

**Comment by Siigari** [comment]
Okay restarted client.

Full text of tconstruct.zs is: http://pastebin.com/4uhWbbyC

Error log is: http://pastebin.com/0q7ERst7

**Comment by jaredlll08** [comment]
ok yea, this is a modtweaker issue, just fixed it, a release will happen at some point, can't give a time

**Comment by Siigari** [comment]
Thanks my friend for being patient with me. I sent you an email to the email listed on your profile.

**Comment by Siigari** [comment]
Hey man! Did you get the update shipped?

**Comment by jaredlll08** [comment]
yesterday, latest release

**Comment by Siigari** [comment]
http://pastebin.com/qSr1PgVs Crash on load :(

**Comment by Siigari** [comment]
2.0.5?

**Comment by jaredlll08** [comment]
Update crafttweaker

**Comment by jaredlll08** [comment]
Update crafttweaker, not modtweaker
