### ISSUE TITLE
am i doing something wrong?

### ISSUE THREAD

**Issue by mightydanp** [stanhebben/MineTweaker3#386]
i cannot see what I am doing wrong

[18:29:54] [Client thread/INFO]: [CHAT] ERROR: ironChests.zs:37 > a method available but none matches the parameters (minetweaker.item.IItemStack, any[], any[], any[])

http://pastebin.com/HtMxMUC4

**Comment by Voidi** [comment]
the addShaped Signature is `minetweaker.item.IItemStack, [any[], any[], any[]]`

**Comment by jaredlll08** [comment]
Yea, your script syntax is wrong, please read the wiki, whenever you see "a method available nut none matches the parameter..." it is user error.

**Comment by mightydanp** [comment]
i have checked the wiki I just want to understand where in my code that I am doing wrong so that i dont keep making the same mistake

**Comment by LakMoore** [comment]
recipes.addShaped(chest,
          [screwDriver, plate, screw],
          [plate, chest, plate],
          [screw, plate, hammer]);

becomes 

 recipes.addShaped(chest, [
          [screwDriver, plate, screw],
          [plate, chest, plate],
          [screw, plate, hammer]
]);

see the extra brackets.  addShaped takes two arguments, you are passing in four!
