### ISSUE TITLE
CraftTweaker overload log durring world loading

### ISSUE THREAD

**Issue by 0Navis0** [stanhebben/MineTweaker3#388]
CraftTweaker totally overload the log durring Minecraft world loading by repeating this part of log so many times. http://pastebin.com/bY114q7F
It has for consequence than Minecraft use until 4Gb of memory only for the log and the log files weigh until 1Gb. Minecraft slow down and lag a lot because of that.

**Comment by jaredlll08** [comment]
Not a minetweaker error. Removed minetweaker and it will still happen

**Comment by 0Navis0** [comment]
Oh so it comes maybe from JEI surely,

**Comment by jaredlll08** [comment]
nope, keep on removing the mod listed until the error stops, whatever mod you just removed, is the culprit
