### ISSUE TITLE
Hide from NEI function not working properly 

### ISSUE THREAD

**Issue by wormzjl** [stanhebben/MineTweaker3#39]
In the script I got the following commands:

import mods.nei.NEI;
NEI.hide(<ForgeMicroblock:microblock>);
NEI.hide(<BuildCraft|Transport:pipeFacade>);
NEI.hide(<appliedenergistics2:item.ItemFacade>);
NEI.hide(<ExtraUtilities:microblocks>);

But they are not hidden in NEI before I use a /mt reload command
Which means that each time I enters the game, I need to reload the scripts to make it work.
Is it a problem on the side of minetweaker or NEI

**Comment by Cherry** [comment]
Experiencing the same issue. Any fix in sight, or other possible resolution?

**Comment by vanceza** [comment]
I'm seeing the exact same problem (I wrote the same script independently). I'll look into what's happening if I can figure out the source.

As a workaround, NEI can filter out items by mod, so if you're writing a modpack you can ship a default config with a "blacklist" of mods to not display until the player enables them. That works for ForgeMicroblocks and ExtraUtilities, but not Applied Energistics facades.

**Comment by jaredlll08** [comment]
NEI support is broken, and seems to be unfixable due to how hacky NEI actually is. this has been resolved in 1.8.x due to JEI
