### ISSUE TITLE
SSP can only be joined one time after game start 

### ISSUE THREAD

**Issue by dillasyx** [stanhebben/MineTweaker3#391]
I thought it's caused by More Planets, but he says it's caused by MT3
here is the problem:
https://github.com/SteveKunG/MorePlanets/issues/11

**Comment by jaredlll08** [comment]
Modtweaker issue, and modtweaker does not support 1.7.10 anymore

**Comment by dillasyx** [comment]
@jaredlll08 isn't it maybe possible to fix this last bug? it's the last bug in my modpack and i would like to release it without bugs. i would pay a small amount, if this would help. it's only this bug. please

**Comment by jaredlll08** [comment]
Look, move on from 1.7.10, it is an extremely old version, and I choose to not support it. If I released the fix for this, then people would get their pitchforks and say "well why didn't you fix my issue?!" and that is something that I do not want to deal with.

**Comment by dillasyx** [comment]
Yeah okay. The problem is, I'm working on this modpack for a long time and a lot of the mods are still 1.7.10, so i try to finish it to end the project with a finished product, but i have to accept your decision. Thanks anyway

**Comment by dillasyx** [comment]
Okay one last question, is it possible, that you could send me the src/java folder incl all libs you used, so i can try it by myself? because i couldn't figure out which one from github to choose and minetweaker api also and there are even more missing :/

**Comment by dillasyx** [comment]
Found the reason... One of the scripts were broken, but minetweaker didn't say it and only on second join it doesn't work
