### ISSUE TITLE
Complete mod failure, when loading world

### ISSUE THREAD

**Issue by Shahelion** [stanhebben/MineTweaker3#393]
Can't even load a world, it just goes back to the menu.

https://gist.github.com/Zsashas/1407952808bfddcf38f7ce7e1a004387

**Comment by jaredlll08** [comment]
Upgrade to crafttweaker.

**Comment by Shahelion** [comment]
This is in 1.7.10... isn't CraftTweaker the mod for newer versions?

Also, I may have found what was wrong...it didn't like me using the AE2 Grinder for custom recipes, once I removed that, it was fine.

This is the template:

//Grinder
//InputStack, OutputStack1, Turns, OutputStack2, OutputStackChance2, OutputStack3, OutputStackChance3
mods.appeng.Grinder.addRecipe(<minecraft:sandstone>, <minecraft:sand> * 2, 4, <minecraft:sand>, 0.8, <minecraft:sand>, 0.6);

**Comment by jaredlll08** [comment]
Yes, which BTW is not supported anymore. There are 1.7.10 crafttweaker versions.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
