### ISSUE TITLE
[1.7.10] Scripts keep reloading every single world load both single/multiplayer.

### ISSUE THREAD

**Issue by StoneLegion** [stanhebben/MineTweaker3#395]
Could we have an option to disable or a fix on world load/connect to not have Scripts reloading again. Since it already happens on client load.

**Comment by jaredlll08** [comment]
Scripts need to reload on servers incase servers have different scripts that they sent to the client

**Comment by StoneLegion** [comment]
So we can't even have an option? Would you like to play on a pack with 3mb's worth of scripts loaded each time. We don't modify the server scripts though could do a md5 check or just allow override to prevent it to save solid packs that don't need new changes.

**Comment by jaredlll08** [comment]
no you don't get an option. The first time the script load is when the client connects to the server, so if I implemented this, it would require clients to connect to single player, then connect to a server.
