### ISSUE TITLE
Need help with a Parsing Error

### ISSUE THREAD

**Issue by WitherBlaster** [stanhebben/MineTweaker3#397]
I tried using MineTweaker to change some 'recipes' in AgriCraft, but everytime I load the game, I get these errors.

> ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected

> ERROR: Error parsing AgriCraft Custom Products.zs:5 -- ; expected

> ERROR: Error parsing AgriCraft Custom Soils.zs:3 -- ; expected

Here are the script files I made (changed to .txt because GitHub doesn't support .zs).
[AgriCraft Custom Soils.txt](https://github.com/stanhebben/MineTweaker3/files/671242/AgriCraft.Custom.Soils.txt)
[AgriCraft Custom Base Blocks.txt](https://github.com/stanhebben/MineTweaker3/files/671243/AgriCraft.Custom.Base.Blocks.txt)
[AgriCraft Custom Products.txt](https://github.com/stanhebben/MineTweaker3/files/671241/AgriCraft.Custom.Products.txt)

I've tried everything I can think of to fix it, but nothing works. Please tell me what I'm doing wrong.

**Comment by jaredlll08** [comment]
importing just means that you don't need to type the full name, you still need to type the machine / calling name, such as:
`BaseBlock.clear(xyz);`

**Comment by WitherBlaster** [comment]
Changed it for base block, but I'm still getting the same error.
Here's the new script.
`import mods.agricraft.growing.BaseBlock;`
`BaseBlock.clear(<AgriCraft:seedTaintedRoot>);`

**Comment by jaredlll08** [comment]
post your minetweaker log please

**Comment by WitherBlaster** [comment]
```
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected
ERROR: Error parsing AgriCraft Custom Products.zs:5 -- ; expected
ERROR: Error parsing AgriCraft Custom Soils.zs:3 -- ; expected
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected
ERROR: Error parsing AgriCraft Custom Products.zs:5 -- ; expected
ERROR: Error parsing AgriCraft Custom Soils.zs:3 -- ; expected
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected
ERROR: Error parsing AgriCraft Custom Products.zs:5 -- ; expected
ERROR: Error parsing AgriCraft Custom Soils.zs:3 -- ; expected
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: Error parsing AgriCraft Custom Base Blocks.zs:3 -- ; expected
ERROR: Error parsing AgriCraft Custom Products.zs:5 -- ; expected
ERROR: Error parsing AgriCraft Custom Soils.zs:3 -- ; expected

```

**Comment by jaredlll08** [comment]
try without the imports please, like use the full name

**Comment by WitherBlaster** [comment]
Still same error. Not sure if I used the right name, though.

`mods.agricraft.growing.BaseBlock.clear(<AgriCraft:seedTaintedRoot>);`

**Comment by jaredlll08** [comment]
ok, I really don't know, I don't add support for Agricraft, and your script looks correct, so report to agricraft.

**Comment by WitherBlaster** [comment]
Ok, I'll do that. Thanks for the help!
