### ISSUE TITLE
TokenException ¦

### ISSUE THREAD

**Issue by AeroyrHwrdd** [stanhebben/MineTweaker3#399]
One of the recipes in Growthcraft uses the character ¦, and usual one.  Minetweaker is having problem parsing this character. 

I can't do anything about this. I don't have knowledge to change the name of the block inside a mod. 

Should I try zzzzz config instead?

**Comment by jaredlll08** [comment]
you need to make an issue with Growthcraft. They should not be using a ¦ in their modid

**Comment by AeroyrHwrdd** [comment]
For reference: I checked with a full pipe | and that is a working replacement. All registers fine with it.
