### ISSUE TITLE
Minetweaker doesn't load added recipes

### ISSUE THREAD

**Issue by SneakyDevil** [stanhebben/MineTweaker3#400]
Running 1.7.10 and removed some recipes I had added a while back, but now whenever the game starts up or when /mt reload is done I get and error and all added recipes just won't load BUT they will get removed...
"ERROR: Error executing MineTweakerRecipeMaker: Index 0, Size: 0"

I do realize that MTRM is a separate mod, but to my limited knowledge MTRM just helps make recipes and has nothing to do with loading them.

[scripts.zip](https://github.com/stanhebben/MineTweaker3/files/681918/scripts.zip)

**Comment by jaredlll08** [comment]
Neither 1.7 or Mtrm is supported.

**Comment by SneakyDevil** [comment]
Not even a "oh yeah, that was a known issue you forgot a semicolon somewhere"? Cool thanks.

**Comment by jaredlll08** [comment]
Nope, especially not when it isn't a script issue or a mod issue of mine.
