### ISSUE TITLE
Will you port MineTweaker on 1.10.2

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#401]
I think that it is important mod because it can fix balance very, very good + maybe all interesting mods are ported on 1.10.2

**Comment by jaredlll08** [comment]
Use Crafttweaker. 
https://minecraft.curseforge.com/projects/crafttweaker

**Comment by stanhebben** [comment]
As a confirmation, CraftTweaker is indeed the successor to MineTweaker and the one to be used for 1.8+

**Comment by jaredlll08** [comment]
Yes. Read the mod page.

Edit, I'm an idiot, I thought that was a question, didn't know you answered it Stan X_X
