### ISSUE TITLE
.addAll and .mirror "No such member..."

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#403]
I was trying to unify some tungsten ores from Electrical Age and Magneticraft via ore dictionary.

The wiki states that i could use this:

`<Magneticraft:tungsten_ore>.add(<Eln:Eln.Ore:5>);`
`<Eln:Eln.Ore:5>.mirror(<Magneticraft:tungsten_ore>);`

`<Magneticraft:item.ingotTungsten>.add(<Eln:Eln.sharedItem:517>);`
`<Eln:Eln.sharedItem:517>.mirror(<Magneticraft:item.ingotTungsten>);`

`<ore:dustTungsten>.add(<Eln:Eln.sharedItem:6>);`
`<Eln:Eln.sharedItem:6>.mirror(<ore:dustTungsten>);`

But i just get:

`ERROR: > No such member in minetweaker.item.IItemStack: addAll`
`ERROR: > No such member in minetweaker.item.IItemStack: mirror`

**Comment by jaredlll08** [comment]
You are trying to use oredictionary commands on itemstacks... Please read
the wiki.

**Comment by ghost** [comment]
Thanks. I'm an idiot. Sorry.
