### ISSUE TITLE
Bug with AE2 (and possibly other mods) compatibility...

### ISSUE THREAD

**Issue by deeredman1991** [stanhebben/MineTweaker3#406]
So when you disable channels in the Applied Energistics config file it removes blocks like the controller from the game. Unfortunately if the recipe has been changed in a pack like Sky Factory 2.5 this causes Minetweaker to crash and will not load any of the other Minetweaker recipes...

My suggested fix for this would be; when reading scripts if the recipe for an item that does not exist is being modified; just tell the player that the item does not exist in the chat but do not throw and error instead keep moving on to the next recipe. :)

If an item that does not exist is being used as a crafting component; maybe then either consider throwing an error or again, letting the player know that item does not exist without modifying that recipe. :)

**Comment by jaredlll08** [comment]
Firstly, 1.7.10 is no longer supported.
Secondly, I will not be changing it since if an item is missing, people need to know that (and a chat message doesn't suffice)
Lastly, if you are already editing configs, you can remove some lines of scripts.
