### ISSUE TITLE
MineTweaker error...

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#407]
ERROR: Error parsing MineTweakerRecipieMaker.zs:38 -- ] or , expected

I have no idea what I'm doing wrong. I installed ModTweaker, MTlib, I did everything as the wiki said. Here it is:  

//#MARKER ADD
val apple = <minecraft:apple>;
mods.tconstruct.Drying.addRecipe(<minecraft:golden_apple:0>, apple.withTag({display:{Lore:[This apple seems special...]}}), 50);

Here is the how to on the wiki:

//InputStack, OutputStack, Time in Ticks
mods.tconstruct.Drying.addRecipe(<minecraft:tallgrass:1>, <minecraft:deadbush>, 50);

I have no idea what I'm doing wrong...   Can someone help me please?

**Comment by jaredlll08** [comment]
You need to post your script using pastebin.

**Comment by ghost** [comment]
Sorry... Here it is: http://pastebin.com/hfuCfksq
By the way, when I did the exact same recipe for MineTweaker3 for Minecraft 1.7.10, it worked no problem.
But I'm using MineTweaker3 for Minecraft 1.10 and it's not working.

**Comment by ghost** [comment]
I found a workaround and now it works, but I would be happier if someone tells me how to tag above can work. Thanks.

**Comment by jaredlll08** [comment]
The problem is that you are not putting your string in quotation marks, like
```
"this is a String"
```

**Comment by ghost** [comment]
THANK YOU!!! It works perfectly!
