### ISSUE TITLE
[1.11] "Error executing script.zs: null" when editing dungeon loot

### ISSUE THREAD

**Issue by TheDeviantCrafter** [stanhebben/MineTweaker3#411]
I'm attempting to edit dungeon loot. I've added the following line, copied exactly from the Minetweaker wiki page:

`vanilla.loot.addChestLoot("dungeonChest", <minecraft:diamond>.weight(100));`

I've also tried replacing `dungeonChest` with the names used by vanilla loot tables, which resulted in this:

`vanilla.loot.addChestLoot("abandoned_mineshaft ", <minecraft:diamond>.weight(100));`

The same error occured. Is it possible that syntax changed in the 1.11 port? Was this functionality dropped?

**Comment by jaredlll08** [comment]
Functionality hasn't been around since 1.8, use Loottabletweaker
