### ISSUE TITLE
Scripts are not loading on restart

### ISSUE THREAD

**Issue by raziel23x** [stanhebben/MineTweaker3#412]
Okay We are running FTB Infinity Evolved 1.7.10 and minetweaker3

[InfinityPackWideChanges.zip](https://github.com/stanhebben/MineTweaker3/files/802940/InfinityPackWideChanges.zip)

 is not loading on restart We have to manually do /mt reload to get the changes to take place manually.

Is there a fix to this issue like it loading the .zs file when the server restarted because right now we have to manually reload the script on every reboot

**Comment by jaredlll08** [comment]
FTBLIB issue.

**Comment by Blue64** [comment]
In other words: [Won't Fix] Label
