### ISSUE TITLE
Cannot resolve

### ISSUE THREAD

**Issue by Gunner76th** [stanhebben/MineTweaker3#416]
http://pastebin.com/RC3ER33e

I am getting this error when I attempt to use this script to change a recipe for Extra Utilities 2: http://pastebin.com/zzxQii2s

**Comment by jaredlll08** [comment]
You have the wrong item name.

**Comment by Gunner76th** [comment]
![2017-03-02_11 37 41](https://cloud.githubusercontent.com/assets/5566872/23516911/a4683b02-ff3c-11e6-8fd7-5acb765edb97.png)

**Comment by jaredlll08** [comment]
Use /mt hand in it.

**Comment by Gunner76th** [comment]
![2017-03-02_11 38 58](https://cloud.githubusercontent.com/assets/5566872/23516957/d329b1c8-ff3c-11e6-9dfc-9d8f3ff98a35.png)
Same as what I have

**Comment by Gunner76th** [comment]
Also I even removed the last row of null entries, and it still does it.

**Comment by jaredlll08** [comment]
Then they are registering their item too late, nothing I can do about that.

**Comment by Gunner76th** [comment]
would that explain why I get this error when I just try to do recipes.remove? 
![2017-03-02_11 40 49](https://cloud.githubusercontent.com/assets/5566872/23517103/5b3b83fc-ff3d-11e6-9176-2dc614b3452f.png)

**Comment by Gunner76th** [comment]
Oh derp, I think I just seen what is causing everything. in the remove function I forgot the closing >

**Comment by Gunner76th** [comment]
that fixed it. Seems the OP error was because in recipes.remove(<extrautils2:Miner) I forgot the > before the )

Once I fixed that both the remove and add functions worked properly. That closes this issue, now to try and hopefully figure out my Hellfire forge and Master Ritual Stone recipes
https://github.com/stanhebben/MineTweaker3/issues/414

Since this was a user/script error, I am considering this issue closed. I will let you close it when you are ready.

**Comment by Blue64** [comment]
alternatively, if you look at the "`Comment`" Button before you type anything for a comment, since you are the one who opened the Bug Report, you are also able to close this.
