### ISSUE TITLE
Cannot remove recipe

### ISSUE THREAD

**Issue by MichinYeoja** [stanhebben/MineTweaker3#419]
my pack has a recipe that is made with any axe and any wood log turning it into 8 planks. for my pack it is a bit op. not sure how to find where the modded recipe is coming from but its not removable. is this a minetweaker issue or mod conflict

**Comment by jaredlll08** [comment]
Can't help without scripts and logs. 
Either way, you are either removing it incorrectly, in which case look at the wiki. 
Or a mod is adding the recipe after we change them, try mt reload, see if that works 
If none of those work, I can't help you.

**Comment by Blue64** [comment]
I would look at the OreDict for the Axes, & the Logs, seeing if there is any recipes for those OreDict in any of the `%AppData%\.minecraft\scripts\*.zs` Files (`* acting in this case as a wildcard, also assuming you are on Windows, also assuming the format hasn't changed from .zs`).

I have a general Checklist for Bug Reports located here:
https://github.com/Blue64/Misc/issues/3
(considering how frequently I've referenced it today alone, I'd consider it a good use of my Misc Repo)
You are also free to reference it too @jaredlll08 should you ever think it relevant (considering where we are, you're probably gonna get a ton of mileage outta it lol)

If you are on `Windows` then also in your `\.minecraft\` folder there should be a file named `minetweaker.log` and in your `\.minecraft\logs\` folder you should find a few different files, including
- `fml-client-latest.log`
- `fml-client-1.log`
- `fml-client-2.log`
- `fml-client-3.log`

some of these might be missing, but these are the 4 most recent Log Files for your last 4 MineCraft Launches (for better, or worse) which would give us a rather detailed output, you want to find (in those Logs) where it mentions the files in your `\.minecraft\scripts\` Folder and let us know what it says.

**_`ALSO`_** you forgot to mention if this is located on a `Server` or on `Single Player`. All of my instructions are for `Single Player`. The `Servers' Instructions` aren't very different though, but you'd need to look at the `Servers' Files`, not just your own. on `Servers`, the `Servers' Scripts` are what dictates the `Recipes`, no matter what the `Players' Scripts` try to do.
