### ISSUE TITLE
[1.10.2] Everytime I add a block to chisel group that group can't be found on reload / load.

### ISSUE THREAD

**Issue by StoneLegion** [stanhebben/MineTweaker3#424]
I wanted to use Quarried Stone and Abyssal Stone in Chisel for the replacement of Marble / Basalt World gen. I liked the world gen style and it's a great fit since we have I think about 4-5 marble spawning mods anyways.

At first I was adding marble in as
```
<ore:stoneMarble>.add(<railcraft:generic:9>);
```
This worked fine in chisel but would never show up in JEI when looking for uses for the railcraft quarried stone.

So I googled and found out about the chisel groups in MT. So I went ahead and commented the above line and added this instead:
```
mods.chisel.Groups.addVariation("marble", <railcraft:generic:9>);
```

This sadly caused the following error:
```
[SERVER_STARTING][SERVER][ERROR] Cannot find group marble
```

So I tried it for Abyssal Stone as Basalt:
```
mods.chisel.Groups.addVariation("basalt", <railcraft:generic:8>);
```
Also got:
```
[SERVER_STARTED][SERVER][ERROR] Cannot find group basalt
```

I tried also adding the groups back
```
mods.chisel.Groups.addGroup("marble");
```
But it seem to make no difference at least letting me see the recipes for the Quarried Stone via JEI.

**tltr;**
This:
```
mods.chisel.Groups.addVariation("basalt", <railcraft:generic:8>);
mods.chisel.Groups.addVariation("marble", <railcraft:generic:9>);
```

Causes:
```
[SERVER_STARTED][SERVER][ERROR] Cannot find group basalt
[SERVER_STARTING][SERVER][ERROR] Cannot find group marble
```

The only way to get Quarried Stone (railcraft:generic:9) to show up using chisel is:
```
<ore:stoneMarble>.add(<railcraft:generic:9>);
```

But it will not show in JEI Correctly for uses/etc.,

**Comment by StoneLegion** [comment]
Opps I sadly think this a modtweaker issue will close.

**Comment by Blue64** [comment]
if you can't get the script working though, feel free to ask. that IS one of the guidelines of the Bug Tracker
`:D`
