### ISSUE TITLE
IndustrialCraft recipes not work in JEI

### ISSUE THREAD

**Issue by Zaakjin** [stanhebben/MineTweaker3#427]
When load any script with any recipe all Industrial Craft recipes in JEI stop working.
Minecraft version 1.10.2
PS. Sorry for my english.

**Comment by Blue64** [comment]
You might be able to understand this:
https://github.com/Blue64/Misc/issues/3 (Checklist)
https://github.com/Blue64/Misc/issues/2 (GitHub Formatting)
those should help you, if not currently, then perhaps in the future at some point.
