### ISSUE TITLE
Scripting issues Edit: NVM I fixed it. forgot some things

### ISSUE THREAD

**Issue by ClownHappy** [stanhebben/MineTweaker3#452]
![screenshot 85](https://user-images.githubusercontent.com/37893782/38166071-00dee9b0-34db-11e8-90e7-9645dc005ed0.png)
 I get this error whenever I try to reload the script I created. 
this is my script

recipes.addshaped(<minecraft:fire> * 3,[[<minecraft:blaze_powder>,<minecraft:gunpowder>,<minecraft:blaze_powder>],[<minecraft:gunpowder>,<minecraft:diamond>,<minecraft:gunpowder>],[<minecraft:blaze_powder>.<minecraft:gunpowder>.<minecraft:blaze_powder>]]

Don't get mad I didn't feel like declaring values.

Any help is appreciated. I just wanted fire.

**Comment by VariableVixen** [comment]
> NVM I fixed it

If you fixed it, please close the issue, and (as a courtesy to others who may have similar problems) explain what was wrong.

**Comment by ClownHappy** [comment]
Forgot some colons and commas
