### ISSUE TITLE
"no main manifest attribute" when trying to run Minetweaker

### ISSUE THREAD

**Issue by Luinmeriliel** [stanhebben/MineTweaker3#468]
Nothing happens when I try to run the .jar to open minetweaker 3.0.10B
Other jar files such as optifine work fine so it's not a association issue on my end.
When I try to run it with the  java -jar "filename".jar command in Powershell (with admin on) i get the error "no main manifest attribute." It seems there is something wrong with the file itself but I havent been able to get any other versions of MT3 working. I don't know how to extract and fix the java code myself either. 
Please, I'm at wits end here.

**Comment by VariableVixen** [comment]
It's a minecraft mod. You don't run it.

**Comment by Luinmeriliel** [comment]
Wow. I'm a retard. Never used MT before if you didn't realize...
