### ISSUE TITLE
Craft Tweaker | ; expected

### ISSUE THREAD

**Issue by teleportx** [stanhebben/MineTweaker3#479]
Hi!
I don't understand where I missed the comma. Can you point out where I missed it?

ERROR:
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: AdvancedCrafts.zs}
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing AdvancedCrafts.zs:8 -- ; expected
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: CreativeItems.zs}
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing CreativeItems.zs:11 -- ; expected

Code:
https://pastebin.com/BuD1abGQ - Advanced Crafts
https://pastebin.com/ZspiKkQK - Creative Items

**Comment by kindlich** [comment]
First, CraftTweaker's issue tracker is over here:
https://github.com/CraftTweaker/CraftTweaker

Second, your print Statements don'T have their `;`
