### ISSUE TITLE
Minetweaker Recipe Maker doesnt work

### ISSUE THREAD

**Issue by Tamagoshi3dmax** [stanhebben/MineTweaker3#480]
I saw in the internet...that i can use MTRM to get recipe for creative items...i download MTRM...did the same thing a youtuber did (except the save-all command that doesnt work too)...i saw a script file in minecraft folder...saw the sz file...and the recipe i created is there...but in game the recipe doesnt work. im trying to get a recipefor Creative Energy Cube from mekanism...i dont know what im doing wrong....because in the video...the guy says that he got a recipe for the block he wanted. 
https://www.youtube.com/watch?v=fUv7kShgi7s   the video i watched to try to learn how to use MTRM.

CraftTweaker and ModTweaker are easier to work or they are hard than MTRM?

for me...the easier is better...because i dont know how to work with codes...
thanks

**Comment by jaredlll08** [comment]
This repository is no longer used.

We generally tell people to write the scripts themselves.

We don't make Minetweaker Recipe Maker, go report it to them, not us.
