### ISSUE TITLE
Can not rename Thermal Expansion block

### ISSUE THREAD

**Issue by Ionaru** [stanhebben/MineTweaker3#49]
I tried renaming Thermal Expansion's 'Tinker's Alloy Block' to 'Bronze Block'.
This is the line I use: 
`<2010:8>.displayName = "Bronze Block";`
I also tried:
`<tile.thermalexpansion.storage:8>.displayName = "Bronze Block";`

Minetweaker.log outputs: 
`INFO: Translating tile.thermalexpansion.storage.bronze.name.name to Bronze Block`

However, the block is still named 'Tinker's Alloy Block' in NEI and in-game. 

Minecraft version: 1.6.4
Forge version: 9.11.1.965
MineTweaker version: 1.6.4-3.0.7
Thermal Expansion version: 3.0.0.7

**Comment by Barhandar** [comment]
Items on 1.7.10 also refuse to be renamed. Given that Minetweaker 2's renaming worked just fine on Thermal Expansion in 1.6.4, might be an issue with newer version's code.

**Comment by skaviouz** [comment]
I don't know if it's related but, some blocks if you rename it (like with the anvil) it'll lose it's name when you place it into the world and pick it up.
Thermal Expansion blocks don't lose their names when you do the same task.

**Comment by jaredlll08** [comment]
The problem with this, is that they use ItemBlocks, and override the getItemStackDisplayName, there isn't much that we can do about that :/
