### ISSUE TITLE
Bug Some recipe removal does not apply until manually reloaded

### ISSUE THREAD

**Issue by HellishINC** [stanhebben/MineTweaker3#60]
When using MT3 0.8b with "Sync" mod to remove it's recipe (and later add custom), mt3 does not take effect until using /mt reload.

// Sync ===
//		Core:
recipes.remove(<Sync:Sync_ItemPlaceholder>);
//		Treadmill:
recipes.remove(<Sync:Sync_BlockPlacer:2>);

// Variables:
val blueDye = <ore:dyeBlue>;
val stone = <ore:stone>;
val ironIngot = <ore:ingotIron>;
val aluminiumIngot = <ore:ingotAluminum>;

//	Sync ===
//		Core:
recipes.addShaped(<Sync:Sync_ItemPlaceholder>, [
	[<ExtraUtilities:pipes>,<minecraft:dye:4>,<ExtraUtilities:pipes>],
	[<minecraft:ender_pearl>,<TConstruct:heartCanister>,<minecraft:ender_pearl>],
	[<minecraft:redstone>,<minecraft:repeater>,<minecraft:redstone>]
	]);

side note: your thread at MCF still links to 3.0.7

**Comment by jaredlll08** [comment]
what usually happens is that the mod is adding recipes too late, there is nothing we can do about it. (I experience this with modtweaker as well for some stuff (mainly mekanism) )

**Comment by Yulife** [comment]
Both are iChun's mods, you could make an issue on his repos :)

**Comment by jaredlll08** [comment]
Checked the source code, Ichun registers his stuff too late
