### ISSUE TITLE
NEI Script Does not load on start

### ISSUE THREAD

**Issue by MrPotatoGaming** [stanhebben/MineTweaker3#71]
For some reason NEI related scripts don't load on client-start. They load fine when using the "/minetweaker reload" command though. This doesn't cause any over-arching problems with just NEI and most NEI Plugins installed. However, when Waila is thrown into the mix things get a little funky. 

When the inventory is open and the NEI panel is either A) searching for items or B) loading a page changed/hidden blocks the client lags a lot. And also begins to spam "[14:00:12] [NEI Item Filtering/WARN] [Waila/]: Error while filtering items : java.util.ConcurrentModificationException : null:" about 300 times a second. 

Even with watchdog enabled, I can't get you any stacktraces to help direct you in the way of issue. My only idea is that it's because NEI is changed after final initialization. But I have no idea.  The log is too large for pastebin. If you need it, I'll have it backed up. From the seems of it though nothing really stands out as a tattletale sign.

**Comment by jaredlll08** [comment]
So is this resolved or not? @MrPotatoGaming says it is, but @scorpion421  says it isn't...

**Comment by jaredlll08** [comment]
No information on this issue, also
NEI support is broken, and seems to be unfixable due to how hacky NEI actually is. this has been resolved in 1.8.x due to JEI
