### ISSUE TITLE
[3.0.9] Error when using /mt recipes

### ISSUE THREAD

**Issue by JasonMcRay** [stanhebben/MineTweaker3#75]
I was really excited about re-implementing the /mt recipes function, but when I use that, i recieve an error: An unknown error occured while attempting to perform this command.

Here is an output I get in the console: http://pastebin.com/99r1VL3x
And this when i just use /mt recipes hand: http://pastebin.com/AQR3YM0a

Doing /mt reload is not fixing that problem, and also /mt reload doesnt cause any errors.

**Comment by jaredlll08** [comment]
I just made changes that should fix the issue here, or atleast the hand issue, try on the next minetweaker version (whenever that is...)
