### ISSUE TITLE
[3.0.9] Buildcraft - Additional recipes for assembly table not working?

### ISSUE THREAD

**Issue by Dallandra** [stanhebben/MineTweaker3#78]
I am not sure if this is a problem with Minetweaker or the machine (and thus Buildcraft) itself, but since BC support was just now added, I assume it might be a problem on this end.

I am currently working on some recipe replacements to make things like Railcraft and Buildcraft work in TerraFirmaCraft. Just a few minutes ago I have reached the BC chipsets and noticed an oddity.

The assembly table seems to only be able to craft the first recipe that has been added to it of an item. As in, you make an iron chipset with a piece of redstone and a vanilla iron ingot normally. If I add another recipe for an iron chipset using redstone and a wrought iron ingot from TFC, the possible output for an iron chipset shows up and is selectable, but the lasers won't start powering the assembly table, thus the item won't get crafted.

If I remove the vanilla recipe first before adding the TFC-compatible one, it works just fine. If I add additional recipes now that make iron chipsets, they will show up on the table but behave like detailed in the previous example.

I have tried using oredictionary entries instead for the iron, but this results in the game sending me to the multiplayer server select screen when trying to access an assembly table (in singleplayer!) and loading into the world and trying to access any assembly table thereafter crashes the game completely with this error log: http://pastebin.com/ZdqwFiPY
Accessing an assembly table with any materials already in it produces this error log: http://pastebin.com/8dgYYahz

Again I am assuming this is a problem with Buildcraft moreso than Minetweaker, but since BC compatibility is apparently still very new, I thought it might be helpful to drop this here first.

**Comment by jaredlll08** [comment]
We no longer add buildcraft support, if it is still an issue, report to buildcraft
