### ISSUE TITLE
Planter add Plantable, multiple arguments 

### ISSUE THREAD

**Issue by MrPotatoGaming** [stanhebben/MineTweaker3#90]
Minetweaker Version: 3.0.9B
MFR: v2.8.0c3-591
First Script: Planter.addPlantable(<magicalcrops:magicalcrops_MagicSeedsEssence>);
Script and Error: http://pastebin.com/VMuHXtxQ

What I'm expecting to happen is for the seeds to be planted as if right clicked on tilled soil, much as other seeds function in the harvester. However the seeds just vanish. 

So after looking at the old minetweaker tutorials, something was mentioned about three arguments. I tried using it, and got the error after the script listed in the link.

**Comment by jaredlll08** [comment]
This is most likely due to magical crops not being able to be planted on anything but dirt.
Also your syntax is wrong. it should be 
'''
mods.mfr.Planter.addPlantable(<magicalcrops:magicalcrops_MagicSeedsEssence>);
'''
