### ISSUE TITLE
Feature Request: Adding world gen stuff

### ISSUE THREAD

**Issue by skaviouz** [stanhebben/MineTweaker3#93]
##### schematic files
 * orientation/rotation
 * adjacent schematic files, with XYZ modifiers ofc. Location based on center, default to S/W if 2/4 block conflict for centerness?
 * Y changes based on terrain, center point of schematic highest dirt block within +/- 10 blocks, editable? This modifies the first modifiers, so you don't have basements going above ground?

##### ores / single block placement
 * custom blocks (like spawning chests with custom loot? or generating from normal loot) or nbt data, or just localized names like normal.
 * how many *veins* per chunk
 * min / max y - that vein spawns at
 * maz x/y/z size
 * x/y/z position modifiers ofc!
 * chance of each adjacent block having another instance placed down?
 * replace X, limiting or non-limiting. e.g. any stone/endstone/netherrack, to include ore dictionary, but not if it's railcraft:QuarriedStone; if there is no required blocks found, skip that ore. Could also limit based on adjacent blocks. No two chests can ever touch on the same Y axis if 2+ chests are adjacent with the same Y axis for example. 
 * retrogen, but maybe requires a cmd to retrogen all scripts marked for retrogen with an id number? with a cmd that says it's in progress, msg every 15 seconds that says percent?, and operation complete msg. and the ability to mark for asynchronous operation, for those who add tons of blocks to the air?!?

This would be cool, make custom loot chests, replace grass blocks, add +1 Y to modifier, and you'll have loot chests above ground :)

I saw the planned 3.1.2 for trees, and saw custom blocks for 3.1.0 so i thought it would match suite

Would also help remove many simple mods, like pam's clay spawn, and just be added as a script.

**Comment by jaredlll08** [comment]
CoFHCore allows you to do very complex ore generation and other generation, I would suggest looking at that, considering we load scripts at world startup, I am pretty sure that it would be too late to generate new things.

**Comment by Yulife** [comment]
Well Stan has plans so keep it open?
