### ISSUE TITLE
[3.0.9B] Removing specific shapless recipes kills all shaped recipes

### ISSUE THREAD

**Issue by Belgabor** [stanhebben/MineTweaker3#97]
If you remove a specific shapeless recipe, for example

```
recipes.removeShapeless(<minecraft:iron_ingot> * 1, [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]);
```

all shaped recipes for the target item are gone. In our pack we have three iron nuggets, two provide nugget to ingot shaped recipes, both these and the vanilla ingot from block recipe are gone.
If you use the generic remove-all syntax,

```
recipes.removeShapeless(<minecraft:iron_ingot>);
```

the shaped recipes are fine.

**Comment by jaredlll08** [comment]
should be fixed in this
https://github.com/jaredlll08/CraftTweaker/commit/33ed5fa877ba372df6bf0b259337de8eb836f232
